-- verwijder alle bag 1.0 tabellen en eventueel views die daarvan gebruik maken
-- in versie 4.0.0 is de BAG 1 ondersteuning verwijderd
-- de BAG 1.0 tabellen en views zijn niet meer nodig en kunnen verwijderd worden
drop materialized view if exists mb_kad_onrrnd_zk_adres cascade;
drop materialized view if exists mb_koz_rechth cascade;
drop materialized view if exists mb_avg_koz_rechth cascade;
drop materialized view if exists mb_ben_obj_nevenadres cascade;
drop materialized view if exists mb_benoemd_obj_adres cascade;
drop materialized view if exists mb_pand cascade;
drop view if exists vb_ligplaats_adres cascade;
drop view if exists vb_standplaats_adres cascade;
drop view if exists vb_vbo_adres cascade;
drop materialized view if exists mb_adres cascade;
drop table if exists wnplts_archief cascade;
drop table if exists wnplts cascade;
drop table if exists verblijfsobj_pand_archief cascade;
drop table if exists verblijfsobj_pand cascade;
drop table if exists verblijfsobj_nummeraand cascade;
drop table if exists verblijfsobj_nummeraan_archief cascade;
drop table if exists verblijfsobj_archief cascade;
drop table if exists verblijfsobj cascade;
drop table if exists standplaats_nummeraand_archief cascade;
drop table if exists standplaats_nummeraand cascade;
drop table if exists standplaats_archief cascade;
drop table if exists standplaats cascade;
drop table if exists pand_archief cascade;
drop table if exists pand cascade;
drop table if exists ovrg_addresseerb_obj_aand cascade;
drop table if exists ovrg_addresseerb_obj_a_archief cascade;
drop table if exists overig_terrein_gebruiksdoel cascade;
drop table if exists overig_terrein_archief cascade;
drop table if exists overig_terrein cascade;
drop table if exists overig_gebouwd_obj_archief cascade;
drop table if exists overig_gebouwd_obj cascade;
drop table if exists overig_bouwwerk_archief cascade;
drop table if exists overig_bouwwerk cascade;
drop table if exists openb_rmte_wnplts cascade;
drop table if exists openb_rmte_gem_openb_rmte cascade;
drop table if exists openb_rmte cascade;
drop table if exists nummeraand_archief cascade;
drop table if exists nummeraand cascade;
drop table if exists ligplaats_nummeraand_archief cascade;
drop table if exists ligplaats_nummeraand cascade;
drop table if exists ligplaats_archief cascade;
drop table if exists ligplaats cascade;
drop table if exists gem_openb_rmte_archief cascade;
drop table if exists gem_openb_rmte cascade;
drop table if exists gebouwd_obj_gebruiksdoel cascade;
drop table if exists gebouwd_obj_archief cascade;
drop table if exists gebouwd_obj cascade;
drop table if exists benoemd_terrein_benoemd_terrei cascade;
drop table if exists benoemd_terrein_benoem_archief cascade;
drop table if exists benoemd_terrein_archief cascade;
drop table if exists benoemd_terrein cascade;
drop table if exists benoemd_obj cascade;
drop table if exists addresseerb_obj_aand_archief cascade;
drop table if exists addresseerb_obj_aand cascade;