tag-template: "$NEXT_PATCH_VERSION"
name-template: v$NEXT_PATCH_VERSION 🎁

version-template: "$MAJOR.$MINOR.$PATCH"

template: |
  ## Upgrade instructies
  
  Upgrade instructies voor deze release zijn te vinden op: https://github.com/B3Partners/brmo/wiki/Upgrade-$PREVIOUS_TAG-naar-v$NEXT_PATCH_VERSION
  
  ## Download

  ZIP file met war files en scripts: https://github.com/B3Partners/brmo/releases/download/v$NEXT_PATCH_VERSION/brmo-dist-$NEXT_PATCH_VERSION-bin.zip
  Beschikbare docker images: https://github.com/orgs/B3Partners/packages?repo_name=brmo 

  ## 🛠 Aanpassingen

  $CHANGES


categories:
  - title: 🚀 Nieuwe functies en verbeteringen
    when:
      labels:
        - enhancement
        - feature
        - 'functie wens'
  - title: 🔨 Security fixes en updates
    when:
      labels:
        - security
  - title: ⛓️‍💥 Breaking changes
    when:
      label: breaking      
  - title: 🐛 Bug Fixes
    when:
      labels:
        - bug
        - fix
        - bugfix
        - regressie
  - title: ⚠️ Deprecated of verwijderd
    when:
      label: deprecated
  - title: 📖 Documentatie
    when:
      labels: 
        - documentation
        - 'vraag of documentatie'
  - title: ♻ Dependency updates
    when:
      labels:
        - dependencies
        - 'dependency update'
    collapse-after: 10
  - title: 🚦 Tests en Infrastructuur
    when:
      labels:
        - tests
        - infrastructure
        - 'bouw- en testinfrastuctuur'
    collapse-after: 10

replacers:
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2'
