//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 02:40:39 PM CET 
//


package nl.b3p.topnl.top100nl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HoofdverkeersgebruikT100Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HoofdverkeersgebruikT100Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="snelverkeer"/>
 *     &lt;enumeration value="gemengd verkeer"/>
 *     &lt;enumeration value="busverkeer"/>
 *     &lt;enumeration value="fietsers, bromfietsers"/>
 *     &lt;enumeration value="voetgangers"/>
 *     &lt;enumeration value="vliegverkeer"/>
 *     &lt;enumeration value="overig"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HoofdverkeersgebruikT100Type", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/top100nl/1.1.0")
@XmlEnum
public enum HoofdverkeersgebruikT100Type {

    @XmlEnumValue("snelverkeer")
    SNELVERKEER("snelverkeer"),
    @XmlEnumValue("gemengd verkeer")
    GEMENGD_VERKEER("gemengd verkeer"),
    @XmlEnumValue("busverkeer")
    BUSVERKEER("busverkeer"),
    @XmlEnumValue("fietsers, bromfietsers")
    FIETSERS_BROMFIETSERS("fietsers, bromfietsers"),
    @XmlEnumValue("voetgangers")
    VOETGANGERS("voetgangers"),
    @XmlEnumValue("vliegverkeer")
    VLIEGVERKEER("vliegverkeer"),
    @XmlEnumValue("overig")
    OVERIG("overig");
    private final String value;

    HoofdverkeersgebruikT100Type(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HoofdverkeersgebruikT100Type fromValue(String v) {
        for (HoofdverkeersgebruikT100Type c: HoofdverkeersgebruikT100Type.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
