//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 02:40:39 PM CET 
//


package nl.b3p.topnl.top100nl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for HoogteType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HoogteType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://register.geostandaarden.nl/gmlapplicatieschema/top100nl/1.1.0}_Top100nlObjectType">
 *       &lt;sequence>
 *         &lt;element name="geometrie" type="{http://register.geostandaarden.nl/gmlapplicatieschema/top100nl/1.1.0}LijnOfPuntPropertyType"/>
 *         &lt;element name="hoogte" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="typeHoogte" type="{http://register.geostandaarden.nl/gmlapplicatieschema/top100nl/1.1.0}TypeHoogteT100Type"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HoogteType", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/top100nl/1.1.0", propOrder = {
    "geometrie",
    "hoogte",
    "typeHoogte"
})
public class HoogteType
    extends Top100NlObjectType
{

    @XmlAnyElement
    protected Element geometrie;
    protected double hoogte;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TypeHoogteT100Type typeHoogte;

    /**
     * Gets the value of the geometrie property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     
     */
    public Element getGeometrie() {
        return geometrie;
    }

    /**
     * Sets the value of the geometrie property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     
     */
    public void setGeometrie(Element value) {
        this.geometrie = value;
    }

    /**
     * Gets the value of the hoogte property.
     * 
     */
    public double getHoogte() {
        return hoogte;
    }

    /**
     * Sets the value of the hoogte property.
     * 
     */
    public void setHoogte(double value) {
        this.hoogte = value;
    }

    /**
     * Gets the value of the typeHoogte property.
     * 
     * @return
     *     possible object is
     *     {@link TypeHoogteT100Type }
     *     
     */
    public TypeHoogteT100Type getTypeHoogte() {
        return typeHoogte;
    }

    /**
     * Sets the value of the typeHoogte property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeHoogteT100Type }
     *     
     */
    public void setTypeHoogte(TypeHoogteT100Type value) {
        this.typeHoogte = value;
    }

}
