
create table hoogte(
      id bigint generated by default as identity (start with 1),
      identificatie varchar(255),
      topnltype varchar(255),
      brontype varchar(255),
      bronactualiteit timestamp,
      bronbeschrijving varchar(255),
      bronnauwkeurigheid double precision,
      objectBeginTijd timestamp,
      objectEindTijd timestamp,
      visualisatieCode integer,
      typeHoogte varchar(255),
      referentieVlak varchar(255),
      hoogte double precision,
      primary key (id)
);