create schema top250nl;

create table top250nl.hoogte(
      id bigint generated by default as identity (start with 1),
      identificatie varchar(255),
      topnltype varchar(255),
      brontype varchar(255),
      bronactualiteit timestamp,
      bronbeschrijving varchar(255),
      bronnauwkeurigheid double precision,
      objectBeginTijd timestamp,
      objectEindTijd timestamp,
      visualisatieCode integer,
      typeHoogte varchar(255),
      referentieVlak varchar(255),
      hoogte double precision,
      primary key (id)
);

create schema top50nl;

create table top50nl.hoogte(
      id bigint generated by default as identity (start with 1),
      identificatie varchar(255),
      topnltype varchar(255),
      brontype varchar(255),
      bronactualiteit timestamp,
      bronbeschrijving varchar(255),
      bronnauwkeurigheid double precision,
      objectBeginTijd timestamp,
      objectEindTijd timestamp,
      visualisatieCode integer,
      typeHoogte varchar(255),
      referentieVlak varchar(255),
      hoogte double precision,
      primary key (id)
);