
-- cleanup
WHENEVER SQLERROR CONTINUE NONE;
DROP TABLE brmo_metadata CASCADE CONSTRAINTS PURGE;
DROP TABLE adres CASCADE CONSTRAINTS PURGE;
DROP TABLE appartementsrecht CASCADE CONSTRAINTS PURGE;
DROP TABLE natuurlijkpersoon CASCADE CONSTRAINTS PURGE;
DROP TABLE nietnatuurlijkpersoon CASCADE CONSTRAINTS PURGE;
DROP TABLE onroerendezaak CASCADE CONSTRAINTS PURGE;
DROP TABLE onroerendezaakbeperking CASCADE CONSTRAINTS PURGE;
DROP TABLE onroerendezaakfiliatie CASCADE CONSTRAINTS PURGE;
DROP TABLE perceel CASCADE CONSTRAINTS PURGE;
DROP TABLE persoon CASCADE CONSTRAINTS PURGE;
DROP TABLE publiekrechtelijkebeperking CASCADE CONSTRAINTS PURGE;
DROP TABLE recht CASCADE CONSTRAINTS PURGE;
DROP TABLE stuk CASCADE CONSTRAINTS PURGE;
DROP TABLE stukdeel CASCADE CONSTRAINTS PURGE;
DROP TABLE archief_appartementsrecht CASCADE CONSTRAINTS PURGE;
DROP TABLE archief_onroerendezaak CASCADE CONSTRAINTS PURGE;
DROP TABLE archief_onroerendezaakfiliatie CASCADE CONSTRAINTS PURGE;
DROP TABLE archief_perceel CASCADE CONSTRAINTS PURGE;
DROP TABLE archief_recht CASCADE CONSTRAINTS PURGE;
TRUNCATE TABLE user_sdo_geom_metadata;
