comment on column pv_adr_object_nummeraand.identif                             is '[PK] AN16 - Identificatie adresseerbaar object aanduiding';
comment on column pv_adr_object_nummeraand.dat_beg_geldh                       is '';
comment on column pv_adr_object_nummeraand.dat_eind_geldh                      is 'OnvolledigeDatum - Datum einde geldigheid addresserbaar object aanduiding';
comment on column pv_adr_object_nummeraand.huinummer                           is 'N5 - Huisnummer';
comment on column pv_adr_object_nummeraand.huinummertoevoeging                 is 'AN4 - Huisnummertoevoeging';
comment on column pv_adr_object_nummeraand.huisletter                          is 'AN1 - Huisletter';
comment on column pv_adr_object_nummeraand.postcode                            is 'AN6 - Postcode';
comment on column pv_adr_object_nummeraand.naam_openb_rmte                     is 'AN80 - Naam openbare ruimte';
comment on column pv_adr_object_nummeraand.gem_code                            is ' [PK] N4 - Gemeentecode';
comment on column pv_adr_object_nummeraand.gem_naam                            is 'AN40 - Gemeentenaam';
comment on column pv_adr_object_nummeraand.wpl_naam                            is 'AN80 - Woonplaatsnaam';
comment on column pv_adr_object_nummeraand.indic_hoofdadres                    is 'boolean - Indicatie hoofdadres';
comment on column pv_adr_object_nummeraand.status                              is 'AN80 - Nummeraanduidingstatus';
comment on column pv_ander_natuurlijk_persoon.sc_identif                       is '[PK] AN32, FK naar nat_prs.sc_identif - Identificatie';
comment on column pv_ander_natuurlijk_persoon.geboortedatum                    is 'N8 - Geboortedatum';
comment on column pv_ander_natuurlijk_persoon.overlijdensdatum                 is 'N8 - Overlijdensdatum';
comment on column pv_appartementsrecht.ka_appartementsindex                    is 'Groepsattribuut Kadastrale aanduiding APPARTEMENTSRECHT.Appartementsindex - Appartementsindex';
comment on column pv_appartementsrecht.ka_kad_gemeentecode                     is 'Groepsattribuut Kadastrale aanduiding APPARTEMENTSRECHT.Kadastrale gemeentecode - Kadastrale gemeentecode';
comment on column pv_appartementsrecht.ka_perceelnummer                        is 'Groepsattribuut Kadastrale aanduiding APPARTEMENTSRECHT.Perceelnummer - Perceelnummer';
comment on column pv_appartementsrecht.ka_sectie                               is 'Groepsattribuut Kadastrale aanduiding APPARTEMENTSRECHT.Sectie - Sectie';
comment on column pv_appartementsrecht.sc_kad_identif                          is '[PK] N15, FK naar kad_onrrnd_zk.kad_identif - Kadastrale identificatie';
comment on column pv_benoemd_obj_kad_onr_zk.fk_nn_lh_tgo_identif               is '[FK] AN16, FK naar benoemd_obj.identif';
comment on column pv_benoemd_obj_kad_onr_zk.fk_nn_rh_koz_kad_identif           is '[FK] N15, FK naar kad_onrrnd_zk.kad_identif';
comment on column pv_benoemd_object.identif                                    is '[PK] AN16 - Benoemd object identificatie';
comment on column pv_benoemd_object.clazz                                      is 'Aanduiding subclass';
comment on column pv_benoemd_terrein.dat_beg_geldh                             is '';
comment on column pv_benoemd_terrein.sc_identif                                is '[PK] AN16, FK naar benoemd_obj.identif - Benoemd object identificatie';
comment on column pv_benoemd_terrein.clazz                                     is 'Aanduiding subclass';
comment on column pv_benoemd_terrein.datum_einde_geldh                         is 'OnvolledigeDatum - Datum einde geldigheid benoemd terrein';
comment on column pv_benoemd_terrein.bt_geom                                   is 'GM_Surface - Benoemd terrein geometrie';
comment on column pv_gebouwd_obj_gebruiksdoel.gebruiksdoel_gebouwd_obj         is 'AN80 - Gebruiksdoel gebouwd object';
comment on column pv_gebouwd_obj_gebruiksdoel.fk_gbo_sc_identif                is '[FK] AN16, FK naar gebouwd_obj.sc_identif (is FK naar superclass BENOEMD OBJECT)';
comment on column pv_gebouwd_object.dat_beg_geldh                              is '';
comment on column pv_gebouwd_object.sc_identif                                 is '[PK] AN16, FK naar benoemd_obj.identif - Benoemd object identificatie';
comment on column pv_gebouwd_object.clazz                                      is 'Aanduiding subclass';
comment on column pv_gebouwd_object.datum_einde_geldh                          is 'OnvolledigeDatum - Datum einde geldigheid gebouwd object';
comment on column pv_gebouwd_object.oppervlakte_obj                            is 'N6 - Oppervlakte (verblijfs)object';
comment on column pv_gebouwd_object.vlakgeom                                   is 'GM_Surface - Gebouwd object vlakgeometrie';
comment on column pv_gebouwd_object.puntgeom                                   is 'GM_Point - Gebouwd objectpuntgeometrie ';
comment on column pv_gemeente.dat_beg_geldh                                    is '';
comment on column pv_gemeente.code                                             is '[PK] N4 - Gemeentecode';
comment on column pv_gemeente.datum_einde_geldh                                is 'OnvolledigeDatum - Datum einde geldigheid gemeente';
comment on column pv_gemeente.naam                                             is 'AN40 - Gemeentenaam';
comment on column pv_gemeente.geom                                             is 'GM_Surface - Gemeentegeometrie';
comment on column pv_ingeschr_natuurlijk_persoon.sc_identif                    is '[PK] AN32, FK naar nat_prs.sc_identif - Identificatie';
comment on column pv_ingeschr_natuurlijk_persoon.gb_geboortedatum              is 'Groepsattribuut Geboorte INGESCHREVEN NATUURLIJK PERSOON.Geboortedatum - Geboortedatum';
comment on column pv_ingeschr_natuurlijk_persoon.gb_geboorteplaats             is 'Groepsattribuut Geboorte INGESCHREVEN NATUURLIJK PERSOON.Geboorteplaats - Geboorteplaats';
comment on column pv_ingeschr_natuurlijk_persoon.ol_overlijdensdatum           is 'Groepsattribuut Overlijden INGESCHREVEN NATUURLIJK PERSOON.Overlijdensdatum - Overlijdensdatum';
comment on column pv_ingeschr_natuurlijk_persoon.ol_overlijdensplaats          is 'Groepsattribuut Overlijden INGESCHREVEN NATUURLIJK PERSOON.Overlijdensplaats - Overlijdensplaats';
comment on column pv_ingeschr_natuurlijk_persoon.va_loc_beschrijving           is 'Groepsattribuut Verblijfadres INGESCHREVEN NATUURLIJK PERSOON.Locatie beschrijving - Locatie beschrijving';
comment on column pv_kad_onr_zk_aantek.begindatum_aantek_kad_obj               is '';
comment on column pv_kad_onr_zk_aantek.kadaster_identif_aantek                 is '[PK] AN255 - Kadaster identificatie aantekening';
comment on column pv_kad_onr_zk_aantek.aard_aantek_kad_obj                     is '[Enumeratie] - Aard aantekening kadastraal object';
comment on column pv_kad_onr_zk_aantek.beschrijving_aantek_kad_obj             is 'AN124 - Beschrijving aantekening kadastraal object';
comment on column pv_kad_onr_zk_aantek.eindd_aantek_kad_obj                    is 'OnvolledigeDatum - Einddatum aantekening kadastraal object';
comment on column pv_kad_onr_zk_aantek.fk_4koz_kad_identif                     is '[FK] N15, FK naar kad_onrrnd_zk.kad_identif: "behoort bij"';
comment on column pv_kad_onr_zk_his_rel.fk_sc_lh_koz_kad_identif               is '[FK] N15, FK naar kad_onrrnd_zk.kad_identif';
comment on column pv_kad_onr_zk_his_rel.fk_sc_rh_koz_kad_identif               is '[FK] N15, FK naar kad_onrrnd_zk.kad_identif';
comment on column pv_kad_onr_zk_his_rel.aard                                   is ' - Aard';
comment on column pv_kad_onr_zk_his_rel.overgangsgrootte                       is ' - Overgangsgrootte';
comment on column pv_kad_onroerende_zaak.cu_aard_cultuur_onbebouwd             is 'Groepsattribuut Cultuur onbebouwd KADASTRALE ONROERENDE ZAAK.Aard cultuur onbebouwd - Aard cultuur onbebouwd';
comment on column pv_kad_onroerende_zaak.dat_beg_geldh                         is '';
comment on column pv_kad_onroerende_zaak.datum_einde_geldh                     is 'OnvolledigeDatum - Datum einde geldigheid kadastrale onroerende zaak';
comment on column pv_kad_onroerende_zaak.kad_identif                           is '[PK] N15 - Kadastrale identificatie';
comment on column pv_kad_onroerende_zaak.ks_bedrag                             is 'Groepsattribuut Koopsom KADASTRALE ONROERENDE ZAAK.Bedrag - Bedrag';
comment on column pv_kad_onroerende_zaak.ks_koopjaar                           is 'Groepsattribuut Koopsom KADASTRALE ONROERENDE ZAAK.Koopjaar - Koopjaar';
comment on column pv_kad_onroerende_zaak.ks_meer_onroerendgoed                 is 'Groepsattribuut Koopsom KADASTRALE ONROERENDE ZAAK.Meer onroerendgoed - Meer onroerendgoed';
comment on column pv_kad_perceel.cu_aard_bebouwing                             is 'Groepsattribuut Cultuur onbebouwd KADASTRALE ONROERENDE ZAAK.Aard bebouwing - Aard bebouwing';
comment on column pv_kad_perceel.sc_kad_identif                                is '[PK] N15, FK naar kad_onrrnd_zk.kad_identif - Kadastrale identificatie';
comment on column pv_kad_perceel.aand_soort_grootte                            is 'boolean - Aanduiding soort grootte';
comment on column pv_kad_perceel.grootte_perceel                               is 'N8 - Grootte perceel';
comment on column pv_kad_perceel.omschr_deelperceel                            is 'AN1120 - Omschrijving deelperceel';
comment on column pv_kad_perceel.ka_kad_gemeentecode                           is 'Groepsattribuut Kadastrale aanduiding KADASTRAAL PERCEEL.Kadastrale gemeentecode - Kadastrale gemeentecode';
comment on column pv_kad_perceel.ka_perceelnummer                              is 'Groepsattribuut Kadastrale aanduiding KADASTRAAL PERCEEL.Perceelnummer - Perceelnummer';
comment on column pv_kad_perceel.ka_sectie                                     is 'Groepsattribuut Kadastrale aanduiding KADASTRAAL PERCEEL.Sectie - Sectie';
comment on column pv_kad_perceel.begrenzing_perceel                            is 'GM_Surface - Begrenzing perceel';
comment on column pv_kad_perceel.plaatscoordinaten_perceel                     is 'GM_Point - Plaatscoördinaten perceel';
comment on column pv_kad_perceel.cu_aard_cultuur_onbebouwd                     is 'Groepsattribuut Cultuur onbebouwd KADASTRALE ONROERENDE ZAAK.Aard cultuur onbebouwd - Aard cultuur onbebouwd';
comment on column pv_kad_perceel.dat_beg_geldh                                 is '';
comment on column pv_kad_perceel.datum_einde_geldh                             is 'OnvolledigeDatum - Datum einde geldigheid kadastrale onroerende zaak';
comment on column pv_kad_perceel.kad_identif                                   is '[PK] N15 - Kadastrale identificatie';
comment on column pv_kad_perceel.ks_bedrag                                     is 'Groepsattribuut Koopsom KADASTRALE ONROERENDE ZAAK.Bedrag - Bedrag';
comment on column pv_kad_perceel.ks_koopjaar                                   is 'Groepsattribuut Koopsom KADASTRALE ONROERENDE ZAAK.Koopjaar - Koopjaar';
comment on column pv_kad_perceel.ks_meer_onroerendgoed                         is 'Groepsattribuut Koopsom KADASTRALE ONROERENDE ZAAK.Meer onroerendgoed - Meer onroerendgoed';
comment on column pv_ligplaats.sc_identif                                      is '[PK] AN16, FK naar benoemd_terrein.sc_identif - Benoemd object identificatie';
comment on column pv_ligplaats.indic_geconst                                   is 'AN1 - Indicatie geconstateerde ligplaats';
comment on column pv_ligplaats.status                                          is 'AN80 - Ligplaatsstatus';
comment on column pv_ligplaats.fk_4nra_sc_identif                              is '[FK] AN16, FK naar nummeraand.sc_identif (is FK naar superclass ADRESSEERBAAR OBJECT AANDUIDING): "heeft als hoofdadres"';
comment on column pv_ligplaats.dat_beg_geldh                                   is '';
comment on column pv_ligplaats.clazz                                           is 'Aanduiding subclass';
comment on column pv_ligplaats.datum_einde_geldh                               is 'OnvolledigeDatum - Datum einde geldigheid benoemd terrein';
comment on column pv_ligplaats.bt_geom                                         is 'GM_Surface - Benoemd terrein geometrie';
comment on column pv_ligplaats_nummeraand.fk_nn_lh_lpl_sc_identif              is '[FK] AN16, FK naar ligplaats.sc_identif (is FK naar superclass BENOEMD OBJECT)';
comment on column pv_ligplaats_nummeraand.fk_nn_lh_lpl_sc_dat_beg_geldh        is '';
comment on column pv_ligplaats_nummeraand.fk_nn_rh_nra_sc_identif              is '[FK] AN16, FK naar nummeraand.sc_identif (is FK naar superclass ADRESSEERBAAR OBJECT AANDUIDING)';
comment on column pv_natuurlijk_persoon.sc_identif                             is '[PK] AN32, FK naar prs.sc_identif - Identificatie';
comment on column pv_natuurlijk_persoon.clazz                                  is 'Aanduiding subclass';
comment on column pv_natuurlijk_persoon.aand_naamgebruik                       is 'AN1 - Aanduiding naamgebruik';
comment on column pv_natuurlijk_persoon.geslachtsaand                          is 'AN1 - Geslachtsaanduiding';
comment on column pv_natuurlijk_persoon.nm_adellijke_titel_predikaat           is 'Groepsattribuut Naam NATUURLIJK PERSOON.Adellijke titel/ predikaat - Adellijke titel/ predikaat';
comment on column pv_natuurlijk_persoon.nm_geslachtsnaam                       is 'Groepsattribuut Naam NATUURLIJK PERSOON.Geslachtsnaam - Geslachtsnaam';
comment on column pv_natuurlijk_persoon.nm_voornamen                           is 'Groepsattribuut Naam NATUURLIJK PERSOON.Voornamen - Voornamen';
comment on column pv_natuurlijk_persoon.nm_voorvoegsel_geslachtsnaam           is 'Groepsattribuut Naam NATUURLIJK PERSOON.Voorvoegsel geslachtsnaam - Voorvoegsel geslachtsnaam';
comment on column pv_natuurlijk_persoon.na_aanhef_aanschrijving                is 'Groepsattribuut Naam aanschrijving NATUURLIJK PERSOON.Aanhef aanschrijving - Aanhef aanschrijving';
comment on column pv_natuurlijk_persoon.na_geslachtsnaam_aanschrijving         is 'Groepsattribuut Naam aanschrijving NATUURLIJK PERSOON.Geslachtsnaam aanschrijving - Geslachtsnaam aanschrijving';
comment on column pv_natuurlijk_persoon.na_voorletters_aanschrijving           is 'Groepsattribuut Naam aanschrijving NATUURLIJK PERSOON.Voorletters aanschrijving - Voorletters aanschrijving';
comment on column pv_natuurlijk_persoon.na_voornamen_aanschrijving             is 'Groepsattribuut Naam aanschrijving NATUURLIJK PERSOON.Voornamen aanschrijving - Voornamen aanschrijving';
comment on column pv_natuurlijk_persoon.fk_2acd_code                           is '[FK] AN3, FK naar academische_titel.code: "Referentielijst NATUURLIJK PERSOON.Academische titel"';
comment on column pv_natuurlijk_persoon.fax_nummer                             is 'AN20 - Fax-nummer';
comment on column pv_natuurlijk_persoon.identif                                is '[PK] AN32 - Identificatie';
comment on column pv_natuurlijk_persoon.kvk_nummer                             is 'N8 - KvK-nummer';
comment on column pv_natuurlijk_persoon.naam                                   is 'AN500 - Naam';
comment on column pv_natuurlijk_persoon.telefoonnummer                         is 'AN20 - Telefoonnummer';
comment on column pv_niet_ingezetene.sc_identif                                is '[PK] AN32, FK naar ingeschr_nat_prs.sc_identif - Identificatie';
comment on column pv_niet_natuurlijk_persoon.sc_identif                        is '[PK] AN32, FK naar prs.sc_identif - Identificatie';
comment on column pv_niet_natuurlijk_persoon.clazz                             is 'Aanduiding subclass';
comment on column pv_niet_natuurlijk_persoon.nnp_naam                          is 'AN500 - (Statutaire) Naam';
comment on column pv_niet_natuurlijk_persoon.kvk_nummer                        is 'N8 - KvK-nummer';
comment on column pv_niet_natuurlijk_persoon.su_naam                           is 'AN500 - Naam';
comment on column pv_niet_natuurlijk_persoon.telefoonnummer                    is 'AN20 - Telefoonnummer';
comment on column pv_niet_natuurlijk_persoon.typering                          is 'AN50 - Subjecttypering';
comment on column pv_niet_natuurlijk_persoon.rechtsvorm                        is 'AN50 - Rechtsvorm';
comment on column pv_niet_natuurlijk_persoon.statutaire_zetel                  is 'AN40 - Statutaire zetel';
comment on column pv_pand.dat_beg_geldh                                        is '';
comment on column pv_pand.identif                                              is '[PK] AN16 - Pandidentificatie';
comment on column pv_pand.datum_einde_geldh                                    is 'OnvolledigeDatum - Datum einde geldigheid pand';
comment on column pv_pand.indic_geconstateerd                                  is 'AN1 - Indicatie geconstateerd pand';
comment on column pv_pand.oorspronkelijk_bouwjaar                              is 'N4 - Oorspronkelijk bouwjaar pand';
comment on column pv_pand.status                                               is 'AN80 - Pandstatus';
comment on column pv_pand.geom_bovenaanzicht                                   is 'GM_Surface - Pandgeometrie bovenaanzicht';
comment on column pv_persoon.sc_identif                                        is '[PK] AN32, FK naar subject.identif - Identificatie';
comment on column pv_persoon.clazz                                             is 'Aanduiding subclass';
comment on column pv_standplaats.sc_identif                                    is '[PK] AN16, FK naar benoemd_terrein.sc_identif - Benoemd object identificatie';
comment on column pv_standplaats.indic_geconst                                 is 'AN1 - Indicatie geconstateerde standplaats';
comment on column pv_standplaats.status                                        is 'AN80 - Standplaatsstatus';
comment on column pv_standplaats.fk_4nra_sc_identif                            is '[FK] AN16, FK naar nummeraand.sc_identif (is FK naar superclass ADRESSEERBAAR OBJECT AANDUIDING): "heeft als hoofdadres"';
comment on column pv_standplaats.dat_beg_geldh                                 is '';
comment on column pv_standplaats.clazz                                         is 'Aanduiding subclass';
comment on column pv_standplaats.datum_einde_geldh                             is 'OnvolledigeDatum - Datum einde geldigheid benoemd terrein';
comment on column pv_standplaats.bt_geom                                       is 'GM_Surface - Benoemd terrein geometrie';
comment on column pv_standplaats_nummeraand.fk_nn_lh_spl_sc_identif            is '[FK] AN16, FK naar standplaats.sc_identif (is FK naar superclass BENOEMD OBJECT)';
comment on column pv_standplaats_nummeraand.fk_nn_lh_spl_sc_dat_beg_geldh      is '';
comment on column pv_standplaats_nummeraand.fk_nn_rh_nra_sc_identif            is '[FK] AN16, FK naar nummeraand.sc_identif (is FK naar superclass ADRESSEERBAAR OBJECT AANDUIDING)';
comment on column pv_verblijfsobj_nummeraand.fk_nn_lh_vbo_sc_identif           is '[FK] AN16, FK naar verblijfsobj.sc_identif (is FK naar superclass BENOEMD OBJECT)';
comment on column pv_verblijfsobj_nummeraand.fk_nn_lh_vbo_sc_dat_beg_geldh     is '';
comment on column pv_verblijfsobj_nummeraand.fk_nn_rh_nra_sc_identif           is '[FK] AN16, FK naar nummeraand.sc_identif (is FK naar superclass ADRESSEERBAAR OBJECT AANDUIDING)';
comment on column pv_verblijfsobj_pand.fk_nn_lh_vbo_sc_identif                 is '[FK] AN16, FK naar verblijfsobj.sc_identif (is FK naar superclass BENOEMD OBJECT)';
comment on column pv_verblijfsobj_pand.fk_nn_lh_vbo_sc_dat_beg_geldh           is '';
comment on column pv_verblijfsobj_pand.fk_nn_rh_pnd_identif                    is '[FK] AN16, FK naar pand.identif';
comment on column pv_verblijfsobject.sc_identif                                is '[PK] AN16, FK naar gebouwd_obj.sc_identif - Benoemd object identificatie';
comment on column pv_verblijfsobject.fk_11nra_sc_identif                       is '[FK] AN16, FK naar nummeraand.sc_identif (is FK naar superclass ADRESSEERBAAR OBJECT AANDUIDING): "heeft als hoofdadres"';
comment on column pv_verblijfsobject.indic_geconstateerd                       is 'AN1 - Indicatie geconstateerd verblijfsobject';
comment on column pv_verblijfsobject.status                                    is 'AN80 - Verblijfsobjectstatus';
comment on column pv_verblijfsobject.dat_beg_geldh                             is '';
comment on column pv_verblijfsobject.clazz                                     is 'Aanduiding subclass';
comment on column pv_verblijfsobject.datum_einde_geldh                         is 'OnvolledigeDatum - Datum einde geldigheid gebouwd object';
comment on column pv_verblijfsobject.oppervlakte_obj                           is 'N6 - Oppervlakte (verblijfs)object';
comment on column pv_verblijfsobject.puntgeom                                  is 'GM_Point - Gebouwd objectpuntgeometrie';
comment on column pv_woonplaats.dat_beg_geldh                                  is '';
comment on column pv_woonplaats.identif                                        is '[PK] AN4 - Woonplaatsidentificatie';
comment on column pv_woonplaats.datum_einde_geldh                              is 'OnvolledigeDatum - Datum einde geldigheid woonplaats';
comment on column pv_woonplaats.naam                                           is 'AN80 - Woonplaatsnaam';
comment on column pv_woonplaats.status                                         is 'AN80 - Woonplaatsstatus';
comment on column pv_woonplaats.fk_7gem_code                                   is '[FK] N4, FK naar gemeente.code: "ligt in"';
comment on column pv_woonplaats.gem_dat_beg_geldh                              is '';
comment on column pv_woonplaats.gem_code                                       is '[PK] N4 - Gemeentecode';
comment on column pv_woonplaats.gem_datum_einde_geldh                          is 'OnvolledigeDatum - Datum einde geldigheid gemeente';
comment on column pv_woonplaats.gem_naam                                       is 'AN40 - Gemeentenaam';
comment on column pv_zakelijk_recht.kadaster_identif                           is '[PK]  - Kadaster identificatie zakelijk recht';
comment on column pv_zakelijk_recht.eindd_recht                                is '[geen RSGB type] - Einddatum recht';
comment on column pv_zakelijk_recht.indic_betrokken_in_splitsing               is '[geen RSGB type] - Indicatie betrokken in splitsing';
comment on column pv_zakelijk_recht.ingangsdatum_recht                         is 'OnvolledigeDatum - Ingangsdatum recht';
comment on column pv_zakelijk_recht.fk_7koz_kad_identif                        is '[FK] N15, FK naar kad_onrrnd_zk.kad_identif: "betreft"';
comment on column pv_zakelijk_recht.fk_8pes_sc_identif                         is '[FK] AN32, FK naar prs.sc_identif (is FK naar superclass SUBJECT): "heeft als gerechtigde"';
comment on column pv_zakelijk_recht.ar_noemer                                  is 'Groepsattribuut Aandeel in recht ZAKELIJK RECHT.Noemer - Noemer';
comment on column pv_zakelijk_recht.ar_teller                                  is 'Groepsattribuut Aandeel in recht ZAKELIJK RECHT.Teller - Teller';
comment on column pv_zakelijk_recht.fk_2aard_recht_verkort_aand                is '[FK] AN4, FK naar aard_recht_verkort.aand: "Referentielijst ZAKELIJK RECHT.Aanduiding aard recht verkort"';
comment on column pv_zakelijk_recht.arv_omschr                                 is 'Referentielijst property AARD RECHT VERKORT.Omschrijving aard recht verkort - Omschrijving aard recht verkort';
comment on column pv_zakelijk_recht.fk_3avr_aand                               is '[FK] AN6, FK naar aard_verkregen_recht.aand: "Referentielijst ZAKELIJK RECHT.Aanduiding aard verkregen recht"';
comment on column pv_zakelijk_recht_aantekening. kadaster_identif_aantek_recht is '[PK]  - Kadaster identificatie aantekening recht';
comment on column pv_zakelijk_recht_aantekening. aard_aantek_recht             is '[geen RSGB type] - Aard aantekening recht';
comment on column pv_zakelijk_recht_aantekening. begindatum_aantek_recht       is 'OnvolledigeDatum - Begindatum aantekening recht';
comment on column pv_zakelijk_recht_aantekening. beschrijving_aantek_recht     is '[geen RSGB type] - Beschrijving aantekening recht';
comment on column pv_zakelijk_recht_aantekening. eindd_aantek_recht            is '[geen RSGB type] - Einddatum aantekening recht';
comment on column pv_zakelijk_recht_aantekening. fk_5zkr_kadaster_identif      is '[FK] , FK naar zak_recht.kadaster_identif: "behoort bij"';
comment on column pm_adr_object_nummeraand.identif                             is '[PK] AN16 - Identificatie adresseerbaar object aanduiding';
comment on column pm_adr_object_nummeraand.dat_beg_geldh                       is '';
comment on column pm_adr_object_nummeraand.dat_eind_geldh                      is 'OnvolledigeDatum - Datum einde geldigheid addresserbaar object aanduiding';
comment on column pm_adr_object_nummeraand.huinummer                           is 'N5 - Huisnummer';
comment on column pm_adr_object_nummeraand.huinummertoevoeging                 is 'AN4 - Huisnummertoevoeging';
comment on column pm_adr_object_nummeraand.huisletter                          is 'AN1 - Huisletter';
comment on column pm_adr_object_nummeraand.postcode                            is 'AN6 - Postcode';
comment on column pm_adr_object_nummeraand.naam_openb_rmte                     is 'AN80 - Naam openbare ruimte';
comment on column pm_adr_object_nummeraand.gem_code                            is ' [PK] N4 - Gemeentecode';
comment on column pm_adr_object_nummeraand.gem_naam                            is 'AN40 - Gemeentenaam';
comment on column pm_adr_object_nummeraand.wpl_naam                            is 'AN80 - Woonplaatsnaam';
comment on column pm_adr_object_nummeraand.indic_hoofdadres                    is 'boolean - Indicatie hoofdadres';
comment on column pm_adr_object_nummeraand.status                              is 'AN80 - Nummeraanduidingstatus';
comment on column pm_ander_natuurlijk_persoon.sc_identif                       is '[PK] AN32, FK naar nat_prs.sc_identif - Identificatie';
comment on column pm_ander_natuurlijk_persoon.geboortedatum                    is 'N8 - Geboortedatum';
comment on column pm_ander_natuurlijk_persoon.overlijdensdatum                 is 'N8 - Overlijdensdatum';
comment on column pm_appartementsrecht.ka_appartementsindex                    is 'Groepsattribuut Kadastrale aanduiding APPARTEMENTSRECHT.Appartementsindex - Appartementsindex';
comment on column pm_appartementsrecht.ka_kad_gemeentecode                     is 'Groepsattribuut Kadastrale aanduiding APPARTEMENTSRECHT.Kadastrale gemeentecode - Kadastrale gemeentecode';
comment on column pm_appartementsrecht.ka_perceelnummer                        is 'Groepsattribuut Kadastrale aanduiding APPARTEMENTSRECHT.Perceelnummer - Perceelnummer';
comment on column pm_appartementsrecht.ka_sectie                               is 'Groepsattribuut Kadastrale aanduiding APPARTEMENTSRECHT.Sectie - Sectie';
comment on column pm_appartementsrecht.sc_kad_identif                          is '[PK] N15, FK naar kad_onrrnd_zk.kad_identif - Kadastrale identificatie';
comment on column pm_benoemd_obj_kad_onr_zk.fk_nn_lh_tgo_identif               is '[FK] AN16, FK naar benoemd_obj.identif';
comment on column pm_benoemd_obj_kad_onr_zk.fk_nn_rh_koz_kad_identif           is '[FK] N15, FK naar kad_onrrnd_zk.kad_identif';
comment on column pm_benoemd_object.identif                                    is '[PK] AN16 - Benoemd object identificatie';
comment on column pm_benoemd_object.clazz                                      is 'Aanduiding subclass';
comment on column pm_benoemd_terrein.dat_beg_geldh                             is '';
comment on column pm_benoemd_terrein.sc_identif                                is '[PK] AN16, FK naar benoemd_obj.identif - Benoemd object identificatie';
comment on column pm_benoemd_terrein.clazz                                     is 'Aanduiding subclass';
comment on column pm_benoemd_terrein.datum_einde_geldh                         is 'OnvolledigeDatum - Datum einde geldigheid benoemd terrein';
comment on column pm_benoemd_terrein.bt_geom                                   is 'GM_Surface - Benoemd terrein geometrie';
comment on column pm_gebouwd_obj_gebruiksdoel.gebruiksdoel_gebouwd_obj         is 'AN80 - Gebruiksdoel gebouwd object';
comment on column pm_gebouwd_obj_gebruiksdoel.fk_gbo_sc_identif                is '[FK] AN16, FK naar gebouwd_obj.sc_identif (is FK naar superclass BENOEMD OBJECT)';
comment on column pm_gebouwd_object.dat_beg_geldh                              is '';
comment on column pm_gebouwd_object.sc_identif                                 is '[PK] AN16, FK naar benoemd_obj.identif - Benoemd object identificatie';
comment on column pm_gebouwd_object.clazz                                      is 'Aanduiding subclass';
comment on column pm_gebouwd_object.datum_einde_geldh                          is 'OnvolledigeDatum - Datum einde geldigheid gebouwd object';
comment on column pm_gebouwd_object.oppervlakte_obj                            is 'N6 - Oppervlakte (verblijfs)object';
comment on column pm_gebouwd_object.vlakgeom                                   is 'GM_Surface - Gebouwd object vlakgeometrie';
comment on column pm_gebouwd_object.puntgeom                                   is 'GM_Point - Gebouwd objectpuntgeometrie ';
comment on column pm_gemeente.dat_beg_geldh                                    is '';
comment on column pm_gemeente.code                                             is '[PK] N4 - Gemeentecode';
comment on column pm_gemeente.datum_einde_geldh                                is 'OnvolledigeDatum - Datum einde geldigheid gemeente';
comment on column pm_gemeente.naam                                             is 'AN40 - Gemeentenaam';
comment on column pm_gemeente.geom                                             is 'GM_Surface - Gemeentegeometrie';
comment on column pm_ingeschr_natuurlijk_persoon.sc_identif                    is '[PK] AN32, FK naar nat_prs.sc_identif - Identificatie';
comment on column pm_ingeschr_natuurlijk_persoon.gb_geboortedatum              is 'Groepsattribuut Geboorte INGESCHREVEN NATUURLIJK PERSOON.Geboortedatum - Geboortedatum';
comment on column pm_ingeschr_natuurlijk_persoon.gb_geboorteplaats             is 'Groepsattribuut Geboorte INGESCHREVEN NATUURLIJK PERSOON.Geboorteplaats - Geboorteplaats';
comment on column pm_ingeschr_natuurlijk_persoon.ol_overlijdensdatum           is 'Groepsattribuut Overlijden INGESCHREVEN NATUURLIJK PERSOON.Overlijdensdatum - Overlijdensdatum';
comment on column pm_ingeschr_natuurlijk_persoon.ol_overlijdensplaats          is 'Groepsattribuut Overlijden INGESCHREVEN NATUURLIJK PERSOON.Overlijdensplaats - Overlijdensplaats';
comment on column pm_ingeschr_natuurlijk_persoon.va_loc_beschrijving           is 'Groepsattribuut Verblijfadres INGESCHREVEN NATUURLIJK PERSOON.Locatie beschrijving - Locatie beschrijving';
comment on column pm_kad_onr_zk_aantek.begindatum_aantek_kad_obj               is '';
comment on column pm_kad_onr_zk_aantek.kadaster_identif_aantek                 is '[PK] AN255 - Kadaster identificatie aantekening';
comment on column pm_kad_onr_zk_aantek.aard_aantek_kad_obj                     is '[Enumeratie] - Aard aantekening kadastraal object';
comment on column pm_kad_onr_zk_aantek.beschrijving_aantek_kad_obj             is 'AN124 - Beschrijving aantekening kadastraal object';
comment on column pm_kad_onr_zk_aantek.eindd_aantek_kad_obj                    is 'OnvolledigeDatum - Einddatum aantekening kadastraal object';
comment on column pm_kad_onr_zk_aantek.fk_4koz_kad_identif                     is '[FK] N15, FK naar kad_onrrnd_zk.kad_identif: "behoort bij"';
comment on column pm_kad_onr_zk_his_rel.fk_sc_lh_koz_kad_identif               is '[FK] N15, FK naar kad_onrrnd_zk.kad_identif';
comment on column pm_kad_onr_zk_his_rel.fk_sc_rh_koz_kad_identif               is '[FK] N15, FK naar kad_onrrnd_zk.kad_identif';
comment on column pm_kad_onr_zk_his_rel.aard                                   is ' - Aard';
comment on column pm_kad_onr_zk_his_rel.overgangsgrootte                       is ' - Overgangsgrootte';
comment on column pm_kad_onroerende_zaak.cu_aard_cultuur_onbebouwd             is 'Groepsattribuut Cultuur onbebouwd KADASTRALE ONROERENDE ZAAK.Aard cultuur onbebouwd - Aard cultuur onbebouwd';
comment on column pm_kad_onroerende_zaak.dat_beg_geldh                         is '';
comment on column pm_kad_onroerende_zaak.datum_einde_geldh                     is 'OnvolledigeDatum - Datum einde geldigheid kadastrale onroerende zaak';
comment on column pm_kad_onroerende_zaak.kad_identif                           is '[PK] N15 - Kadastrale identificatie';
comment on column pm_kad_onroerende_zaak.ks_bedrag                             is 'Groepsattribuut Koopsom KADASTRALE ONROERENDE ZAAK.Bedrag - Bedrag';
comment on column pm_kad_onroerende_zaak.ks_koopjaar                           is 'Groepsattribuut Koopsom KADASTRALE ONROERENDE ZAAK.Koopjaar - Koopjaar';
comment on column pm_kad_onroerende_zaak.ks_meer_onroerendgoed                 is 'Groepsattribuut Koopsom KADASTRALE ONROERENDE ZAAK.Meer onroerendgoed - Meer onroerendgoed';
comment on column pm_kad_perceel.cu_aard_bebouwing                             is 'Groepsattribuut Cultuur onbebouwd KADASTRALE ONROERENDE ZAAK.Aard bebouwing - Aard bebouwing';
comment on column pm_kad_perceel.sc_kad_identif                                is '[PK] N15, FK naar kad_onrrnd_zk.kad_identif - Kadastrale identificatie';
comment on column pm_kad_perceel.aand_soort_grootte                            is 'boolean - Aanduiding soort grootte';
comment on column pm_kad_perceel.grootte_perceel                               is 'N8 - Grootte perceel';
comment on column pm_kad_perceel.omschr_deelperceel                            is 'AN1120 - Omschrijving deelperceel';
comment on column pm_kad_perceel.ka_kad_gemeentecode                           is 'Groepsattribuut Kadastrale aanduiding KADASTRAAL PERCEEL.Kadastrale gemeentecode - Kadastrale gemeentecode';
comment on column pm_kad_perceel.ka_perceelnummer                              is 'Groepsattribuut Kadastrale aanduiding KADASTRAAL PERCEEL.Perceelnummer - Perceelnummer';
comment on column pm_kad_perceel.ka_sectie                                     is 'Groepsattribuut Kadastrale aanduiding KADASTRAAL PERCEEL.Sectie - Sectie';
comment on column pm_kad_perceel.begrenzing_perceel                            is 'GM_Surface - Begrenzing perceel';
comment on column pm_kad_perceel.plaatscoordinaten_perceel                     is 'GM_Point - Plaatscoördinaten perceel';
comment on column pm_kad_perceel.cu_aard_cultuur_onbebouwd                     is 'Groepsattribuut Cultuur onbebouwd KADASTRALE ONROERENDE ZAAK.Aard cultuur onbebouwd - Aard cultuur onbebouwd';
comment on column pm_kad_perceel.dat_beg_geldh                                 is '';
comment on column pm_kad_perceel.datum_einde_geldh                             is 'OnvolledigeDatum - Datum einde geldigheid kadastrale onroerende zaak';
comment on column pm_kad_perceel.kad_identif                                   is '[PK] N15 - Kadastrale identificatie';
comment on column pm_kad_perceel.ks_bedrag                                     is 'Groepsattribuut Koopsom KADASTRALE ONROERENDE ZAAK.Bedrag - Bedrag';
comment on column pm_kad_perceel.ks_koopjaar                                   is 'Groepsattribuut Koopsom KADASTRALE ONROERENDE ZAAK.Koopjaar - Koopjaar';
comment on column pm_kad_perceel.ks_meer_onroerendgoed                         is 'Groepsattribuut Koopsom KADASTRALE ONROERENDE ZAAK.Meer onroerendgoed - Meer onroerendgoed';
comment on column pm_ligplaats.sc_identif                                      is '[PK] AN16, FK naar benoemd_terrein.sc_identif - Benoemd object identificatie';
comment on column pm_ligplaats.indic_geconst                                   is 'AN1 - Indicatie geconstateerde ligplaats';
comment on column pm_ligplaats.status                                          is 'AN80 - Ligplaatsstatus';
comment on column pm_ligplaats.fk_4nra_sc_identif                              is '[FK] AN16, FK naar nummeraand.sc_identif (is FK naar superclass ADRESSEERBAAR OBJECT AANDUIDING): "heeft als hoofdadres"';
comment on column pm_ligplaats.dat_beg_geldh                                   is '';
comment on column pm_ligplaats.clazz                                           is 'Aanduiding subclass';
comment on column pm_ligplaats.datum_einde_geldh                               is 'OnvolledigeDatum - Datum einde geldigheid benoemd terrein';
comment on column pm_ligplaats.bt_geom                                         is 'GM_Surface - Benoemd terrein geometrie';
comment on column pm_ligplaats_nummeraand.fk_nn_lh_lpl_sc_identif              is '[FK] AN16, FK naar ligplaats.sc_identif (is FK naar superclass BENOEMD OBJECT)';
comment on column pm_ligplaats_nummeraand.fk_nn_lh_lpl_sc_dat_beg_geldh        is '';
comment on column pm_ligplaats_nummeraand.fk_nn_rh_nra_sc_identif              is '[FK] AN16, FK naar nummeraand.sc_identif (is FK naar superclass ADRESSEERBAAR OBJECT AANDUIDING)';
comment on column pm_natuurlijk_persoon.sc_identif                             is '[PK] AN32, FK naar prs.sc_identif - Identificatie';
comment on column pm_natuurlijk_persoon.clazz                                  is 'Aanduiding subclass';
comment on column pm_natuurlijk_persoon.aand_naamgebruik                       is 'AN1 - Aanduiding naamgebruik';
comment on column pm_natuurlijk_persoon.geslachtsaand                          is 'AN1 - Geslachtsaanduiding';
comment on column pm_natuurlijk_persoon.nm_adellijke_titel_predikaat           is 'Groepsattribuut Naam NATUURLIJK PERSOON.Adellijke titel/ predikaat - Adellijke titel/ predikaat';
comment on column pm_natuurlijk_persoon.nm_geslachtsnaam                       is 'Groepsattribuut Naam NATUURLIJK PERSOON.Geslachtsnaam - Geslachtsnaam';
comment on column pm_natuurlijk_persoon.nm_voornamen                           is 'Groepsattribuut Naam NATUURLIJK PERSOON.Voornamen - Voornamen';
comment on column pm_natuurlijk_persoon.nm_voorvoegsel_geslachtsnaam           is 'Groepsattribuut Naam NATUURLIJK PERSOON.Voorvoegsel geslachtsnaam - Voorvoegsel geslachtsnaam';
comment on column pm_natuurlijk_persoon.na_aanhef_aanschrijving                is 'Groepsattribuut Naam aanschrijving NATUURLIJK PERSOON.Aanhef aanschrijving - Aanhef aanschrijving';
comment on column pm_natuurlijk_persoon.na_geslachtsnaam_aanschrijving         is 'Groepsattribuut Naam aanschrijving NATUURLIJK PERSOON.Geslachtsnaam aanschrijving - Geslachtsnaam aanschrijving';
comment on column pm_natuurlijk_persoon.na_voorletters_aanschrijving           is 'Groepsattribuut Naam aanschrijving NATUURLIJK PERSOON.Voorletters aanschrijving - Voorletters aanschrijving';
comment on column pm_natuurlijk_persoon.na_voornamen_aanschrijving             is 'Groepsattribuut Naam aanschrijving NATUURLIJK PERSOON.Voornamen aanschrijving - Voornamen aanschrijving';
comment on column pm_natuurlijk_persoon.fk_2acd_code                           is '[FK] AN3, FK naar academische_titel.code: "Referentielijst NATUURLIJK PERSOON.Academische titel"';
comment on column pm_natuurlijk_persoon.fax_nummer                             is 'AN20 - Fax-nummer';
comment on column pm_natuurlijk_persoon.identif                                is '[PK] AN32 - Identificatie';
comment on column pm_natuurlijk_persoon.kvk_nummer                             is 'N8 - KvK-nummer';
comment on column pm_natuurlijk_persoon.naam                                   is 'AN500 - Naam';
comment on column pm_natuurlijk_persoon.telefoonnummer                         is 'AN20 - Telefoonnummer';
comment on column pm_niet_ingezetene.sc_identif                                is '[PK] AN32, FK naar ingeschr_nat_prs.sc_identif - Identificatie';
comment on column pm_niet_natuurlijk_persoon.sc_identif                        is '[PK] AN32, FK naar prs.sc_identif - Identificatie';
comment on column pm_niet_natuurlijk_persoon.clazz                             is 'Aanduiding subclass';
comment on column pm_niet_natuurlijk_persoon.nnp_naam                          is 'AN500 - (Statutaire) Naam';
comment on column pm_niet_natuurlijk_persoon.kvk_nummer                        is 'N8 - KvK-nummer';
comment on column pm_niet_natuurlijk_persoon.su_naam                           is 'AN500 - Naam';
comment on column pm_niet_natuurlijk_persoon.telefoonnummer                    is 'AN20 - Telefoonnummer';
comment on column pm_niet_natuurlijk_persoon.typering                          is 'AN50 - Subjecttypering';
comment on column pm_niet_natuurlijk_persoon.rechtsvorm                        is 'AN50 - Rechtsvorm';
comment on column pm_niet_natuurlijk_persoon.statutaire_zetel                  is 'AN40 - Statutaire zetel';
comment on column pm_pand.dat_beg_geldh                                        is '';
comment on column pm_pand.identif                                              is '[PK] AN16 - Pandidentificatie';
comment on column pm_pand.datum_einde_geldh                                    is 'OnvolledigeDatum - Datum einde geldigheid pand';
comment on column pm_pand.indic_geconstateerd                                  is 'AN1 - Indicatie geconstateerd pand';
comment on column pm_pand.oorspronkelijk_bouwjaar                              is 'N4 - Oorspronkelijk bouwjaar pand';
comment on column pm_pand.status                                               is 'AN80 - Pandstatus';
comment on column pm_pand.geom_bovenaanzicht                                   is 'GM_Surface - Pandgeometrie bovenaanzicht';
comment on column pm_persoon.sc_identif                                        is '[PK] AN32, FK naar subject.identif - Identificatie';
comment on column pm_persoon.clazz                                             is 'Aanduiding subclass';
comment on column pm_standplaats.sc_identif                                    is '[PK] AN16, FK naar benoemd_terrein.sc_identif - Benoemd object identificatie';
comment on column pm_standplaats.indic_geconst                                 is 'AN1 - Indicatie geconstateerde standplaats';
comment on column pm_standplaats.status                                        is 'AN80 - Standplaatsstatus';
comment on column pm_standplaats.fk_4nra_sc_identif                            is '[FK] AN16, FK naar nummeraand.sc_identif (is FK naar superclass ADRESSEERBAAR OBJECT AANDUIDING): "heeft als hoofdadres"';
comment on column pm_standplaats.dat_beg_geldh                                 is '';
comment on column pm_standplaats.clazz                                         is 'Aanduiding subclass';
comment on column pm_standplaats.datum_einde_geldh                             is 'OnvolledigeDatum - Datum einde geldigheid benoemd terrein';
comment on column pm_standplaats.bt_geom                                       is 'GM_Surface - Benoemd terrein geometrie';
comment on column pm_standplaats_nummeraand.fk_nn_lh_spl_sc_identif            is '[FK] AN16, FK naar standplaats.sc_identif (is FK naar superclass BENOEMD OBJECT)';
comment on column pm_standplaats_nummeraand.fk_nn_lh_spl_sc_dat_beg_geldh      is '';
comment on column pm_standplaats_nummeraand.fk_nn_rh_nra_sc_identif            is '[FK] AN16, FK naar nummeraand.sc_identif (is FK naar superclass ADRESSEERBAAR OBJECT AANDUIDING)';
comment on column pm_verblijfsobj_nummeraand.fk_nn_lh_vbo_sc_identif           is '[FK] AN16, FK naar verblijfsobj.sc_identif (is FK naar superclass BENOEMD OBJECT)';
comment on column pm_verblijfsobj_nummeraand.fk_nn_lh_vbo_sc_dat_beg_geldh     is '';
comment on column pm_verblijfsobj_nummeraand.fk_nn_rh_nra_sc_identif           is '[FK] AN16, FK naar nummeraand.sc_identif (is FK naar superclass ADRESSEERBAAR OBJECT AANDUIDING)';
comment on column pm_verblijfsobj_pand.fk_nn_lh_vbo_sc_identif                 is '[FK] AN16, FK naar verblijfsobj.sc_identif (is FK naar superclass BENOEMD OBJECT)';
comment on column pm_verblijfsobj_pand.fk_nn_lh_vbo_sc_dat_beg_geldh           is '';
comment on column pm_verblijfsobj_pand.fk_nn_rh_pnd_identif                    is '[FK] AN16, FK naar pand.identif';
comment on column pm_verblijfsobject.sc_identif                                is '[PK] AN16, FK naar gebouwd_obj.sc_identif - Benoemd object identificatie';
comment on column pm_verblijfsobject.fk_11nra_sc_identif                       is '[FK] AN16, FK naar nummeraand.sc_identif (is FK naar superclass ADRESSEERBAAR OBJECT AANDUIDING): "heeft als hoofdadres"';
comment on column pm_verblijfsobject.indic_geconstateerd                       is 'AN1 - Indicatie geconstateerd verblijfsobject';
comment on column pm_verblijfsobject.status                                    is 'AN80 - Verblijfsobjectstatus';
comment on column pm_verblijfsobject.dat_beg_geldh                             is '';
comment on column pm_verblijfsobject.clazz                                     is 'Aanduiding subclass';
comment on column pm_verblijfsobject.datum_einde_geldh                         is 'OnvolledigeDatum - Datum einde geldigheid gebouwd object';
comment on column pm_verblijfsobject.oppervlakte_obj                           is 'N6 - Oppervlakte (verblijfs)object';
comment on column pm_verblijfsobject.puntgeom                                  is 'GM_Point - Gebouwd objectpuntgeometrie';
comment on column pm_woonplaats.dat_beg_geldh                                  is '';
comment on column pm_woonplaats.identif                                        is '[PK] AN4 - Woonplaatsidentificatie';
comment on column pm_woonplaats.datum_einde_geldh                              is 'OnvolledigeDatum - Datum einde geldigheid woonplaats';
comment on column pm_woonplaats.naam                                           is 'AN80 - Woonplaatsnaam';
comment on column pm_woonplaats.status                                         is 'AN80 - Woonplaatsstatus';
comment on column pm_woonplaats.fk_7gem_code                                   is '[FK] N4, FK naar gemeente.code: "ligt in"';
comment on column pm_woonplaats.gem_dat_beg_geldh                              is '';
comment on column pm_woonplaats.gem_code                                       is '[PK] N4 - Gemeentecode';
comment on column pm_woonplaats.gem_datum_einde_geldh                          is 'OnvolledigeDatum - Datum einde geldigheid gemeente';
comment on column pm_woonplaats.gem_naam                                       is 'AN40 - Gemeentenaam';
comment on column pm_zakelijk_recht.kadaster_identif                           is '[PK]  - Kadaster identificatie zakelijk recht';
comment on column pm_zakelijk_recht.eindd_recht                                is '[geen RSGB type] - Einddatum recht';
comment on column pm_zakelijk_recht.indic_betrokken_in_splitsing               is '[geen RSGB type] - Indicatie betrokken in splitsing';
comment on column pm_zakelijk_recht.ingangsdatum_recht                         is 'OnvolledigeDatum - Ingangsdatum recht';
comment on column pm_zakelijk_recht.fk_7koz_kad_identif                        is '[FK] N15, FK naar kad_onrrnd_zk.kad_identif: "betreft"';
comment on column pm_zakelijk_recht.fk_8pes_sc_identif                         is '[FK] AN32, FK naar prs.sc_identif (is FK naar superclass SUBJECT): "heeft als gerechtigde"';
comment on column pm_zakelijk_recht.ar_noemer                                  is 'Groepsattribuut Aandeel in recht ZAKELIJK RECHT.Noemer - Noemer';
comment on column pm_zakelijk_recht.ar_teller                                  is 'Groepsattribuut Aandeel in recht ZAKELIJK RECHT.Teller - Teller';
comment on column pm_zakelijk_recht.fk_2aard_recht_verkort_aand                is '[FK] AN4, FK naar aard_recht_verkort.aand: "Referentielijst ZAKELIJK RECHT.Aanduiding aard recht verkort"';
comment on column pm_zakelijk_recht.arv_omschr                                 is 'Referentielijst property AARD RECHT VERKORT.Omschrijving aard recht verkort - Omschrijving aard recht verkort';
comment on column pm_zakelijk_recht.fk_3avr_aand                               is '[FK] AN6, FK naar aard_verkregen_recht.aand: "Referentielijst ZAKELIJK RECHT.Aanduiding aard verkregen recht"';
comment on column pm_zakelijk_recht_aantekening. kadaster_identif_aantek_recht is '[PK]  - Kadaster identificatie aantekening recht';
comment on column pm_zakelijk_recht_aantekening. aard_aantek_recht             is '[geen RSGB type] - Aard aantekening recht';
comment on column pm_zakelijk_recht_aantekening. begindatum_aantek_recht       is 'OnvolledigeDatum - Begindatum aantekening recht';
comment on column pm_zakelijk_recht_aantekening. beschrijving_aantek_recht     is '[geen RSGB type] - Beschrijving aantekening recht';
comment on column pm_zakelijk_recht_aantekening. eindd_aantek_recht            is '[geen RSGB type] - Einddatum aantekening recht';
comment on column pm_zakelijk_recht_aantekening. fk_5zkr_kadaster_identif      is '[FK] , FK naar zak_recht.kadaster_identif: "behoort bij"';
comment on column pv_info_i_koz_adres.bob_identif                              is '[FK] AN16, FK naar benoemd_obj.identif';
comment on column pv_info_i_koz_adres.koz_identif                              is '[FK] N15, FK naar kad_onrrnd_zk.kad_identif';
comment on column pv_info_i_koz_adres.aon_identif                              is '[PK] AN16 - Identificatie adresseerbaar object aanduiding';
comment on column pv_info_i_koz_adres.dat_beg_geldh                            is '';
comment on column pv_info_i_koz_adres.dat_eind_geldh                           is 'OnvolledigeDatum - Datum einde geldigheid addresserbaar object aanduiding';
comment on column pv_info_i_koz_adres.huinummer                                is 'N5 - Huisnummer';
comment on column pv_info_i_koz_adres.huinummertoevoeging                      is 'AN4 - Huisnummertoevoeging';
comment on column pv_info_i_koz_adres.huisletter                               is 'AN1 - Huisletter';
comment on column pv_info_i_koz_adres.postcode                                 is 'AN6 - Postcode';
comment on column pv_info_i_koz_adres.naam_openb_rmte                          is 'AN80 - Naam openbare ruimte';
comment on column pv_info_i_koz_adres.gem_code                                 is '[PK] N4 - Gemeentecode';
comment on column pv_info_i_koz_adres.gem_naam                                 is 'AN40 - Gemeentenaam';
comment on column pv_info_i_koz_adres.wpl_naam                                 is 'AN80 - Woonplaatsnaam';
comment on column pv_info_i_koz_adres.status                                   is 'AN80 - Nummeraanduidingstatus';
comment on column pv_info_i_koz_zak_recht.koz_identif                          is '[PK] N15 - Kadastrale identificatie';
comment on column pv_info_i_koz_zak_recht.eindd_recht                          is '[geen RSGB type] - Einddatum recht';
comment on column pv_info_i_koz_zak_recht.indic_betrokken_in_splitsing         is '[geen RSGB type] - Indicatie betrokken in splitsing';
comment on column pv_info_i_koz_zak_recht.ingangsdatum_recht                   is 'OnvolledigeDatum - Ingangsdatum recht';
comment on column pv_info_i_koz_zak_recht.pso_identif                          is '[PK] AN32, FK naar subject.identif - Identificatie';
comment on column pv_info_i_koz_zak_recht.soort_eigenaar                       is '';
comment on column pv_info_i_koz_zak_recht.geslachtsnaam                        is 'Groepsattribuut Naam NATUURLIJK PERSOON.Geslachtsnaam - Geslachtsnaam';
comment on column pv_info_i_koz_zak_recht.voorvoegsel                          is 'Groepsattribuut Naam NATUURLIJK PERSOON.Voorvoegsel geslachtsnaam - Voorvoegsel';
comment on column pv_info_i_koz_zak_recht.voornamen                            is 'Groepsattribuut Naam NATUURLIJK PERSOON.Voornamen - Voornamen';
comment on column pv_info_i_koz_zak_recht.geslacht                             is 'AN1 - Geslachtsaanduiding';
comment on column pv_info_i_koz_zak_recht.woonadres                            is 'Groepsattribuut Verblijfadres INGESCHREVEN NATUURLIJK PERSOON.Locatie beschrijving - Locatie beschrijving';
comment on column pv_info_i_koz_zak_recht.geboortedatum                        is 'Groepsattribuut Geboorte INGESCHREVEN NATUURLIJK PERSOON.Geboortedatum - Geboortedatum';
comment on column pv_info_i_koz_zak_recht.geboorteplaats                       is 'Groepsattribuut Geboorte INGESCHREVEN NATUURLIJK PERSOON.Geboorteplaats - Geboorteplaats';
comment on column pv_info_i_koz_zak_recht.overlijdensdatum                     is 'Groepsattribuut Overlijden INGESCHREVEN NATUURLIJK PERSOON.Overlijdensdatum - Overlijdensdatum';
comment on column pv_info_i_koz_zak_recht.naam_niet_natuurlijk_persoon         is 'AN500 - (Statutaire) Naam';
comment on column pv_info_i_koz_zak_recht.rechtsvorm                           is 'AN50 - Rechtsvorm';
comment on column pv_info_i_koz_zak_recht.statutaire_zetel                     is 'AN40 - Statutaire zetel';
comment on column pv_info_i_koz_zak_recht.kvk_nummer                           is 'N8 - KvK-nummer';
comment on column pv_info_i_koz_zak_recht.aandeel_noemer                       is 'Groepsattribuut Aandeel in recht ZAKELIJK RECHT.Noemer - Noemer';
comment on column pv_info_i_koz_zak_recht.aandeel_teller                       is 'Groepsattribuut Aandeel in recht ZAKELIJK RECHT.Teller - Teller';
comment on column pv_info_i_koz_zak_recht.arv_omschr                           is 'Referentielijst property AARD RECHT VERKORT.Omschrijving aard recht verkort - Omschrijving aard recht verkort';
comment on column pv_info_i_koz_zak_recht.fk_3avr_aand                         is '[FK] AN6, FK naar aard_verkregen_recht.aand: "Referentielijst ZAKELIJK RECHT.Aanduiding aard verkregen recht"';
comment on column pv_info_i_koz_zak_recht_aant.koz_identif                     is '[PK] N15 - Kadastrale identificatie';
comment on column pv_info_i_koz_zak_recht_aant.kadaster_identif                is '[PK]  - Kadaster identificatie zakelijk recht';
comment on column pv_info_i_koz_zak_recht_aant.kadaster_identif_aantek_recht   is '[PK]  - Kadaster identificatie aantekening recht';
comment on column pv_info_i_koz_zak_recht_aant.aard_aantek_recht               is '[geen RSGB type] - Aard aantekening recht';
comment on column pv_info_i_koz_zak_recht_aant.begindatum_aantek_recht         is 'OnvolledigeDatum - Begindatum aantekening recht';
comment on column pv_info_i_koz_zak_recht_aant.beschrijving_aantek_recht       is '[geen RSGB type] - Beschrijving aantekening recht';
comment on column pv_info_i_koz_zak_recht_aant.eindd_aantek_recht              is '[geen RSGB type] - Einddatum aantekening recht';
comment on column pv_info_o_koz_adres.koz_identif                              is '[FK] N15, FK naar kad_onrrnd_zk.kad_identif';
comment on column pv_info_o_koz_adres.aon_identif                              is '[PK] AN16 - Identificatie adresseerbaar object aanduiding';
comment on column pv_info_o_koz_adres.dat_beg_geldh                            is '';
comment on column pv_info_o_koz_adres.dat_eind_geldh                           is 'OnvolledigeDatum - Datum einde geldigheid addresserbaar object aanduiding';
comment on column pv_info_o_koz_adres.huinummer                                is 'N5 - Huisnummer';
comment on column pv_info_o_koz_adres.huinummertoevoeging                      is 'AN4 - Huisnummertoevoeging';
comment on column pv_info_o_koz_adres.huisletter                               is 'AN1 - Huisletter';
comment on column pv_info_o_koz_adres.postcode                                 is 'AN6 - Postcode';
comment on column pv_info_o_koz_adres.naam_openb_rmte                          is 'AN80 - Naam openbare ruimte';
comment on column pv_info_o_koz_adres.gem_code                                 is ' PK] N4 - Gemeentecode';
comment on column pv_info_o_koz_adres.gem_naam                                 is 'AN40 - Gemeentenaam';
comment on column pv_info_o_koz_adres.wpl_naam                                 is 'AN80 - Woonplaatsnaam';
comment on column pv_info_o_koz_adres.status                                   is 'AN80 - Nummeraanduidingstatus';
comment on column pv_info_o_lip_hoofdadr.lip_indentif                          is '[PK] AN16, FK naar benoemd_terrein.sc_identif - Benoemd object identificatie';
comment on column pv_info_o_lip_hoofdadr.indic_geconst                         is 'AN1 - Indicatie geconstateerde ligplaats';
comment on column pv_info_o_lip_hoofdadr.lip_status                            is 'AN80 - Ligplaatsstatus';
comment on column pv_info_o_lip_hoofdadr.lip_dat_beg_geldh                     is '';
comment on column pv_info_o_lip_hoofdadr.clazz                                 is 'Aanduiding subclass';
comment on column pv_info_o_lip_hoofdadr.lip_datum_einde_geldh                 is 'OnvolledigeDatum - Datum einde geldigheid benoemd terrein';
comment on column pv_info_o_lip_hoofdadr.nummeraand_identif                    is '[PK] AN16 - Identificatie adresseerbaar object aanduiding';
comment on column pv_info_o_lip_hoofdadr.nummeraand_dat_beg_geldh              is '';
comment on column pv_info_o_lip_hoofdadr.nummeraand_datum_einde_geldh          is 'OnvolledigeDatum - Datum einde geldigheid addresserbaar object aanduiding';
comment on column pv_info_o_lip_hoofdadr.huinummer                             is 'N5 - Huisnummer';
comment on column pv_info_o_lip_hoofdadr.huinummertoevoeging                   is 'AN4 - Huisnummertoevoeging';
comment on column pv_info_o_lip_hoofdadr.huisletter                            is 'AN1 - Huisletter';
comment on column pv_info_o_lip_hoofdadr.postcode                              is 'AN6 - Postcode';
comment on column pv_info_o_lip_hoofdadr.naam_openb_rmte                       is 'AN80 - Naam openbare ruimte';
comment on column pv_info_o_lip_hoofdadr.gem_code                              is ' [PK] N4 - Gemeentecode';
comment on column pv_info_o_lip_hoofdadr.gem_naam                              is 'AN40 - Gemeentenaam';
comment on column pv_info_o_lip_hoofdadr.wpl_naam                              is 'AN80 - Woonplaatsnaam';
comment on column pv_info_o_lip_hoofdadr.indic_hoofdadres                      is 'boolean - Indicatie hoofdadres';
comment on column pv_info_o_lip_hoofdadr.nummeraand_status                     is 'AN80 - Nummeraanduidingstatus';
comment on column pv_info_o_stp_hoofdadr.stp_indentif                          is '[PK] AN16, FK naar benoemd_terrein.sc_identif - Benoemd object identificatie';
comment on column pv_info_o_stp_hoofdadr.indic_geconst                         is 'AN1 - Indicatie geconstateerde standplaats';
comment on column pv_info_o_stp_hoofdadr.stp_status                            is 'AN80 - Standplaatsstatus';
comment on column pv_info_o_stp_hoofdadr.stp_dat_beg_geldh                     is '';
comment on column pv_info_o_stp_hoofdadr.clazz                                 is 'Aanduiding subclass';
comment on column pv_info_o_stp_hoofdadr.stp_datum_einde_geldh                 is 'OnvolledigeDatum - Datum einde geldigheid benoemd terrein';
comment on column pv_info_o_stp_hoofdadr.nummeraand_identif                    is '[PK] AN16 - Identificatie adresseerbaar object aanduiding';
comment on column pv_info_o_stp_hoofdadr.nummeraand_dat_beg_geldh              is '';
comment on column pv_info_o_stp_hoofdadr.nummeraand_datum_einde_geldh          is 'OnvolledigeDatum - Datum einde geldigheid addresserbaar object aanduiding';
comment on column pv_info_o_stp_hoofdadr.huinummer                             is 'N5 - Huisnummer';
comment on column pv_info_o_stp_hoofdadr.huinummertoevoeging                   is 'AN4 - Huisnummertoevoeging';
comment on column pv_info_o_stp_hoofdadr.huisletter                            is 'AN1 - Huisletter';
comment on column pv_info_o_stp_hoofdadr.postcode                              is 'AN6 - Postcode';
comment on column pv_info_o_stp_hoofdadr.naam_openb_rmte                       is 'AN80 - Naam openbare ruimte';
comment on column pv_info_o_stp_hoofdadr.gem_code                              is ' [PK] N4 - Gemeentecode';
comment on column pv_info_o_stp_hoofdadr.gem_naam                              is 'AN40 - Gemeentenaam';
comment on column pv_info_o_stp_hoofdadr.wpl_naam                              is 'AN80 - Woonplaatsnaam';
comment on column pv_info_o_stp_hoofdadr.indic_hoofdadres                      is 'boolean - Indicatie hoofdadres';
comment on column pv_info_o_stp_hoofdadr.nummeraand_status                     is 'AN80 - Nummeraanduidingstatus';
comment on column pv_info_o_vob_hoofdadr.vbo_identif                           is '[PK] AN16, FK naar gebouwd_obj.sc_identif - Benoemd object identificatie';
comment on column pv_info_o_vob_hoofdadr.indic_geconstateerd                   is 'AN1 - Indicatie geconstateerd verblijfsobject';
comment on column pv_info_o_vob_hoofdadr.vbo_status                            is 'AN80 - Verblijfsobjectstatus';
comment on column pv_info_o_vob_hoofdadr.vbo_dat_beg_geldh                     is '';
comment on column pv_info_o_vob_hoofdadr.clazz                                 is 'Aanduiding subclass';
comment on column pv_info_o_vob_hoofdadr.vbo_datum_einde_geldh                 is 'OnvolledigeDatum - Datum einde geldigheid gebouwd object';
comment on column pv_info_o_vob_hoofdadr.oppervlakte_obj                       is 'N6 - Oppervlakte (verblijfs)object';
comment on column pv_info_o_vob_hoofdadr.nummeraand_identif                    is '[PK] AN16 - Identificatie adresseerbaar object aanduiding';
comment on column pv_info_o_vob_hoofdadr.nummeraand_dat_beg_geldh              is '';
comment on column pv_info_o_vob_hoofdadr.nummeraand_datum_einde_geldh          is 'OnvolledigeDatum - Datum einde geldigheid addresserbaar object aanduiding';
comment on column pv_info_o_vob_hoofdadr.huinummer                             is 'N5 - Huisnummer';
comment on column pv_info_o_vob_hoofdadr.huinummertoevoeging                   is 'AN4 - Huisnummertoevoeging';
comment on column pv_info_o_vob_hoofdadr.huisletter                            is 'AN1 - Huisletter';
comment on column pv_info_o_vob_hoofdadr.postcode                              is 'AN6 - Postcode';
comment on column pv_info_o_vob_hoofdadr.naam_openb_rmte                       is 'AN80 - Naam openbare ruimte';
comment on column pv_info_o_vob_hoofdadr.gem_code                              is ' [PK] N4 - Gemeentecode';
comment on column pv_info_o_vob_hoofdadr.gem_naam                              is 'AN40 - Gemeentenaam';
comment on column pv_info_o_vob_hoofdadr.wpl_naam                              is 'AN80 - Woonplaatsnaam';
comment on column pv_info_o_vob_hoofdadr.indic_hoofdadres                      is 'boolean - Indicatie hoofdadres';
comment on column pv_info_o_vob_hoofdadr.nummeraand_status                     is 'AN80 - Nummeraanduidingstatus';
comment on column pv_map_i_kpe.cu_aard_bebouwing                               is 'Groepsattribuut Cultuur onbebouwd KADASTRALE ONROERENDE ZAAK.Aard bebouwing - Aard bebouwing';
comment on column pv_map_i_kpe.sc_kad_identif                                  is '[PK] N15, FK naar kad_onrrnd_zk.kad_identif - Kadastrale identificatie';
comment on column pv_map_i_kpe.aand_soort_grootte                              is 'boolean - Aanduiding soort grootte';
comment on column pv_map_i_kpe.grootte_perceel                                 is 'N8 - Grootte perceel';
comment on column pv_map_i_kpe.omschr_deelperceel                              is 'AN1120 - Omschrijving deelperceel';
comment on column pv_map_i_kpe.ka_kad_gemeentecode                             is 'Groepsattribuut Kadastrale aanduiding KADASTRAAL PERCEEL.Kadastrale gemeentecode - Kadastrale gemeentecode';
comment on column pv_map_i_kpe.ka_perceelnummer                                is 'Groepsattribuut Kadastrale aanduiding KADASTRAAL PERCEEL.Perceelnummer - Perceelnummer';
comment on column pv_map_i_kpe.ka_sectie                                       is 'Groepsattribuut Kadastrale aanduiding KADASTRAAL PERCEEL.Sectie - Sectie';
comment on column pv_map_i_kpe.begrenzing_perceel                              is 'GM_Surface - Begrenzing perceel';
comment on column pv_map_i_kpe.aanduiding                                      is 'Groepsattribuut Kadastrale aanduiding KADASTRAAL PERCEEL.Perceelnummer - Perceelnummer';
comment on column pv_map_i_kpe.cu_aard_cultuur_onbebouwd                       is 'Groepsattribuut Cultuur onbebouwd KADASTRALE ONROERENDE ZAAK.Aard cultuur onbebouwd - Aard cultuur onbebouwd';
comment on column pv_map_i_kpe.dat_beg_geldh                                   is '';
comment on column pv_map_i_kpe.datum_einde_geldh                               is 'OnvolledigeDatum - Datum einde geldigheid kadastrale onroerende zaak';
comment on column pv_map_i_kpe.kad_identif                                     is '[PK] N15 - Kadastrale identificatie';
comment on column pv_map_i_kpe.ks_bedrag                                       is 'Groepsattribuut Koopsom KADASTRALE ONROERENDE ZAAK.Bedrag - Bedrag';
comment on column pv_map_i_kpe.ks_koopjaar                                     is 'Groepsattribuut Koopsom KADASTRALE ONROERENDE ZAAK.Koopjaar - Koopjaar';
comment on column pv_map_i_kpe.ks_meer_onroerendgoed                           is 'Groepsattribuut Koopsom KADASTRALE ONROERENDE ZAAK.Meer onroerendgoed - Meer onroerendgoed';
comment on column pv_map_o_bte.dat_beg_geldh                                   is '';
comment on column pv_map_o_bte.sc_identif                                      is '[PK] AN16, FK naar benoemd_obj.identif - Benoemd object identificatie';
comment on column pv_map_o_bte.clazz                                           is 'Aanduiding subclass';
comment on column pv_map_o_bte.datum_einde_geldh                               is 'OnvolledigeDatum - Datum einde geldigheid benoemd terrein';
comment on column pv_map_o_bte.bt_geom                                         is 'GM_Surface - Benoemd terrein geometrie';
comment on column pv_map_o_kpe.cu_aard_bebouwing                               is 'Groepsattribuut Cultuur onbebouwd KADASTRALE ONROERENDE ZAAK.Aard bebouwing - Aard bebouwing';
comment on column pv_map_o_kpe.sc_kad_identif                                  is '[PK] N15, FK naar kad_onrrnd_zk.kad_identif - Kadastrale identificatie';
comment on column pv_map_o_kpe.aand_soort_grootte                              is 'boolean - Aanduiding soort grootte';
comment on column pv_map_o_kpe.grootte_perceel                                 is 'N8 - Grootte perceel';
comment on column pv_map_o_kpe.omschr_deelperceel                              is 'AN1120 - Omschrijving deelperceel';
comment on column pv_map_o_kpe.ka_kad_gemeentecode                             is 'Groepsattribuut Kadastrale aanduiding KADASTRAAL PERCEEL.Kadastrale gemeentecode - Kadastrale gemeentecode';
comment on column pv_map_o_kpe.ka_perceelnummer                                is 'Groepsattribuut Kadastrale aanduiding KADASTRAAL PERCEEL.Perceelnummer - Perceelnummer';
comment on column pv_map_o_kpe.ka_sectie                                       is 'Groepsattribuut Kadastrale aanduiding KADASTRAAL PERCEEL.Sectie - Sectie';
comment on column pv_map_o_kpe.begrenzing_perceel                              is 'GM_Surface - Begrenzing perceel';
comment on column pv_map_o_kpe.aanduiding                                      is 'Groepsattribuut Kadastrale aanduiding KADASTRAAL PERCEEL.Perceelnummer - Perceelnummer';
comment on column pv_map_o_kpe.cu_aard_cultuur_onbebouwd                       is 'Groepsattribuut Cultuur onbebouwd KADASTRALE ONROERENDE ZAAK.Aard cultuur onbebouwd - Aard cultuur onbebouwd';
comment on column pv_map_o_kpe.dat_beg_geldh                                   is '';
comment on column pv_map_o_kpe.datum_einde_geldh                               is 'OnvolledigeDatum - Datum einde geldigheid kadastrale onroerende zaak';
comment on column pv_map_o_kpe.kad_identif                                     is '[PK] N15 - Kadastrale identificatie';
comment on column pv_map_o_kpe.ks_meer_onroerendgoed                           is 'Groepsattribuut Koopsom KADASTRALE ONROERENDE ZAAK.Meer onroerendgoed - Meer onroerendgoed';
comment on column pv_map_o_lip.sc_identif                                      is '[PK] AN16, FK naar benoemd_terrein.sc_identif - Benoemd object identificatie';
comment on column pv_map_o_lip.indic_geconst                                   is 'AN1 - Indicatie geconstateerde ligplaats';
comment on column pv_map_o_lip.status                                          is 'AN80 - Ligplaatsstatus';
comment on column pv_map_o_lip.fk_4nra_sc_identif                              is '[FK] AN16, FK naar nummeraand.sc_identif (is FK naar superclass ADRESSEERBAAR OBJECT AANDUIDING): "heeft als hoofdadres"';
comment on column pv_map_o_lip.dat_beg_geldh                                   is '';
comment on column pv_map_o_lip.clazz                                           is 'Aanduiding subclass';
comment on column pv_map_o_lip.datum_einde_geldh                               is 'OnvolledigeDatum - Datum einde geldigheid benoemd terrein';
comment on column pv_map_o_lip.bt_geom                                         is 'GM_Surface - Benoemd terrein geometrie';
comment on column pv_map_o_pnd.dat_beg_geldh                                   is '';
comment on column pv_map_o_pnd.identif                                         is '[PK] AN16 - Pandidentificatie';
comment on column pv_map_o_pnd.datum_einde_geldh                               is 'OnvolledigeDatum - Datum einde geldigheid pand';
comment on column pv_map_o_pnd.indic_geconstateerd                             is 'AN1 - Indicatie geconstateerd pand';
comment on column pv_map_o_pnd.oorspronkelijk_bouwjaar                         is 'N4 - Oorspronkelijk bouwjaar pand';
comment on column pv_map_o_pnd.status                                          is 'AN80 - Pandstatus';
comment on column pv_map_o_pnd.geom_bovenaanzicht                              is 'GM_Surface - Pandgeometrie bovenaanzicht';
comment on column pv_map_o_stp.sc_identif                                      is '[PK] AN16, FK naar benoemd_terrein.sc_identif - Benoemd object identificatie';
comment on column pv_map_o_stp.indic_geconst                                   is 'AN1 - Indicatie geconstateerde standplaats';
comment on column pv_map_o_stp.status                                          is 'AN80 - Standplaatsstatus';
comment on column pv_map_o_stp.fk_4nra_sc_identif                              is '[FK] AN16, FK naar nummeraand.sc_identif (is FK naar superclass ADRESSEERBAAR OBJECT AANDUIDING): "heeft als hoofdadres"';
comment on column pv_map_o_stp.dat_beg_geldh                                   is '';
comment on column pv_map_o_stp.clazz                                           is 'Aanduiding subclass';
comment on column pv_map_o_stp.datum_einde_geldh                               is 'OnvolledigeDatum - Datum einde geldigheid benoemd terrein';
comment on column pv_map_o_stp.bt_geom                                         is 'GM_Surface - Benoemd terrein geometrie';
comment on column pv_map_o_vob.sc_identif                                      is '[PK] AN16, FK naar gebouwd_obj.sc_identif - Benoemd object identificatie';
comment on column pv_map_o_vob.fk_11nra_sc_identif                             is '[FK] AN16, FK naar nummeraand.sc_identif (is FK naar superclass ADRESSEERBAAR OBJECT AANDUIDING): "heeft als hoofdadres"';
comment on column pv_map_o_vob.indic_geconstateerd                             is 'AN1 - Indicatie geconstateerd verblijfsobject';
comment on column pv_map_o_vob.status                                          is 'AN80 - Verblijfsobjectstatus';
comment on column pv_map_o_vob.dat_beg_geldh                                   is '';
comment on column pv_map_o_vob.clazz                                           is 'Aanduiding subclass';
comment on column pv_map_o_vob.datum_einde_geldh                               is 'OnvolledigeDatum - Datum einde geldigheid gebouwd object';
comment on column pv_map_o_vob.oppervlakte_obj                                 is 'N6 - Oppervlakte (verblijfs)object';
comment on column pv_map_o_vob.puntgeom                                        is 'GM_Point - Gebouwd objectpuntgeometrie';
