version: '3.9'

volumes:
  brmo-db:
  brmo-logs:
  brmo-data:

services:
  db:
    build:
      context: ./src/main/docker
      dockerfile: pg_conf/Dockerfile
    shm_size: '2gb'
    command: >
            -c shared_buffers=8GB
            -c max_connections=200
            -c max_wal_size=3GB
            -c autovacuum_max_workers=4
            -c maintenance_work_mem=2GB
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      BRMO_PASSWORD: ${BRMO_DB_PASSWORD:-brmo}
      BRMO_USER: brmo
    restart: on-failure
    volumes:
      - brmo-db:/var/lib/postgresql/data
    healthcheck:
      test: su postgres -c "pg_isready --dbname=rsgb -q"
      interval: 1m30s
      timeout: 10s
      retries: 3

  brmo:
    build:
      context: ./src/main/docker
      dockerfile: Dockerfile
    shm_size: '512mb'
    volumes:
      - brmo-logs:/usr/local/tomcat/logs
      - brmo-data:/opt/brmo-data
    restart: on-failure
    env_file:
      - ./src/main/docker/env/tomcat
    depends_on:
      - db
    healthcheck:
      test: "curl --fail -s http://localhost:8080/brmo-service/ || exit 1"
      interval: 1m30s
      timeout: 10s
      retries: 3
