# Description: Docker compose file voor BRMO service met database
volumes:
  brmo-db:
  brmo-db-ssl:
  brmo-logs:
  brmo-data:


services:
  db:
    image: ghcr.io/b3partners/brmo-service-db:${BRMO_VERSION:-snapshot}
    shm_size: '2gb'
    volumes:
      - brmo-db:/var/lib/postgresql/data
      - brmo-db-ssl:/opt/ssl
    command: >
      -c max_connections=200
      -c shared_buffers=4GB
      -c maintenance_work_mem=2GB
      -c work_mem=16MB
      -c max_wal_size=3GB
      -c autovacuum_max_workers=4
      -c ssl=${ENABLE_TLS:-on}
      -c ssl_cert_file=${SSL_CERT_FILE:-/opt/ssl/certs/certificate.pem}
      -c ssl_key_file=${SSL_KEY_FILE:-/opt/ssl/private/private.key}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DB_PASS_RSGB: ${DB_PASS_RSGB:-rsgb}
      DB_PASS_STAGING: ${DB_PASS_STAGING:-staging}
      DB_PASS_RSGBBGT: ${DB_PASS_RSGBBGT:-rsgbbgt}
      DB_PASS_TOPNL: ${DB_PASS_TOPNL:-topnl}
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U postgres -d staging
      interval: 25s
      timeout: 10s
      retries: 3


  brmo:
    image: ghcr.io/b3partners/brmo-service:${BRMO_VERSION:-snapshot}
    shm_size: '512mb'
    volumes:
      - brmo-logs:/usr/local/tomcat/logs
      - brmo-data:/opt/brmo-data
    environment:
      PG_HOST: ${PG_HOST:-db}
      PG_PORT: ${PG_PORT:-5432}
      DB_PASS_RSGB: ${DB_PASS_RSGB:-rsgb}
      DB_PASS_STAGING: ${DB_PASS_STAGING:-staging}
      DB_PASS_RSGBBGT: ${DB_PASS_RSGBBGT:-rsgbbgt}
      DB_PASS_TOPNL: ${DB_PASS_TOPNL:-topnl}
      DB_NAME_RSGB: ${DB_NAME_RSGB:-rsgb}
      DB_NAME_STAGING: ${DB_NAME_STAGING:-staging}
      DB_NAME_RSGBBGT: ${DB_NAME_RSGBBGT:-rsgbbgt}
      DB_NAME_TOPNL: ${DB_NAME_TOPNL:-topnl}
      DB_USER_RSGB: ${DB_USER_RSGB:-rsgb}
      DB_USER_STAGING: ${DB_USER_STAGING:-staging}
      DB_USER_RSGBBGT: ${DB_USER_RSGBBGT:-rsgbbgt}
      DB_USER_TOPNL: ${DB_USER_TOPNL:-topnl}
      CATALINA_OPTS: -DMAIL_FROM=${MAIL_FROM:-brmo-no-reply@b3partners.nl}
        -DMAIL_HOST=${MAIL_HOST:-mail.b3partners.nl}
        -DPG_PORT=${PG_PORT:-5432}
        -DPG_HOST=${PG_HOST:-db}
        -DDB_PASS_RSGB=${DB_PASS_RSGB}
        -DDB_PASS_STAGING=${DB_PASS_STAGING}
        -DDB_PASS_RSGBBGT=${DB_PASS_RSGBBGT}
        -DDB_PASS_TOPNL=${DB_PASS_TOPNL}
        -DHR_ACTIVE=${HR_ACTIVE:-false}
        -DHR_PASS_KEYSTORE=${HR_PASS_KEYSTORE:-changeme}
        -DHR_PASS_TRUSTSTORE=${HR_PASS_TRUSTSTORE:-changeme}
        -DHR_ISPREPROD=${HR_ISPREPROD:-true}
        -DHR_URL=${HR_URL:-https://webservices.preprod.kvk.nl/postbus1}
        -DHR_IMAP_RESOURCE=${HR_IMAP_RESOURCE:-disabled}
        -DHR_IMAP_USER=${HR_IMAP_USER:-changeme}
        -DHR_IMAP_PASS=${HR_IMAP_PASS:-changeme}
        -DHR_IMAP_HOST=${HR_IMAP_HOST:-mail.b3partners.nl}
        -DDB_NAME_RSGB=${DB_NAME_RSGB}
        -DDB_NAME_STAGING=${DB_NAME_STAGING}
        -DDB_NAME_RSGBBGT=${DB_NAME_RSGBBGT}
        -DDB_NAME_TOPNL=${DB_NAME_TOPNL}
        -DDB_USER_RSGB=${DB_USER_RSGB}
        -DDB_USER_STAGING=${DB_USER_STAGING}
        -DDB_USER_RSGBBGT=${DB_USER_RSGBBGT}
        -DDB_USER_TOPNL=${DB_USER_TOPNL}
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:8080/brmo-service/ || exit 1
      interval: 25s
      timeout: 5s
      retries: 2
