version: '3.9'

volumes:
  brmo-db:
  brmo-logs:
  brmo-data:


services:
  db:
    image: ghcr.io/b3partners/brmo-service-db:${BRMO_VERSION:-snapshot}
    shm_size: '2gb'
    command: >
      -c shared_buffers=8GB
      -c max_connections=200
      -c max_wal_size=3GB
      -c autovacuum_max_workers=4
      -c maintenance_work_mem=2GB
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DB_PASS_RSGB: ${DB_PASS_RSGB:-rsgb}
      DB_PASS_STAGING: ${DB_PASS_STAGING:-staging}
      DB_PASS_RSGBBGT: ${DB_PASS_RSGBBGT:-rsgbbgt}
      DB_PASS_TOPNL: ${DB_PASS_TOPNL:-topnl}
    volumes:
      - brmo-db:/var/lib/postgresql/data
    restart: unless-stopped


  brmo:
    image: ghcr.io/b3partners/brmo-service:${BRMO_VERSION:-snapshot}
    shm_size: '512mb'
    volumes:
      - brmo-logs:/usr/local/tomcat/logs
      - brmo-data:/opt/brmo-data
    environment:
      PG_HOST: ${PG_HOST:-db}
      PG_PORT: ${PG_PORT:-5432}
      DB_PASS_RSGB: ${DB_PASS_RSGB:-rsgb}
      DB_PASS_STAGING: ${DB_PASS_STAGING:-staging}
      DB_PASS_RSGBBGT: ${DB_PASS_RSGBBGT:-rsgbbgt}
      DB_PASS_TOPNL: ${DB_PASS_TOPNL:-topnl}
      CATALINA_OPTS: -DMAIL_FROM=${MAIL_FROM:-brmo-no-reply@b3partners.nl} -DMAIL_HOST=${MAIL_HOST:-mail.b3partners.nl} -DPG_PORT=${PG_PORT:-5432} -DPG_HOST=${PG_HOST:-db} -DDB_PASS_RSGB=${DB_PASS_RSGB} -DDB_PASS_STAGING=${DB_PASS_STAGING} -DDB_PASS_RSGBBGT=${DB_PASS_RSGBBGT} -DDB_PASS_TOPNL=${DB_PASS_TOPNL}
    depends_on:
      - db
    restart: unless-stopped