INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('1', 'Beklemrecht');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('2', 'Eigendom (recht van)');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('3', 'Erfpacht (recht van)');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('4', 'Gebruik en bewoning (recht van)');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('5', 'Grondrente (recht van)');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('6', 'Huurrecht (zakelijk)');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('7', 'Opstal (recht van)');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('8', 'Optierecht (zakelijk)');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('9', 'Oud-vaderlandsrecht');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('10', 'Privaatrechtelijke belemmering (als bedoeld in artikel 5, lid 3, onder b, Belemmeringenwet Privaatrecht)');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('11', 'Stadsmeierrecht');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('12', 'Vruchtgebruik (recht van)');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('13', 'Erfpacht en Opstal (recht van)');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('14', 'Opstalrecht Nutsvoorzieningen');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('15', 'Eigendom Telecommunicatienetwerk');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('16', 'Erfpachtrecht Telecommunicatienetwerk');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('17', 'Vruchtgebruik Telecommunicatienetwerk');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('18', 'Overige zakelijke rechten');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('19', 'Voorrecht');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('20', 'Zakelijk recht na twee of meer zakelijke belastingen');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('21', 'Zakelijke belasting derde of volgende');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('22', 'BP-recht');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('23', 'Opstalrecht Nutsvoorzieningen op gedeelte van perceel');
INSERT INTO aard_verkregen_recht (aand, omschr_aard_verkregenr_recht) VALUES ('24', 'Zakelijk recht als bedoeld in artikel 5, lid 3, onder b, van de Belemmeringenwet Privaatrecht op gedeelte van perceel');
