SET AUTOCOMMIT 100;
-- gemeenten 2022
INSERT INTO gemeente (code, naam) VALUES (1680, 'Aa en Hunze');
INSERT INTO gemeente (code, naam) VALUES (358, 'Aalsmeer');
INSERT INTO gemeente (code, naam) VALUES (197, 'Aalten');
INSERT INTO gemeente (code, naam) VALUES (59, 'Achtkarspelen');
INSERT INTO gemeente (code, naam) VALUES (482, 'Alblasserdam');
INSERT INTO gemeente (code, naam) VALUES (613, 'Albrandswaard');
INSERT INTO gemeente (code, naam) VALUES (361, 'Alkmaar');
INSERT INTO gemeente (code, naam) VALUES (141, 'Almelo');
INSERT INTO gemeente (code, naam) VALUES (34, 'Almere');
INSERT INTO gemeente (code, naam) VALUES (484, 'Alphen aan den Rijn');
INSERT INTO gemeente (code, naam) VALUES (1723, 'Alphen-Chaam');
INSERT INTO gemeente (code, naam) VALUES (1959, 'Altena');
INSERT INTO gemeente (code, naam) VALUES (60, 'Ameland');
INSERT INTO gemeente (code, naam) VALUES (307, 'Amersfoort');
INSERT INTO gemeente (code, naam) VALUES (362, 'Amstelveen');
INSERT INTO gemeente (code, naam) VALUES (363, 'Amsterdam');
INSERT INTO gemeente (code, naam) VALUES (200, 'Apeldoorn');
INSERT INTO gemeente (code, naam) VALUES (202, 'Arnhem');
INSERT INTO gemeente (code, naam) VALUES (106, 'Assen');
INSERT INTO gemeente (code, naam) VALUES (743, 'Asten');
INSERT INTO gemeente (code, naam) VALUES (744, 'Baarle-Nassau');
INSERT INTO gemeente (code, naam) VALUES (308, 'Baarn');
INSERT INTO gemeente (code, naam) VALUES (489, 'Barendrecht');
INSERT INTO gemeente (code, naam) VALUES (203, 'Barneveld');
INSERT INTO gemeente (code, naam) VALUES (888, 'Beek');
INSERT INTO gemeente (code, naam) VALUES (1954, 'Beekdaelen');
INSERT INTO gemeente (code, naam) VALUES (889, 'Beesel');
INSERT INTO gemeente (code, naam) VALUES (1945, 'Berg en Dal');
INSERT INTO gemeente (code, naam) VALUES (1724, 'Bergeijk');
INSERT INTO gemeente (code, naam) VALUES (893, 'Bergen (L.)');
INSERT INTO gemeente (code, naam) VALUES (373, 'Bergen (NH.)');
INSERT INTO gemeente (code, naam) VALUES (748, 'Bergen op Zoom');
INSERT INTO gemeente (code, naam) VALUES (1859, 'Berkelland');
INSERT INTO gemeente (code, naam) VALUES (1721, 'Bernheze');
INSERT INTO gemeente (code, naam) VALUES (753, 'Best');
INSERT INTO gemeente (code, naam) VALUES (209, 'Beuningen');
INSERT INTO gemeente (code, naam) VALUES (375, 'Beverwijk');
INSERT INTO gemeente (code, naam) VALUES (310, 'De Bilt');
INSERT INTO gemeente (code, naam) VALUES (1728, 'Bladel');
INSERT INTO gemeente (code, naam) VALUES (376, 'Blaricum');
INSERT INTO gemeente (code, naam) VALUES (377, 'Bloemendaal');
INSERT INTO gemeente (code, naam) VALUES (1901, 'Bodegraven-Reeuwijk');
INSERT INTO gemeente (code, naam) VALUES (755, 'Boekel');
INSERT INTO gemeente (code, naam) VALUES (1681, 'Borger-Odoorn');
INSERT INTO gemeente (code, naam) VALUES (147, 'Borne');
INSERT INTO gemeente (code, naam) VALUES (654, 'Borsele');
INSERT INTO gemeente (code, naam) VALUES (757, 'Boxtel');
INSERT INTO gemeente (code, naam) VALUES (758, 'Breda');
INSERT INTO gemeente (code, naam) VALUES (501, 'Brielle');
INSERT INTO gemeente (code, naam) VALUES (1876, 'Bronckhorst');
INSERT INTO gemeente (code, naam) VALUES (213, 'Brummen');
INSERT INTO gemeente (code, naam) VALUES (899, 'Brunssum');
INSERT INTO gemeente (code, naam) VALUES (312, 'Bunnik');
INSERT INTO gemeente (code, naam) VALUES (313, 'Bunschoten');
INSERT INTO gemeente (code, naam) VALUES (214, 'Buren');
INSERT INTO gemeente (code, naam) VALUES (502, 'Capelle aan den IJssel');
INSERT INTO gemeente (code, naam) VALUES (383, 'Castricum');
INSERT INTO gemeente (code, naam) VALUES (109, 'Coevorden');
INSERT INTO gemeente (code, naam) VALUES (1706, 'Cranendonck');
INSERT INTO gemeente (code, naam) VALUES (216, 'Culemborg');
INSERT INTO gemeente (code, naam) VALUES (148, 'Dalfsen');
INSERT INTO gemeente (code, naam) VALUES (1891, 'Dantumadiel');
INSERT INTO gemeente (code, naam) VALUES (503, 'Delft');
INSERT INTO gemeente (code, naam) VALUES (762, 'Deurne');
INSERT INTO gemeente (code, naam) VALUES (150, 'Deventer');
INSERT INTO gemeente (code, naam) VALUES (384, 'Diemen');
INSERT INTO gemeente (code, naam) VALUES (1774, 'Dinkelland');
INSERT INTO gemeente (code, naam) VALUES (221, 'Doesburg');
INSERT INTO gemeente (code, naam) VALUES (222, 'Doetinchem');
INSERT INTO gemeente (code, naam) VALUES (766, 'Dongen');
INSERT INTO gemeente (code, naam) VALUES (505, 'Dordrecht');
INSERT INTO gemeente (code, naam) VALUES (498, 'Drechterland');
INSERT INTO gemeente (code, naam) VALUES (1719, 'Drimmelen');
INSERT INTO gemeente (code, naam) VALUES (303, 'Dronten');
INSERT INTO gemeente (code, naam) VALUES (225, 'Druten');
INSERT INTO gemeente (code, naam) VALUES (226, 'Duiven');
INSERT INTO gemeente (code, naam) VALUES (1711, 'Echt-Susteren');
INSERT INTO gemeente (code, naam) VALUES (385, 'Edam-Volendam');
INSERT INTO gemeente (code, naam) VALUES (228, 'Ede');
INSERT INTO gemeente (code, naam) VALUES (317, 'Eemnes');
INSERT INTO gemeente (code, naam) VALUES (770, 'Eersel');
INSERT INTO gemeente (code, naam) VALUES (1903, 'Eijsden-Margraten');
INSERT INTO gemeente (code, naam) VALUES (772, 'Eindhoven');
INSERT INTO gemeente (code, naam) VALUES (230, 'Elburg');
INSERT INTO gemeente (code, naam) VALUES (114, 'Emmen');
INSERT INTO gemeente (code, naam) VALUES (388, 'Enkhuizen');
INSERT INTO gemeente (code, naam) VALUES (153, 'Enschede');
INSERT INTO gemeente (code, naam) VALUES (232, 'Epe');
INSERT INTO gemeente (code, naam) VALUES (233, 'Ermelo');
INSERT INTO gemeente (code, naam) VALUES (777, 'Etten-Leur');
INSERT INTO gemeente (code, naam) VALUES (1940, 'De Fryske Marren');
INSERT INTO gemeente (code, naam) VALUES (779, 'Geertruidenberg');
INSERT INTO gemeente (code, naam) VALUES (1771, 'Geldrop-Mierlo');
INSERT INTO gemeente (code, naam) VALUES (1652, 'Gemert-Bakel');
INSERT INTO gemeente (code, naam) VALUES (907, 'Gennep');
INSERT INTO gemeente (code, naam) VALUES (784, 'Gilze en Rijen');
INSERT INTO gemeente (code, naam) VALUES (1924, 'Goeree-Overflakkee');
INSERT INTO gemeente (code, naam) VALUES (664, 'Goes');
INSERT INTO gemeente (code, naam) VALUES (785, 'Goirle');
INSERT INTO gemeente (code, naam) VALUES (1942, 'Gooise Meren');
INSERT INTO gemeente (code, naam) VALUES (512, 'Gorinchem');
INSERT INTO gemeente (code, naam) VALUES (513, 'Gouda');
INSERT INTO gemeente (code, naam) VALUES (518, '''s-Gravenhage');
INSERT INTO gemeente (code, naam) VALUES (14, 'Groningen');
INSERT INTO gemeente (code, naam) VALUES (1729, 'Gulpen-Wittem');
INSERT INTO gemeente (code, naam) VALUES (158, 'Haaksbergen');
INSERT INTO gemeente (code, naam) VALUES (392, 'Haarlem');
INSERT INTO gemeente (code, naam) VALUES (394, 'Haarlemmermeer');
INSERT INTO gemeente (code, naam) VALUES (1655, 'Halderberge');
INSERT INTO gemeente (code, naam) VALUES (160, 'Hardenberg');
INSERT INTO gemeente (code, naam) VALUES (243, 'Harderwijk');
INSERT INTO gemeente (code, naam) VALUES (523, 'Hardinxveld-Giessendam');
INSERT INTO gemeente (code, naam) VALUES (72, 'Harlingen');
INSERT INTO gemeente (code, naam) VALUES (244, 'Hattem');
INSERT INTO gemeente (code, naam) VALUES (396, 'Heemskerk');
INSERT INTO gemeente (code, naam) VALUES (397, 'Heemstede');
INSERT INTO gemeente (code, naam) VALUES (246, 'Heerde');
INSERT INTO gemeente (code, naam) VALUES (74, 'Heerenveen');
INSERT INTO gemeente (code, naam) VALUES (917, 'Heerlen');
INSERT INTO gemeente (code, naam) VALUES (1658, 'Heeze-Leende');
INSERT INTO gemeente (code, naam) VALUES (399, 'Heiloo');
INSERT INTO gemeente (code, naam) VALUES (400, 'Den Helder');
INSERT INTO gemeente (code, naam) VALUES (163, 'Hellendoorn');
INSERT INTO gemeente (code, naam) VALUES (530, 'Hellevoetsluis');
INSERT INTO gemeente (code, naam) VALUES (794, 'Helmond');
INSERT INTO gemeente (code, naam) VALUES (531, 'Hendrik-Ido-Ambacht');
INSERT INTO gemeente (code, naam) VALUES (164, 'Hengelo');
INSERT INTO gemeente (code, naam) VALUES (796, '''s-Hertogenbosch');
INSERT INTO gemeente (code, naam) VALUES (252, 'Heumen');
INSERT INTO gemeente (code, naam) VALUES (797, 'Heusden');
INSERT INTO gemeente (code, naam) VALUES (534, 'Hillegom');
INSERT INTO gemeente (code, naam) VALUES (798, 'Hilvarenbeek');
INSERT INTO gemeente (code, naam) VALUES (402, 'Hilversum');
INSERT INTO gemeente (code, naam) VALUES (1963, 'Hoeksche Waard');
INSERT INTO gemeente (code, naam) VALUES (1735, 'Hof van Twente');
INSERT INTO gemeente (code, naam) VALUES (1966, 'Het Hogeland');
INSERT INTO gemeente (code, naam) VALUES (1911, 'Hollands Kroon');
INSERT INTO gemeente (code, naam) VALUES (118, 'Hoogeveen');
INSERT INTO gemeente (code, naam) VALUES (405, 'Hoorn');
INSERT INTO gemeente (code, naam) VALUES (1507, 'Horst aan de Maas');
INSERT INTO gemeente (code, naam) VALUES (321, 'Houten');
INSERT INTO gemeente (code, naam) VALUES (406, 'Huizen');
INSERT INTO gemeente (code, naam) VALUES (677, 'Hulst');
INSERT INTO gemeente (code, naam) VALUES (353, 'IJsselstein');
INSERT INTO gemeente (code, naam) VALUES (1884, 'Kaag en Braassem');
INSERT INTO gemeente (code, naam) VALUES (166, 'Kampen');
INSERT INTO gemeente (code, naam) VALUES (678, 'Kapelle');
INSERT INTO gemeente (code, naam) VALUES (537, 'Katwijk');
INSERT INTO gemeente (code, naam) VALUES (928, 'Kerkrade');
INSERT INTO gemeente (code, naam) VALUES (1598, 'Koggenland');
INSERT INTO gemeente (code, naam) VALUES (542, 'Krimpen aan den IJssel');
INSERT INTO gemeente (code, naam) VALUES (1931, 'Krimpenerwaard');
INSERT INTO gemeente (code, naam) VALUES (1659, 'Laarbeek');
INSERT INTO gemeente (code, naam) VALUES (882, 'Landgraaf');
INSERT INTO gemeente (code, naam) VALUES (415, 'Landsmeer');
INSERT INTO gemeente (code, naam) VALUES (1621, 'Lansingerland');
INSERT INTO gemeente (code, naam) VALUES (417, 'Laren');
INSERT INTO gemeente (code, naam) VALUES (80, 'Leeuwarden');
INSERT INTO gemeente (code, naam) VALUES (546, 'Leiden');
INSERT INTO gemeente (code, naam) VALUES (547, 'Leiderdorp');
INSERT INTO gemeente (code, naam) VALUES (1916, 'Leidschendam-Voorburg');
INSERT INTO gemeente (code, naam) VALUES (995, 'Lelystad');
INSERT INTO gemeente (code, naam) VALUES (1640, 'Leudal');
INSERT INTO gemeente (code, naam) VALUES (327, 'Leusden');
INSERT INTO gemeente (code, naam) VALUES (1705, 'Lingewaard');
INSERT INTO gemeente (code, naam) VALUES (553, 'Lisse');
INSERT INTO gemeente (code, naam) VALUES (262, 'Lochem');
INSERT INTO gemeente (code, naam) VALUES (809, 'Loon op Zand');
INSERT INTO gemeente (code, naam) VALUES (331, 'Lopik');
INSERT INTO gemeente (code, naam) VALUES (168, 'Losser');
INSERT INTO gemeente (code, naam) VALUES (263, 'Maasdriel');
INSERT INTO gemeente (code, naam) VALUES (1641, 'Maasgouw');
INSERT INTO gemeente (code, naam) VALUES (556, 'Maassluis');
INSERT INTO gemeente (code, naam) VALUES (935, 'Maastricht');
INSERT INTO gemeente (code, naam) VALUES (420, 'Medemblik');
INSERT INTO gemeente (code, naam) VALUES (938, 'Meerssen');
INSERT INTO gemeente (code, naam) VALUES (1948, 'Meierijstad');
INSERT INTO gemeente (code, naam) VALUES (119, 'Meppel');
INSERT INTO gemeente (code, naam) VALUES (687, 'Middelburg');
INSERT INTO gemeente (code, naam) VALUES (1842, 'Midden-Delfland');
INSERT INTO gemeente (code, naam) VALUES (1731, 'Midden-Drenthe');
INSERT INTO gemeente (code, naam) VALUES (1952, 'Midden-Groningen');
INSERT INTO gemeente (code, naam) VALUES (815, 'Mill en Sint Hubert');
INSERT INTO gemeente (code, naam) VALUES (1709, 'Moerdijk');
INSERT INTO gemeente (code, naam) VALUES (1978, 'Molenlanden');
INSERT INTO gemeente (code, naam) VALUES (1955, 'Montferland');
INSERT INTO gemeente (code, naam) VALUES (335, 'Montfoort');
INSERT INTO gemeente (code, naam) VALUES (944, 'Mook en Middelaar');
INSERT INTO gemeente (code, naam) VALUES (1740, 'Neder-Betuwe');
INSERT INTO gemeente (code, naam) VALUES (946, 'Nederweert');
INSERT INTO gemeente (code, naam) VALUES (356, 'Nieuwegein');
INSERT INTO gemeente (code, naam) VALUES (569, 'Nieuwkoop');
INSERT INTO gemeente (code, naam) VALUES (267, 'Nijkerk');
INSERT INTO gemeente (code, naam) VALUES (268, 'Nijmegen');
INSERT INTO gemeente (code, naam) VALUES (1930, 'Nissewaard');
INSERT INTO gemeente (code, naam) VALUES (1970, 'Noardeast-Fryslân');
INSERT INTO gemeente (code, naam) VALUES (1695, 'Noord-Beveland');
INSERT INTO gemeente (code, naam) VALUES (1699, 'Noordenveld');
INSERT INTO gemeente (code, naam) VALUES (171, 'Noordoostpolder');
INSERT INTO gemeente (code, naam) VALUES (575, 'Noordwijk');
INSERT INTO gemeente (code, naam) VALUES (820, 'Nuenen, Gerwen en Nederwetten');
INSERT INTO gemeente (code, naam) VALUES (302, 'Nunspeet');
INSERT INTO gemeente (code, naam) VALUES (579, 'Oegstgeest');
INSERT INTO gemeente (code, naam) VALUES (823, 'Oirschot');
INSERT INTO gemeente (code, naam) VALUES (824, 'Oisterwijk');
INSERT INTO gemeente (code, naam) VALUES (1895, 'Oldambt');
INSERT INTO gemeente (code, naam) VALUES (269, 'Oldebroek');
INSERT INTO gemeente (code, naam) VALUES (173, 'Oldenzaal');
INSERT INTO gemeente (code, naam) VALUES (1773, 'Olst-Wijhe');
INSERT INTO gemeente (code, naam) VALUES (175, 'Ommen');
INSERT INTO gemeente (code, naam) VALUES (1586, 'Oost Gelre');
INSERT INTO gemeente (code, naam) VALUES (826, 'Oosterhout');
INSERT INTO gemeente (code, naam) VALUES (85, 'Ooststellingwerf');
INSERT INTO gemeente (code, naam) VALUES (431, 'Oostzaan');
INSERT INTO gemeente (code, naam) VALUES (432, 'Opmeer');
INSERT INTO gemeente (code, naam) VALUES (86, 'Opsterland');
INSERT INTO gemeente (code, naam) VALUES (828, 'Oss');
INSERT INTO gemeente (code, naam) VALUES (1509, 'Oude IJsselstreek');
INSERT INTO gemeente (code, naam) VALUES (437, 'Ouder-Amstel');
INSERT INTO gemeente (code, naam) VALUES (589, 'Oudewater');
INSERT INTO gemeente (code, naam) VALUES (1734, 'Overbetuwe');
INSERT INTO gemeente (code, naam) VALUES (590, 'Papendrecht');
INSERT INTO gemeente (code, naam) VALUES (1894, 'Peel en Maas');
INSERT INTO gemeente (code, naam) VALUES (765, 'Pekela');
INSERT INTO gemeente (code, naam) VALUES (1926, 'Pijnacker-Nootdorp');
INSERT INTO gemeente (code, naam) VALUES (439, 'Purmerend');
INSERT INTO gemeente (code, naam) VALUES (273, 'Putten');
INSERT INTO gemeente (code, naam) VALUES (177, 'Raalte');
INSERT INTO gemeente (code, naam) VALUES (703, 'Reimerswaal');
INSERT INTO gemeente (code, naam) VALUES (274, 'Renkum');
INSERT INTO gemeente (code, naam) VALUES (339, 'Renswoude');
INSERT INTO gemeente (code, naam) VALUES (1667, 'Reusel-De Mierden');
INSERT INTO gemeente (code, naam) VALUES (275, 'Rheden');
INSERT INTO gemeente (code, naam) VALUES (340, 'Rhenen');
INSERT INTO gemeente (code, naam) VALUES (597, 'Ridderkerk');
INSERT INTO gemeente (code, naam) VALUES (1742, 'Rijssen-Holten');
INSERT INTO gemeente (code, naam) VALUES (603, 'Rijswijk');
INSERT INTO gemeente (code, naam) VALUES (1669, 'Roerdalen');
INSERT INTO gemeente (code, naam) VALUES (957, 'Roermond');
INSERT INTO gemeente (code, naam) VALUES (736, 'De Ronde Venen');
INSERT INTO gemeente (code, naam) VALUES (1674, 'Roosendaal');
INSERT INTO gemeente (code, naam) VALUES (599, 'Rotterdam');
INSERT INTO gemeente (code, naam) VALUES (277, 'Rozendaal');
INSERT INTO gemeente (code, naam) VALUES (840, 'Rucphen');
INSERT INTO gemeente (code, naam) VALUES (441, 'Schagen');
INSERT INTO gemeente (code, naam) VALUES (279, 'Scherpenzeel');
INSERT INTO gemeente (code, naam) VALUES (606, 'Schiedam');
INSERT INTO gemeente (code, naam) VALUES (88, 'Schiermonnikoog');
INSERT INTO gemeente (code, naam) VALUES (1676, 'Schouwen-Duiveland');
INSERT INTO gemeente (code, naam) VALUES (965, 'Simpelveld');
INSERT INTO gemeente (code, naam) VALUES (845, 'Sint-Michielsgestel');
INSERT INTO gemeente (code, naam) VALUES (1883, 'Sittard-Geleen');
INSERT INTO gemeente (code, naam) VALUES (610, 'Sliedrecht');
INSERT INTO gemeente (code, naam) VALUES (1714, 'Sluis');
INSERT INTO gemeente (code, naam) VALUES (90, 'Smallingerland');
INSERT INTO gemeente (code, naam) VALUES (342, 'Soest');
INSERT INTO gemeente (code, naam) VALUES (847, 'Someren');
INSERT INTO gemeente (code, naam) VALUES (848, 'Son en Breugel');
INSERT INTO gemeente (code, naam) VALUES (37, 'Stadskanaal');
INSERT INTO gemeente (code, naam) VALUES (180, 'Staphorst');
INSERT INTO gemeente (code, naam) VALUES (532, 'Stede Broec');
INSERT INTO gemeente (code, naam) VALUES (851, 'Steenbergen');
INSERT INTO gemeente (code, naam) VALUES (1708, 'Steenwijkerland');
INSERT INTO gemeente (code, naam) VALUES (971, 'Stein');
INSERT INTO gemeente (code, naam) VALUES (1904, 'Stichtse Vecht');
INSERT INTO gemeente (code, naam) VALUES (1900, 'Súdwest-Fryslân');
INSERT INTO gemeente (code, naam) VALUES (715, 'Terneuzen');
INSERT INTO gemeente (code, naam) VALUES (93, 'Terschelling');
INSERT INTO gemeente (code, naam) VALUES (448, 'Texel');
INSERT INTO gemeente (code, naam) VALUES (1525, 'Teylingen');
INSERT INTO gemeente (code, naam) VALUES (716, 'Tholen');
INSERT INTO gemeente (code, naam) VALUES (281, 'Tiel');
INSERT INTO gemeente (code, naam) VALUES (855, 'Tilburg');
INSERT INTO gemeente (code, naam) VALUES (183, 'Tubbergen');
INSERT INTO gemeente (code, naam) VALUES (1700, 'Twenterand');
INSERT INTO gemeente (code, naam) VALUES (1730, 'Tynaarlo');
INSERT INTO gemeente (code, naam) VALUES (737, 'Tytsjerksteradiel');
INSERT INTO gemeente (code, naam) VALUES (450, 'Uitgeest');
INSERT INTO gemeente (code, naam) VALUES (451, 'Uithoorn');
INSERT INTO gemeente (code, naam) VALUES (184, 'Urk');
INSERT INTO gemeente (code, naam) VALUES (344, 'Utrecht');
INSERT INTO gemeente (code, naam) VALUES (1581, 'Utrechtse Heuvelrug');
INSERT INTO gemeente (code, naam) VALUES (981, 'Vaals');
INSERT INTO gemeente (code, naam) VALUES (994, 'Valkenburg aan de Geul');
INSERT INTO gemeente (code, naam) VALUES (858, 'Valkenswaard');
INSERT INTO gemeente (code, naam) VALUES (47, 'Veendam');
INSERT INTO gemeente (code, naam) VALUES (345, 'Veenendaal');
INSERT INTO gemeente (code, naam) VALUES (717, 'Veere');
INSERT INTO gemeente (code, naam) VALUES (861, 'Veldhoven');
INSERT INTO gemeente (code, naam) VALUES (453, 'Velsen');
INSERT INTO gemeente (code, naam) VALUES (983, 'Venlo');
INSERT INTO gemeente (code, naam) VALUES (984, 'Venray');
INSERT INTO gemeente (code, naam) VALUES (1961, 'Vijfheerenlanden');
INSERT INTO gemeente (code, naam) VALUES (622, 'Vlaardingen');
INSERT INTO gemeente (code, naam) VALUES (96, 'Vlieland');
INSERT INTO gemeente (code, naam) VALUES (718, 'Vlissingen');
INSERT INTO gemeente (code, naam) VALUES (986, 'Voerendaal');
INSERT INTO gemeente (code, naam) VALUES (626, 'Voorschoten');
INSERT INTO gemeente (code, naam) VALUES (285, 'Voorst');
INSERT INTO gemeente (code, naam) VALUES (865, 'Vught');
INSERT INTO gemeente (code, naam) VALUES (1949, 'Waadhoeke');
INSERT INTO gemeente (code, naam) VALUES (866, 'Waalre');
INSERT INTO gemeente (code, naam) VALUES (867, 'Waalwijk');
INSERT INTO gemeente (code, naam) VALUES (627, 'Waddinxveen');
INSERT INTO gemeente (code, naam) VALUES (289, 'Wageningen');
INSERT INTO gemeente (code, naam) VALUES (629, 'Wassenaar');
INSERT INTO gemeente (code, naam) VALUES (852, 'Waterland');
INSERT INTO gemeente (code, naam) VALUES (988, 'Weert');
INSERT INTO gemeente (code, naam) VALUES (1960, 'West Betuwe');
INSERT INTO gemeente (code, naam) VALUES (668, 'West Maas en Waal');
INSERT INTO gemeente (code, naam) VALUES (1969, 'Westerkwartier');
INSERT INTO gemeente (code, naam) VALUES (1701, 'Westerveld');
INSERT INTO gemeente (code, naam) VALUES (293, 'Westervoort');
INSERT INTO gemeente (code, naam) VALUES (1950, 'Westerwolde');
INSERT INTO gemeente (code, naam) VALUES (1783, 'Westland');
INSERT INTO gemeente (code, naam) VALUES (98, 'Weststellingwerf');
INSERT INTO gemeente (code, naam) VALUES (614, 'Westvoorne');
INSERT INTO gemeente (code, naam) VALUES (189, 'Wierden');
INSERT INTO gemeente (code, naam) VALUES (296, 'Wijchen');
INSERT INTO gemeente (code, naam) VALUES (1696, 'Wijdemeren');
INSERT INTO gemeente (code, naam) VALUES (352, 'Wijk bij Duurstede');
INSERT INTO gemeente (code, naam) VALUES (294, 'Winterswijk');
INSERT INTO gemeente (code, naam) VALUES (873, 'Woensdrecht');
INSERT INTO gemeente (code, naam) VALUES (632, 'Woerden');
INSERT INTO gemeente (code, naam) VALUES (1690, 'De Wolden');
INSERT INTO gemeente (code, naam) VALUES (880, 'Wormerland');
INSERT INTO gemeente (code, naam) VALUES (351, 'Woudenberg');
INSERT INTO gemeente (code, naam) VALUES (479, 'Zaanstad');
INSERT INTO gemeente (code, naam) VALUES (297, 'Zaltbommel');
INSERT INTO gemeente (code, naam) VALUES (473, 'Zandvoort');
INSERT INTO gemeente (code, naam) VALUES (50, 'Zeewolde');
INSERT INTO gemeente (code, naam) VALUES (355, 'Zeist');
INSERT INTO gemeente (code, naam) VALUES (299, 'Zevenaar');
INSERT INTO gemeente (code, naam) VALUES (637, 'Zoetermeer');
INSERT INTO gemeente (code, naam) VALUES (638, 'Zoeterwoude');
INSERT INTO gemeente (code, naam) VALUES (1892, 'Zuidplas');
INSERT INTO gemeente (code, naam) VALUES (879, 'Zundert');
INSERT INTO gemeente (code, naam) VALUES (301, 'Zutphen');
INSERT INTO gemeente (code, naam) VALUES (1896, 'Zwartewaterland');
INSERT INTO gemeente (code, naam) VALUES (642, 'Zwijndrecht');
INSERT INTO gemeente (code, naam) VALUES (193, 'Zwolle');
INSERT INTO gemeente (code, naam) VALUES (1979, 'Eemsdelta');
INSERT INTO gemeente (dat_beg_geldh, code, naam) VALUES ('2022-01-01', 1980, 'Dijk en Waard');
INSERT INTO gemeente (dat_beg_geldh, code, naam) VALUES ('2022-01-01', 1991, 'Maashorst');
INSERT INTO gemeente (dat_beg_geldh, code, naam) VALUES ('2022-01-01', 1982, 'Land van Cuijk');
