--snijdt alle banden tussen BAG en andere BRs door
--zodat BAG verwijderd en weer opnieuw geladen kan worden
ALTER TABLE ADDRESSEERB_OBJ_AAND DROP CONSTRAINT FK_AOA_AS_6;
ALTER TABLE BENOEMD_OBJ_KAD_ONRRND_ZK DROP CONSTRAINT FK_TGO_KOZ_NN_LH;
ALTER TABLE ANDER_NAT_PRS DROP CONSTRAINT FK_ANP_AS_3;
ALTER TABLE BEGR_TERR_DL DROP CONSTRAINT FK_BTD_AS_8;
ALTER TABLE GEM_OPENB_RMTE DROP CONSTRAINT FK_GOR_AS_7;
ALTER TABLE HUISHOUDEN DROP CONSTRAINT FK_HHD_AS_5;
ALTER TABLE HUISHOUDEN DROP CONSTRAINT FK_HHD_AS_7;
ALTER TABLE HUISHOUDEN DROP CONSTRAINT FK_HHD_AS_4;
ALTER TABLE INGESCHR_NAT_PRS DROP CONSTRAINT FK_INP_AS_27;
ALTER TABLE INGESCHR_NAT_PRS DROP CONSTRAINT FK_INP_VA_AS_7;
ALTER TABLE INGESCHR_NAT_PRS DROP CONSTRAINT FK_INP_AS_28;
ALTER TABLE INGESCHR_NAT_PRS DROP CONSTRAINT FK_INP_VA_AS_5;
ALTER TABLE INGESCHR_NAT_PRS DROP CONSTRAINT FK_INP_AS_29;
ALTER TABLE INGESCHR_NAT_PRS DROP CONSTRAINT FK_INP_VA_AS_4;
ALTER TABLE INGESCHR_NAT_PRS DROP CONSTRAINT FK_INP_AS_30;
ALTER TABLE INGESCHR_NAT_PRS DROP CONSTRAINT FK_INP_VA_AS_3;
ALTER TABLE INGESCHR_NAT_PRS DROP CONSTRAINT FK_INP_AS_31;
ALTER TABLE INGESCHR_NAT_PRS DROP CONSTRAINT FK_INP_VA_AS_6;
ALTER TABLE INGESCHR_NIET_NAT_PRS DROP CONSTRAINT FK_INN_AS_8;
ALTER TABLE LOCAAND_ADRES DROP CONSTRAINT FK_LOCAAND_ADRES_SC_LH;
ALTER TABLE ONBEGR_TERR_DL DROP CONSTRAINT FK_OBT_AS_8;
ALTER TABLE ONDERSTEUNEND_WEGDEEL DROP CONSTRAINT FK_OWD_AS_6;
ALTER TABLE SUBJECT DROP CONSTRAINT FK_SUB_AS_14;
ALTER TABLE SUBJECT DROP CONSTRAINT FK_SUB_AS_15;
ALTER TABLE SUBJECT DROP CONSTRAINT FK_SUB_AS_13;
ALTER TABLE SUBJECT DROP CONSTRAINT FK_SUB_PA_AS_4;
ALTER TABLE VESTG DROP CONSTRAINT FK_VES_AS_16;
ALTER TABLE VESTG DROP CONSTRAINT FK_VES_AS_20;
ALTER TABLE VESTG DROP CONSTRAINT FK_VES_SC;
ALTER TABLE VESTG_BENOEMD_OBJ DROP CONSTRAINT FK_VES_TGO_NN_RH;
ALTER TABLE WATERDEEL DROP CONSTRAINT FK_WAD_AS_7;
ALTER TABLE WEGDEEL DROP CONSTRAINT FK_WGD_AS_8;
ALTER TABLE WOZ_DEELOBJ DROP CONSTRAINT FK_WDO_AS_5;
ALTER TABLE WOZ_DEELOBJ DROP CONSTRAINT FK_WDO_AS_4;

-- zet fk constraint om niet cascade delete naar woonplaats te doen
ALTER TABLE OPENB_RMTE_WNPLTS DROP CONSTRAINT FK_OPR_WPL_NN_RH;
ALTER TABLE OPENB_RMTE_WNPLTS ADD CONSTRAINT FK_OPR_WPL_NN_RH FOREIGN KEY (FK_NN_RH_WPL_IDENTIF) REFERENCES WNPLTS (IDENTIF);
ALTER TABLE WNPLTS DROP CONSTRAINT FK_WPL_AS_7;
ALTER TABLE WNPLTS ADD CONSTRAINT FK_WPL_AS_7 FOREIGN KEY (FK_7GEM_CODE) REFERENCES GEMEENTE (CODE);

-- Referentielijst niet gevuld
ALTER TABLE ZAK_RECHT DROP CONSTRAINT FK_ZKR_RL_3;

-- Rechterkant mogelijk nog niet geinsert
ALTER TABLE KAD_ONRRND_ZK_HIS_REL DROP CONSTRAINT FK_KAD_ONRRND_ZK_HIS_REL_SC_RH;
