CREATE INDEX ZAK_RECHT_FK_KAD_IDENTIF_IDX ON ZAK_RECHT (FK_7KOZ_KAD_IDENTIF);
CREATE INDEX KAD_ONRRND_ZK_AANTEK_FK4_IDX ON KAD_ONRRND_ZK_AANTEK (FK_4KOZ_KAD_IDENTIF);
CREATE INDEX KAD_PERCEEL_ID_IDX ON KAD_PERCEEL (KA_KAD_GEMEENTECODE, KA_SECTIE, KA_PERCEELNUMMER);
CREATE INDEX ZAK_RECHT_AANTEK_FK5_ZK_RE_IDX ON ZAK_RECHT_AANTEK (FK_5ZKR_KADASTER_IDENTIF);
