-- voeg kolommen toe aan tabel woz_obj
ALTER TABLE WOZ_OBJ ADD WATERSCHAP VARCHAR2(4);
ALTER TABLE WOZ_OBJ ADD FK_VERANTW_GEM_CODE NUMERIC(4,0);
-- omdat testdata ongeldige waarden bevat vooralsnog geen constraint afdwingen voor gemeente
-- ALTER TABLE WOZ_OBJ ADD CONSTRAINT FK_GEM_CODE FOREIGN KEY (FK_VERANTW_GEM_CODE) REFERENCES GEMEENTE(CODE) ON DELETE NO ACTION;
COMMENT ON COLUMN WOZ_OBJ.WATERSCHAP IS 'ligt in waterschap (niet-RSGB)';
COMMENT ON COLUMN WOZ_OBJ.FK_VERANTW_GEM_CODE IS 'verantwoordelijke gemeente (niet-RSGB)';

ALTER TABLE WOZ_OBJ_ARCHIEF ADD WATERSCHAP VARCHAR2(4);
ALTER TABLE WOZ_OBJ_ARCHIEF ADD FK_VERANTW_GEM_CODE NUMERIC(4,0);
COMMENT ON COLUMN WOZ_OBJ_ARCHIEF.WATERSCHAP IS 'ligt in waterschap (niet-RSGB)';
COMMENT ON COLUMN WOZ_OBJ_ARCHIEF.FK_VERANTW_GEM_CODE IS 'verantwoordelijke gemeente (niet-RSGB)';

-- koppeltabel voor onroerende zaak
CREATE TABLE WOZ_OMVAT (
    FK_SC_LH_KAD_IDENTIF NUMBER(15,0) NOT NULL,
    FK_SC_RH_WOZ_NUMMER NUMBER(12,0) NOT NULL,
    TOEGEKENDE_OPP NUMBER(11,0) NULL,
    CONSTRAINT WOZ_OMVAT_PK PRIMARY KEY (FK_SC_LH_KAD_IDENTIF, FK_SC_RH_WOZ_NUMMER)
);
-- geen harde binding tussen WOZ en BRK maken
-- ALTER TABLE WOZ_OMVAT ADD CONSTRAINT FK_WOZ_OMVAT_SC_LH FOREIGN KEY (FK_SC_LH_KAD_IDENTIF) REFERENCES KAD_ONRRND_ZK (KAD_IDENTIF) ON DELETE CASCADE;
ALTER TABLE WOZ_OMVAT ADD CONSTRAINT FK_WOZ_OMVAT_SC_RH FOREIGN KEY (FK_SC_RH_WOZ_NUMMER) REFERENCES WOZ_OBJ (NUMMER) ON DELETE CASCADE;

COMMENT ON COLUMN WOZ_OMVAT.FK_SC_LH_KAD_IDENTIF IS '[FK] N15, FK naar kad_onrrnd_zk.kad_identif';
COMMENT ON COLUMN WOZ_OMVAT.FK_SC_RH_WOZ_NUMMER IS '[FK] N12, FK naar woz_obj.nummer';
COMMENT ON COLUMN WOZ_OMVAT.TOEGEKENDE_OPP IS 'N12, toegekende oppervlakte';
