timestamps {
    node {
        properties([
            [$class: 'jenkins.model.BuildDiscarderProperty', strategy: [$class: 'LogRotator',
                artifactDaysToKeepStr: '8',
                artifactNumToKeepStr: '3',
                daysToKeepStr: '15',
                numToKeepStr: '5']
            ]]);

        stage('Prepare') {
            checkout scm
        }

        withEnv(["JAVA_HOME=${ tool JDK8 }", "PATH+MAVEN=${tool 'Maven CURRENT'}/bin:${env.JAVA_HOME}/bin"]) {
            lock('rsgb-p8') {
                timeout(90) {
                    stage("P8 datamodel Integration Test") {
                        sh "mvn -e verify -B -Pp8 -T1 -pl 'datamodel'
                    }
                }
            }
        }

        stage('Publish Results') {
            junit allowEmptyResults: true, testResults: '**/target/surefire-reports/TEST-*.xml, **/target/failsafe-reports/TEST-*.xml'
        }

        stage('Publish Test Coverage') {
            jacoco exclusionPattern: '**/*Test.class', execPattern: '**/target/**.exec'
            sh "curl -s https://codecov.io/bash | bash"
        }

        cleanWs cleanWhenFailure: false, cleanWhenNotBuilt: false, cleanWhenUnstable: false, notFailBuild: true
    }
}
