BEGIN
    FOR t IN (SELECT * FROM USER_TABLES)
    LOOP
        EXECUTE IMMEDIATE 'GRANT SELECT, UPDATE, INSERT, DELETE ON ' || t.table_name || ' TO C##JENKINS_TOPNL';
    END LOOP;
END;
/

BEGIN
    FOR t IN (SELECT * FROM USER_SEQUENCES)
    LOOP
        EXECUTE IMMEDIATE 'GRANT SELECT ON ' || t.sequence_name || ' TO C##JENKINS_TOPNL';
    END LOOP;
END;
/
