-- Transformeer alle metadata van geometrieen in de tabellen van de RSGB database
--    van 90112 (Oracle Rijksdriehoek identifier)
--    naar 28992 (EPSG Rijksdriehoek identifier)
-- tbv. update/migratie BRMO 1.2.10 naar 1.2.11
--
UPDATE USER_SDO_GEOM_METADATA SET SRID=28992 WHERE srid=90112;
--
-- Transformeer alle geometrieen in de tabellen van de RSGB database 
--    van 90112 (Oracle Rijksdriehoek identifier) 
--    naar 28992 (EPSG Rijksdriehoek identifier)
-- tbv. update/migratie BRMO 1.2.10 naar 1.2.11
--
-- (her-)genereer onderstaand deel script eventueel met:
--    SELECT 
--    'UPDATE ' || TABLE_NAME || ' t ' || 'SET t.'||COLUMN_NAME||'.SDO_SRID = 28992 WHERE t.' ||COLUMN_NAME||' IS NOT NULL;' AS transform
--    FROM USER_TAB_COLUMNS WHERE DATA_TYPE = 'SDO_GEOMETRY';
--
UPDATE BEGR_TERR_DL t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE BEGR_TERR_DL t SET t.KRUINLIJNGEOM.SDO_SRID = 28992 WHERE t.KRUINLIJNGEOM IS NOT NULL;
UPDATE BEGR_TERR_DL_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE BEGR_TERR_DL_ARCHIEF t SET t.KRUINLIJNGEOM.SDO_SRID = 28992 WHERE t.KRUINLIJNGEOM IS NOT NULL;
UPDATE BENOEMD_TERREIN t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE BENOEMD_TERREIN_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE BUURT t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE BUURT_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE FUNCTIONEEL_GEBIED t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE FUNCTIONEEL_GEBIED_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE GEBOUWD_OBJ t SET t.PUNTGEOM.SDO_SRID = 28992 WHERE t.PUNTGEOM IS NOT NULL;
UPDATE GEBOUWD_OBJ t SET t.VLAKGEOM.SDO_SRID = 28992 WHERE t.VLAKGEOM IS NOT NULL;
UPDATE GEBOUWD_OBJ_ARCHIEF t SET t.VLAKGEOM.SDO_SRID = 28992 WHERE t.VLAKGEOM IS NOT NULL;
UPDATE GEBOUWD_OBJ_ARCHIEF t SET t.PUNTGEOM.SDO_SRID = 28992 WHERE t.PUNTGEOM IS NOT NULL;
UPDATE GEBOUWINSTALLATIE t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE GEBOUWINSTALLATIE_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE GEMEENTE t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE GEMEENTE_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE INRICHTINGSELEMENT t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE INRICHTINGSELEMENT_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE KAD_PERCEEL t SET t.BEGRENZING_PERCEEL.SDO_SRID = 28992 WHERE t.BEGRENZING_PERCEEL IS NOT NULL;
UPDATE KAD_PERCEEL t SET t.PLAATSCOORDINATEN_PERCEEL.SDO_SRID = 28992 WHERE t.PLAATSCOORDINATEN_PERCEEL IS NOT NULL;
UPDATE KAD_PERCEEL_ARCHIEF t SET t.BEGRENZING_PERCEEL.SDO_SRID = 28992 WHERE t.BEGRENZING_PERCEEL IS NOT NULL;
UPDATE KAD_PERCEEL_ARCHIEF t SET t.PLAATSCOORDINATEN_PERCEEL.SDO_SRID = 28992 WHERE t.PLAATSCOORDINATEN_PERCEEL IS NOT NULL;
UPDATE KUNSTWERKDEEL t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE KUNSTWERKDEEL_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE ONBEGR_TERR_DL t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE ONBEGR_TERR_DL t SET t.KRUINLIJNGEOM.SDO_SRID = 28992 WHERE t.KRUINLIJNGEOM IS NOT NULL;
UPDATE ONBEGR_TERR_DL_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE ONBEGR_TERR_DL_ARCHIEF t SET t.KRUINLIJNGEOM.SDO_SRID = 28992 WHERE t.KRUINLIJNGEOM IS NOT NULL;
UPDATE ONDERSTEUNEND_WEGDEEL t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE ONDERSTEUNEND_WEGDEEL_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE OVERIG_BOUWWERK t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE OVERIG_BOUWWERK_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE OVRG_SCHEIDING t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE OVRG_SCHEIDING_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE PAND t SET t.GEOM_BOVENAANZICHT.SDO_SRID = 28992 WHERE t.GEOM_BOVENAANZICHT IS NOT NULL;
UPDATE PAND t SET t.GEOM_MAAIVELD.SDO_SRID = 28992 WHERE t.GEOM_MAAIVELD IS NOT NULL;
UPDATE PAND_ARCHIEF t SET t.GEOM_BOVENAANZICHT.SDO_SRID = 28992 WHERE t.GEOM_BOVENAANZICHT IS NOT NULL;
UPDATE PAND_ARCHIEF t SET t.GEOM_MAAIVELD.SDO_SRID = 28992 WHERE t.GEOM_MAAIVELD IS NOT NULL;
UPDATE SCHEIDING t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE SCHEIDING_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE SPOOR t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE SPOOR_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE STADSDEEL t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE STADSDEEL_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE VRIJSTAAND_VEGETATIE_OBJ t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE VRIJSTAAND_VEGETATIE_O_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE WATERDEEL t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE WATERDEEL_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE WATERSCHAP t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE WATERSCHAP_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE WEGDEEL t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE WEGDEEL_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE WIJK t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE WIJK_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE WNPLTS t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE WNPLTS_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE WOZ_OBJ t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
UPDATE WOZ_OBJ_ARCHIEF t SET t.GEOM.SDO_SRID = 28992 WHERE t.GEOM IS NOT NULL;
