//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.08 at 04:32:51 PM CET 
//


package nl.b3p.topnl.top50nl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FysiekVoorkomenWegT50Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FysiekVoorkomenWegT50Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="op vast deel van brug"/>
 *     &lt;enumeration value="op beweegbaar deel van brug"/>
 *     &lt;enumeration value="op knooppuntverbinding"/>
 *     &lt;enumeration value="op oprit / afrit"/>
 *     &lt;enumeration value="op vrijliggende baan"/>
 *     &lt;enumeration value="overkluisd"/>
 *     &lt;enumeration value="in tunnel"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FysiekVoorkomenWegT50Type", namespace = "http://www.kadaster.nl/top50nl/1.1")
@XmlEnum
public enum FysiekVoorkomenWegT50Type {


    /**
     * Gelegen op een niet beweegbaar deel van een kunstwerk dat een verbinding vormt door middel van een overspanning
     * 
     */
    @XmlEnumValue("op vast deel van brug")
    OP_VAST_DEEL_VAN_BRUG("op vast deel van brug"),

    /**
     * Gelegen op een beweegbaar deel van een kunstwerk dat een verbinding vormt door middel van een overspanning
     * 
     */
    @XmlEnumValue("op beweegbaar deel van brug")
    OP_BEWEEGBAAR_DEEL_VAN_BRUG("op beweegbaar deel van brug"),

    /**
     * Gelegen op een verbinding tussen twee wegen op een verkeersknooppunt, zoals een klaverblad
     * 
     */
    @XmlEnumValue("op knooppuntverbinding")
    OP_KNOOPPUNTVERBINDING("op knooppuntverbinding"),

    /**
     * Gelegen op een oprit of afrit van een auto(snel)weg
     * 
     */
    @XmlEnumValue("op oprit / afrit")
    OP_OPRIT_AFRIT("op oprit / afrit"),

    /**
     * Gelegen op een vrijliggende baan
     * 
     */
    @XmlEnumValue("op vrijliggende baan")
    OP_VRIJLIGGENDE_BAAN("op vrijliggende baan"),

    /**
     * Overbouwd door gebouwen, zodanig dat de orthogonale projectie van de gebouwen op of over het object valt
     * 
     */
    @XmlEnumValue("overkluisd")
    OVERKLUISD("overkluisd"),

    /**
     * Gelegen in een kunstmatig aangelegde, onderaardse of door een berg geboorde kokervormige doorgang
     * 
     */
    @XmlEnumValue("in tunnel")
    IN_TUNNEL("in tunnel");
    private final String value;

    FysiekVoorkomenWegT50Type(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FysiekVoorkomenWegT50Type fromValue(String v) {
        for (FysiekVoorkomenWegT50Type c: FysiekVoorkomenWegT50Type.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
