//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.08 at 04:32:51 PM CET 
//


package nl.b3p.topnl.top50nl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for GebouwType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GebouwType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.kadaster.nl/top50nl/1.1}_Top50nlObjectType">
 *       &lt;sequence>
 *         &lt;element name="fysiekVoorkomen" type="{http://www.kadaster.nl/top50nl/1.1}FysiekVoorkomenGebouwT50Type" minOccurs="0"/>
 *         &lt;element name="geometrie" type="{http://www.kadaster.nl/top50nl/1.1}VlakOfPuntPropertyType"/>
 *         &lt;element name="hoogte" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="hoogteklasse" type="{http://www.kadaster.nl/top50nl/1.1}HoogteklasseGebouwT50Type"/>
 *         &lt;element name="naamFries" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="naamNL" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="typeGebouw" type="{http://www.kadaster.nl/top50nl/1.1}TypeGebouwT50Type" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GebouwType", namespace = "http://www.kadaster.nl/top50nl/1.1", propOrder = {
    "fysiekVoorkomen",
    "geometrie",
    "hoogte",
    "hoogteklasse",
    "naamFries",
    "naamNL",
    "typeGebouw"
})
public class GebouwType
    extends Top50NlObjectType
{

    @XmlSchemaType(name = "string")
    protected FysiekVoorkomenGebouwT50Type fysiekVoorkomen;
    @XmlAnyElement
    protected Element geometrie;
    protected Double hoogte;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected HoogteklasseGebouwT50Type hoogteklasse;
    protected List<String> naamFries;
    protected List<String> naamNL;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected List<TypeGebouwT50Type> typeGebouw;

    /**
     * Gets the value of the fysiekVoorkomen property.
     * 
     * @return
     *     possible object is
     *     {@link FysiekVoorkomenGebouwT50Type }
     *     
     */
    public FysiekVoorkomenGebouwT50Type getFysiekVoorkomen() {
        return fysiekVoorkomen;
    }

    /**
     * Sets the value of the fysiekVoorkomen property.
     * 
     * @param value
     *     allowed object is
     *     {@link FysiekVoorkomenGebouwT50Type }
     *     
     */
    public void setFysiekVoorkomen(FysiekVoorkomenGebouwT50Type value) {
        this.fysiekVoorkomen = value;
    }

    /**
     * Gets the value of the geometrie property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     
     */
    public Element getGeometrie() {
        return geometrie;
    }

    /**
     * Sets the value of the geometrie property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     
     */
    public void setGeometrie(Element value) {
        this.geometrie = value;
    }

    /**
     * Gets the value of the hoogte property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getHoogte() {
        return hoogte;
    }

    /**
     * Sets the value of the hoogte property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setHoogte(Double value) {
        this.hoogte = value;
    }

    /**
     * Gets the value of the hoogteklasse property.
     * 
     * @return
     *     possible object is
     *     {@link HoogteklasseGebouwT50Type }
     *     
     */
    public HoogteklasseGebouwT50Type getHoogteklasse() {
        return hoogteklasse;
    }

    /**
     * Sets the value of the hoogteklasse property.
     * 
     * @param value
     *     allowed object is
     *     {@link HoogteklasseGebouwT50Type }
     *     
     */
    public void setHoogteklasse(HoogteklasseGebouwT50Type value) {
        this.hoogteklasse = value;
    }

    /**
     * Gets the value of the naamFries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the naamFries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNaamFries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNaamFries() {
        if (naamFries == null) {
            naamFries = new ArrayList<String>();
        }
        return this.naamFries;
    }

    /**
     * Gets the value of the naamNL property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the naamNL property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNaamNL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNaamNL() {
        if (naamNL == null) {
            naamNL = new ArrayList<String>();
        }
        return this.naamNL;
    }

    /**
     * Gets the value of the typeGebouw property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the typeGebouw property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypeGebouw().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeGebouwT50Type }
     * 
     * 
     */
    public List<TypeGebouwT50Type> getTypeGebouw() {
        if (typeGebouw == null) {
            typeGebouw = new ArrayList<TypeGebouwT50Type>();
        }
        return this.typeGebouw;
    }

}
