//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.08 at 04:32:51 PM CET 
//


package nl.b3p.topnl.top50nl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeFunctioneelGebiedT50Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TypeFunctioneelGebiedT50Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="arboretum"/>
 *     &lt;enumeration value="bedrijventerrein"/>
 *     &lt;enumeration value="begraafplaats"/>
 *     &lt;enumeration value="bungalowpark"/>
 *     &lt;enumeration value="camping, kampeerterrein"/>
 *     &lt;enumeration value="circuit"/>
 *     &lt;enumeration value="crossbaan"/>
 *     &lt;enumeration value="dierentuin, safaripark"/>
 *     &lt;enumeration value="emplacement"/>
 *     &lt;enumeration value="erebegraafplaats"/>
 *     &lt;enumeration value="gaswinning"/>
 *     &lt;enumeration value="groeve"/>
 *     &lt;enumeration value="haven"/>
 *     &lt;enumeration value="heemtuin"/>
 *     &lt;enumeration value="helikopterlandingsterrein"/>
 *     &lt;enumeration value="jachthaven"/>
 *     &lt;enumeration value="mijn"/>
 *     &lt;enumeration value="militair oefengebied, schietterrein"/>
 *     &lt;enumeration value="mosselbank"/>
 *     &lt;enumeration value="natuurgebied, natuurreservaat"/>
 *     &lt;enumeration value="oliewinning"/>
 *     &lt;enumeration value="openluchtmuseum"/>
 *     &lt;enumeration value="openluchttheater"/>
 *     &lt;enumeration value="park"/>
 *     &lt;enumeration value="pinetum"/>
 *     &lt;enumeration value="productie-installatie"/>
 *     &lt;enumeration value="recreatiegebied"/>
 *     &lt;enumeration value="renbaan"/>
 *     &lt;enumeration value="skibaan"/>
 *     &lt;enumeration value="sluizencomplex"/>
 *     &lt;enumeration value="sportterrein, sportcomplex"/>
 *     &lt;enumeration value="stortplaats"/>
 *     &lt;enumeration value="tennispark"/>
 *     &lt;enumeration value="verzorgingsplaats"/>
 *     &lt;enumeration value="vliegveld, luchthaven"/>
 *     &lt;enumeration value="volkstuinen"/>
 *     &lt;enumeration value="wildwissel"/>
 *     &lt;enumeration value="windturbinepark"/>
 *     &lt;enumeration value="woonwagencentrum"/>
 *     &lt;enumeration value="zandwinning"/>
 *     &lt;enumeration value="zenderpark"/>
 *     &lt;enumeration value="zoutwinning"/>
 *     &lt;enumeration value="zuiveringsinstallatie"/>
 *     &lt;enumeration value="zweefvliegveldterrein"/>
 *     &lt;enumeration value="ijsbaan"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TypeFunctioneelGebiedT50Type", namespace = "http://www.kadaster.nl/top50nl/1.1")
@XmlEnum
public enum TypeFunctioneelGebiedT50Type {

    @XmlEnumValue("arboretum")
    ARBORETUM("arboretum"),
    @XmlEnumValue("bedrijventerrein")
    BEDRIJVENTERREIN("bedrijventerrein"),
    @XmlEnumValue("begraafplaats")
    BEGRAAFPLAATS("begraafplaats"),
    @XmlEnumValue("bungalowpark")
    BUNGALOWPARK("bungalowpark"),
    @XmlEnumValue("camping, kampeerterrein")
    CAMPING_KAMPEERTERREIN("camping, kampeerterrein"),
    @XmlEnumValue("circuit")
    CIRCUIT("circuit"),
    @XmlEnumValue("crossbaan")
    CROSSBAAN("crossbaan"),
    @XmlEnumValue("dierentuin, safaripark")
    DIERENTUIN_SAFARIPARK("dierentuin, safaripark"),
    @XmlEnumValue("emplacement")
    EMPLACEMENT("emplacement"),
    @XmlEnumValue("erebegraafplaats")
    EREBEGRAAFPLAATS("erebegraafplaats"),
    @XmlEnumValue("gaswinning")
    GASWINNING("gaswinning"),
    @XmlEnumValue("groeve")
    GROEVE("groeve"),
    @XmlEnumValue("haven")
    HAVEN("haven"),
    @XmlEnumValue("heemtuin")
    HEEMTUIN("heemtuin"),
    @XmlEnumValue("helikopterlandingsterrein")
    HELIKOPTERLANDINGSTERREIN("helikopterlandingsterrein"),
    @XmlEnumValue("jachthaven")
    JACHTHAVEN("jachthaven"),
    @XmlEnumValue("mijn")
    MIJN("mijn"),
    @XmlEnumValue("militair oefengebied, schietterrein")
    MILITAIR_OEFENGEBIED_SCHIETTERREIN("militair oefengebied, schietterrein"),
    @XmlEnumValue("mosselbank")
    MOSSELBANK("mosselbank"),
    @XmlEnumValue("natuurgebied, natuurreservaat")
    NATUURGEBIED_NATUURRESERVAAT("natuurgebied, natuurreservaat"),
    @XmlEnumValue("oliewinning")
    OLIEWINNING("oliewinning"),
    @XmlEnumValue("openluchtmuseum")
    OPENLUCHTMUSEUM("openluchtmuseum"),
    @XmlEnumValue("openluchttheater")
    OPENLUCHTTHEATER("openluchttheater"),
    @XmlEnumValue("park")
    PARK("park"),
    @XmlEnumValue("pinetum")
    PINETUM("pinetum"),
    @XmlEnumValue("productie-installatie")
    PRODUCTIE_INSTALLATIE("productie-installatie"),
    @XmlEnumValue("recreatiegebied")
    RECREATIEGEBIED("recreatiegebied"),
    @XmlEnumValue("renbaan")
    RENBAAN("renbaan"),
    @XmlEnumValue("skibaan")
    SKIBAAN("skibaan"),
    @XmlEnumValue("sluizencomplex")
    SLUIZENCOMPLEX("sluizencomplex"),
    @XmlEnumValue("sportterrein, sportcomplex")
    SPORTTERREIN_SPORTCOMPLEX("sportterrein, sportcomplex"),
    @XmlEnumValue("stortplaats")
    STORTPLAATS("stortplaats"),
    @XmlEnumValue("tennispark")
    TENNISPARK("tennispark"),
    @XmlEnumValue("verzorgingsplaats")
    VERZORGINGSPLAATS("verzorgingsplaats"),
    @XmlEnumValue("vliegveld, luchthaven")
    VLIEGVELD_LUCHTHAVEN("vliegveld, luchthaven"),
    @XmlEnumValue("volkstuinen")
    VOLKSTUINEN("volkstuinen"),
    @XmlEnumValue("wildwissel")
    WILDWISSEL("wildwissel"),
    @XmlEnumValue("windturbinepark")
    WINDTURBINEPARK("windturbinepark"),
    @XmlEnumValue("woonwagencentrum")
    WOONWAGENCENTRUM("woonwagencentrum"),
    @XmlEnumValue("zandwinning")
    ZANDWINNING("zandwinning"),
    @XmlEnumValue("zenderpark")
    ZENDERPARK("zenderpark"),
    @XmlEnumValue("zoutwinning")
    ZOUTWINNING("zoutwinning"),
    @XmlEnumValue("zuiveringsinstallatie")
    ZUIVERINGSINSTALLATIE("zuiveringsinstallatie"),
    @XmlEnumValue("zweefvliegveldterrein")
    ZWEEFVLIEGVELDTERREIN("zweefvliegveldterrein"),
    @XmlEnumValue("ijsbaan")
    IJSBAAN("ijsbaan");
    private final String value;

    TypeFunctioneelGebiedT50Type(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeFunctioneelGebiedT50Type fromValue(String v) {
        for (TypeFunctioneelGebiedT50Type c: TypeFunctioneelGebiedT50Type.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
