//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.08 at 04:32:51 PM CET 
//


package nl.b3p.topnl.top50nl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeWaterT50Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TypeWaterT50Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="waterloop"/>
 *     &lt;enumeration value="meer, plas, ven, vijver"/>
 *     &lt;enumeration value="greppel, droge sloot"/>
 *     &lt;enumeration value="zee"/>
 *     &lt;enumeration value="droogvallend"/>
 *     &lt;enumeration value="bron, wel"/>
 *     &lt;enumeration value="overig"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TypeWaterT50Type", namespace = "http://www.kadaster.nl/top50nl/1.1")
@XmlEnum
public enum TypeWaterT50Type {

    @XmlEnumValue("waterloop")
    WATERLOOP("waterloop"),
    @XmlEnumValue("meer, plas, ven, vijver")
    MEER_PLAS_VEN_VIJVER("meer, plas, ven, vijver"),
    @XmlEnumValue("greppel, droge sloot")
    GREPPEL_DROGE_SLOOT("greppel, droge sloot"),
    @XmlEnumValue("zee")
    ZEE("zee"),
    @XmlEnumValue("droogvallend")
    DROOGVALLEND("droogvallend"),
    @XmlEnumValue("bron, wel")
    BRON_WEL("bron, wel"),
    @XmlEnumValue("overig")
    OVERIG("overig");
    private final String value;

    TypeWaterT50Type(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeWaterT50Type fromValue(String v) {
        for (TypeWaterT50Type c: TypeWaterT50Type.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
