--Pas op, zorg dat constraints tussen bag en andere
--BR gedropt zijn, anders gaat de gehele database
--leeg.
truncate addresseerb_obj_aand;
truncate addresseerb_obj_aand_archief;
truncate benoemd_obj ;
truncate benoemd_terrein;
truncate benoemd_terrein_archief;
truncate benoemd_terrein_benoem_archief;
truncate benoemd_terrein_benoemd_terrei;
truncate gebouwd_obj;
truncate gebouwd_obj_archief;
truncate gebouwd_obj_gebruiksdoel;
truncate gem_openb_rmte;
truncate gem_openb_rmte_archief;
truncate ligplaats;
truncate ligplaats_archief;
truncate ligplaats_nummeraand;
truncate ligplaats_nummeraand_archief;
truncate nummeraand;
truncate nummeraand_archief;
truncate openb_rmte;
truncate openb_rmte_gem_openb_rmte;
truncate openb_rmte_wnplts;
truncate overig_bouwwerk;
truncate overig_bouwwerk_archief;
truncate overig_gebouwd_obj;
truncate overig_gebouwd_obj_archief;
truncate overig_terrein;
truncate overig_terrein_archief;
truncate overig_terrein_gebruiksdoel;
truncate ovrg_addresseerb_obj_a_archief;
truncate ovrg_addresseerb_obj_aand;
truncate pand;
truncate pand_archief;
truncate standplaats;
truncate standplaats_archief;
truncate standplaats_nummeraand;
truncate standplaats_nummeraand_archief;
truncate verblijfsobj;
truncate verblijfsobj_archief;
truncate verblijfsobj_nummeraan_archief;
truncate verblijfsobj_nummeraand;
truncate verblijfsobj_pand;
truncate verblijfsobj_pand_archief;
truncate wnplts;
truncate wnplts_archief;