version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    target_branch: "master"
    default_reviewers:
      - "mprins"
    default_assignees:
      - "mprins"
    default_labels:
      - "bouw- en testinfrastuctuur"
      - "dependency update"
