--
-- upgrade RSGBBGT datamodel van 1.3.6 naar 1.4.0 (Oracle)
--
-- verhelp dubbele records in GT_PK_METADATA tabel (#255)
DELETE FROM GT_PK_METADATA;

CREATE UNIQUE INDEX gt_pk_metadata_table_idx01 ON GT_PK_METADATA (table_schema, table_name, pk_column);

INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'BAK', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'BEGROEID_TERREINDEEL', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'BORD', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'FUNCTIONEELGEBIED', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'GEBOUW_INSTALLATIE', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'INSTALLATIE', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'KAST', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'MAST', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'PAAL', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'PUT', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'SENSOR', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'OPENBARERUIMTELABEL', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'OVERIGE_SCHEIDING', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'SCHEIDING', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'OVERIG_BOUWWERK', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'ONGECLASSIFICEERDOBJECT', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'WATERDEEL', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'KUNSTWERKDEEL', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'ONBEGROEID_TERREINDEEL', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'OVERBRUGGINGSDEEL', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'STRAATMEUBILAIR', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'ONDERSTEUNEND_WATERDEEL', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'ONDERSTEUNEND_WEGDEEL', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'SPOOR', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'WEGINRICHTINGSELEMENT', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'VEGETATIEOBJECT', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'TUNNELDEEL', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'WATERINRICHTINGSELEMENT', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'WEGDEEL', 'IDENTIF', NULL, 'assigned', NULL);
INSERT INTO GT_PK_METADATA VALUES ('RSGBBGT', 'PAND', 'IDENTIF', NULL, 'assigned', NULL);
