version: "3"

volumes:
  pgdata:
  brmo-logs:
  brmo-data:

services:
  db:
    image: postgis/postgis:12-3.0
    environment:
      POSTGRES_PASSWORD: brmo
      POSTGRES_USER: brmo
      POSTGRES_DB: rsgb
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"

  brmo:
    build:
      context: .
    volumes:
      - ./brmo-logs:/usr/local/tomcat/logs
      - ./brmo-data:/opt/brmo-data
    ports:
      - 8080:8080
      - 8009:8009
    restart: on-failure
    env_file:
      - ./env/tomcat
    depends_on:
      - db
    healthcheck:
      test: "curl --fail -s http://localhost:8080/brmo-service/ || exit 1"
      interval: 1m30s
      timeout: 10s
      retries: 3