//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 10:59:49 AM CEST 
//


package nl.b3p.topnl.top250nl;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BRTVlakOfLijnPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BRTVlakOfLijnPropertyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTVlakOfLijn"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BRTVlakOfLijnPropertyType", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0", propOrder = {
    "brtVlakOfLijn"
})
public class BRTVlakOfLijnPropertyType {

    @XmlElement(name = "BRTVlakOfLijn", required = true)
    protected BRTVlakOfLijnType brtVlakOfLijn;

    /**
     * Gets the value of the brtVlakOfLijn property.
     * 
     * @return
     *     possible object is
     *     {@link BRTVlakOfLijnType }
     *     
     */
    public BRTVlakOfLijnType getBRTVlakOfLijn() {
        return brtVlakOfLijn;
    }

    /**
     * Sets the value of the brtVlakOfLijn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BRTVlakOfLijnType }
     *     
     */
    public void setBRTVlakOfLijn(BRTVlakOfLijnType value) {
        this.brtVlakOfLijn = value;
    }

}
