//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 10:59:49 AM CEST 
//


package nl.b3p.topnl.top250nl;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for HoogteType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HoogteType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.1}_Top250nlObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="typeHoogte" type="{http://www.opengis.net/gml/3.2}CodeType"/&gt;
 *         &lt;element name="hoogte" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="referentievlak" type="{http://www.opengis.net/gml/3.2}CodeType"/&gt;
 *         &lt;element name="geometrie" type="{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTLijnOfPuntPropertyType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HoogteType", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.1", propOrder = {
    "typeHoogte",
    "hoogte",
    "referentievlak",
    "geometrie"
})
public class HoogteType
    extends Top250NlObjectType
{

    @XmlElement(required = true)
    protected CodeType typeHoogte;
    protected double hoogte;
    @XmlElement(required = true)
    protected CodeType referentievlak;
    @XmlAnyElement
    protected Element geometrie;

    /**
     * Gets the value of the typeHoogte property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getTypeHoogte() {
        return typeHoogte;
    }

    /**
     * Sets the value of the typeHoogte property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setTypeHoogte(CodeType value) {
        this.typeHoogte = value;
    }

    /**
     * Gets the value of the hoogte property.
     * 
     */
    public double getHoogte() {
        return hoogte;
    }

    /**
     * Sets the value of the hoogte property.
     * 
     */
    public void setHoogte(double value) {
        this.hoogte = value;
    }

    /**
     * Gets the value of the referentievlak property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getReferentievlak() {
        return referentievlak;
    }

    /**
     * Sets the value of the referentievlak property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setReferentievlak(CodeType value) {
        this.referentievlak = value;
    }

    /**
     * Gets the value of the geometrie property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     
     */
    public Element getGeometrie() {
        return geometrie;
    }

    /**
     * Sets the value of the geometrie property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     
     */
    public void setGeometrie(Element value) {
        this.geometrie = value;
    }

}
