//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.08 at 10:18:04 AM CET 
//


package nl.b3p.topnl.top250nl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for TerreinType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TerreinType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.1}_Top250nlObjectType">
 *       &lt;sequence>
 *         &lt;element name="geometrieVlak" type="{http://www.opengis.net/gml/3.2}SurfacePropertyType"/>
 *         &lt;element name="naam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="typeLandgebruik" type="{http://www.opengis.net/gml/3.2}CodeType"/>
 *         &lt;element name="voorkomen" type="{http://www.opengis.net/gml/3.2}CodeType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TerreinType", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.1", propOrder = {
    "geometrieVlak",
    "naam",
    "typeLandgebruik",
    "voorkomen"
})
public class TerreinType
    extends Top250NlObjectType
{

    @XmlAnyElement
    protected Element geometrieVlak;
    protected String naam;
    @XmlElement(required = true)
    protected CodeType typeLandgebruik;
    protected List<CodeType> voorkomen;

    /**
     * Gets the value of the geometrieVlak property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     
     */
    public Element getGeometrieVlak() {
        return geometrieVlak;
    }

    /**
     * Sets the value of the geometrieVlak property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     
     */
    public void setGeometrieVlak(Element value) {
        this.geometrieVlak = value;
    }

    /**
     * Gets the value of the naam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaam() {
        return naam;
    }

    /**
     * Sets the value of the naam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaam(String value) {
        this.naam = value;
    }

    /**
     * Gets the value of the typeLandgebruik property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getTypeLandgebruik() {
        return typeLandgebruik;
    }

    /**
     * Sets the value of the typeLandgebruik property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setTypeLandgebruik(CodeType value) {
        this.typeLandgebruik = value;
    }

    /**
     * Gets the value of the voorkomen property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the voorkomen property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVoorkomen().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getVoorkomen() {
        if (voorkomen == null) {
            voorkomen = new ArrayList<CodeType>();
        }
        return this.voorkomen;
    }

}
