//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 10:59:49 AM CEST 
//


package nl.b3p.topnl.top250nl;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for WegdeelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WegdeelType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.1}_Top250nlObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="typeInfrastructuur" type="{http://www.opengis.net/gml/3.2}CodeType"/&gt;
 *         &lt;element name="typeWeg" type="{http://www.opengis.net/gml/3.2}CodeType"/&gt;
 *         &lt;element name="hoofdverkeersgebruik" type="{http://www.opengis.net/gml/3.2}CodeType"/&gt;
 *         &lt;element name="fysiekVoorkomen" type="{http://www.opengis.net/gml/3.2}CodeType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="verhardingsbreedteklasse" type="{http://www.opengis.net/gml/3.2}CodeType" minOccurs="0"/&gt;
 *         &lt;element name="gescheidenRijbaan" type="{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTJaNeeWaardeType"/&gt;
 *         &lt;element name="verhardingstype" type="{http://www.opengis.net/gml/3.2}CodeType"/&gt;
 *         &lt;element name="aantalRijstroken" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://www.opengis.net/gml/3.2}CodeType"/&gt;
 *         &lt;element name="naam" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="isBAGnaam" type="{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTJaNeeWaardeType" minOccurs="0"/&gt;
 *         &lt;element name="aWegnummer" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="nWegnummer" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="eWegnummer" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="sWegnummer" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="afritnummer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="afritnaam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="knooppuntnaam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="brugnaam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tunnelnaam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="geometrie" type="{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTLijnOfPuntPropertyType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WegdeelType", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.1", propOrder = {
    "typeInfrastructuur",
    "typeWeg",
    "hoofdverkeersgebruik",
    "fysiekVoorkomen",
    "verhardingsbreedteklasse",
    "gescheidenRijbaan",
    "verhardingstype",
    "aantalRijstroken",
    "status",
    "naam",
    "isBAGnaam",
    "aWegnummer",
    "nWegnummer",
    "eWegnummer",
    "sWegnummer",
    "afritnummer",
    "afritnaam",
    "knooppuntnaam",
    "brugnaam",
    "tunnelnaam",
    "geometrie"
})
public class WegdeelType
    extends Top250NlObjectType
{

    @XmlElement(required = true)
    protected CodeType typeInfrastructuur;
    @XmlElement(required = true)
    protected CodeType typeWeg;
    @XmlElement(required = true)
    protected CodeType hoofdverkeersgebruik;
    protected List<CodeType> fysiekVoorkomen;
    protected CodeType verhardingsbreedteklasse;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected BRTJaNeeWaardeType gescheidenRijbaan;
    @XmlElement(required = true)
    protected CodeType verhardingstype;
    protected BigInteger aantalRijstroken;
    @XmlElement(required = true)
    protected CodeType status;
    protected List<String> naam;
    @XmlSchemaType(name = "string")
    protected BRTJaNeeWaardeType isBAGnaam;
    protected List<String> aWegnummer;
    protected List<String> nWegnummer;
    protected List<String> eWegnummer;
    protected List<String> sWegnummer;
    protected String afritnummer;
    protected String afritnaam;
    protected String knooppuntnaam;
    protected String brugnaam;
    protected String tunnelnaam;
    @XmlAnyElement
    protected Element geometrie;

    /**
     * Gets the value of the typeInfrastructuur property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getTypeInfrastructuur() {
        return typeInfrastructuur;
    }

    /**
     * Sets the value of the typeInfrastructuur property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setTypeInfrastructuur(CodeType value) {
        this.typeInfrastructuur = value;
    }

    /**
     * Gets the value of the typeWeg property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getTypeWeg() {
        return typeWeg;
    }

    /**
     * Sets the value of the typeWeg property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setTypeWeg(CodeType value) {
        this.typeWeg = value;
    }

    /**
     * Gets the value of the hoofdverkeersgebruik property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getHoofdverkeersgebruik() {
        return hoofdverkeersgebruik;
    }

    /**
     * Sets the value of the hoofdverkeersgebruik property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setHoofdverkeersgebruik(CodeType value) {
        this.hoofdverkeersgebruik = value;
    }

    /**
     * Gets the value of the fysiekVoorkomen property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the fysiekVoorkomen property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFysiekVoorkomen().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getFysiekVoorkomen() {
        if (fysiekVoorkomen == null) {
            fysiekVoorkomen = new ArrayList<CodeType>();
        }
        return this.fysiekVoorkomen;
    }

    /**
     * Gets the value of the verhardingsbreedteklasse property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getVerhardingsbreedteklasse() {
        return verhardingsbreedteklasse;
    }

    /**
     * Sets the value of the verhardingsbreedteklasse property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setVerhardingsbreedteklasse(CodeType value) {
        this.verhardingsbreedteklasse = value;
    }

    /**
     * Gets the value of the gescheidenRijbaan property.
     * 
     * @return
     *     possible object is
     *     {@link BRTJaNeeWaardeType }
     *     
     */
    public BRTJaNeeWaardeType getGescheidenRijbaan() {
        return gescheidenRijbaan;
    }

    /**
     * Sets the value of the gescheidenRijbaan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BRTJaNeeWaardeType }
     *     
     */
    public void setGescheidenRijbaan(BRTJaNeeWaardeType value) {
        this.gescheidenRijbaan = value;
    }

    /**
     * Gets the value of the verhardingstype property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getVerhardingstype() {
        return verhardingstype;
    }

    /**
     * Sets the value of the verhardingstype property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setVerhardingstype(CodeType value) {
        this.verhardingstype = value;
    }

    /**
     * Gets the value of the aantalRijstroken property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAantalRijstroken() {
        return aantalRijstroken;
    }

    /**
     * Sets the value of the aantalRijstroken property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAantalRijstroken(BigInteger value) {
        this.aantalRijstroken = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setStatus(CodeType value) {
        this.status = value;
    }

    /**
     * Gets the value of the naam property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the naam property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNaam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNaam() {
        if (naam == null) {
            naam = new ArrayList<String>();
        }
        return this.naam;
    }

    /**
     * Gets the value of the isBAGnaam property.
     * 
     * @return
     *     possible object is
     *     {@link BRTJaNeeWaardeType }
     *     
     */
    public BRTJaNeeWaardeType getIsBAGnaam() {
        return isBAGnaam;
    }

    /**
     * Sets the value of the isBAGnaam property.
     * 
     * @param value
     *     allowed object is
     *     {@link BRTJaNeeWaardeType }
     *     
     */
    public void setIsBAGnaam(BRTJaNeeWaardeType value) {
        this.isBAGnaam = value;
    }

    /**
     * Gets the value of the aWegnummer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the aWegnummer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAWegnummer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAWegnummer() {
        if (aWegnummer == null) {
            aWegnummer = new ArrayList<String>();
        }
        return this.aWegnummer;
    }

    /**
     * Gets the value of the nWegnummer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the nWegnummer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNWegnummer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNWegnummer() {
        if (nWegnummer == null) {
            nWegnummer = new ArrayList<String>();
        }
        return this.nWegnummer;
    }

    /**
     * Gets the value of the eWegnummer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the eWegnummer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEWegnummer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEWegnummer() {
        if (eWegnummer == null) {
            eWegnummer = new ArrayList<String>();
        }
        return this.eWegnummer;
    }

    /**
     * Gets the value of the sWegnummer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the sWegnummer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSWegnummer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSWegnummer() {
        if (sWegnummer == null) {
            sWegnummer = new ArrayList<String>();
        }
        return this.sWegnummer;
    }

    /**
     * Gets the value of the afritnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAfritnummer() {
        return afritnummer;
    }

    /**
     * Sets the value of the afritnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAfritnummer(String value) {
        this.afritnummer = value;
    }

    /**
     * Gets the value of the afritnaam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAfritnaam() {
        return afritnaam;
    }

    /**
     * Sets the value of the afritnaam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAfritnaam(String value) {
        this.afritnaam = value;
    }

    /**
     * Gets the value of the knooppuntnaam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKnooppuntnaam() {
        return knooppuntnaam;
    }

    /**
     * Sets the value of the knooppuntnaam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKnooppuntnaam(String value) {
        this.knooppuntnaam = value;
    }

    /**
     * Gets the value of the brugnaam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrugnaam() {
        return brugnaam;
    }

    /**
     * Sets the value of the brugnaam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrugnaam(String value) {
        this.brugnaam = value;
    }

    /**
     * Gets the value of the tunnelnaam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTunnelnaam() {
        return tunnelnaam;
    }

    /**
     * Sets the value of the tunnelnaam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTunnelnaam(String value) {
        this.tunnelnaam = value;
    }

    /**
     * Gets the value of the geometrie property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     
     */
    public Element getGeometrie() {
        return geometrie;
    }

    /**
     * Sets the value of the geometrie property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     
     */
    public void setGeometrie(Element value) {
        this.geometrie = value;
    }

}
