-- aanmaken van brmo-schema's in oracle
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- STAGING
CREATE USER "JENKINS_STAGING" IDENTIFIED BY "jenkins_staging" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "JENKINS_STAGING" QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "CONNECT" TO "JENKINS_STAGING";
GRANT "RESOURCE" TO "JENKINS_STAGING";
ALTER USER "JENKINS_STAGING" DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO "JENKINS_STAGING";
GRANT ALTER SESSION TO "JENKINS_STAGING";
GRANT CREATE MATERIALIZED VIEW TO "JENKINS_STAGING";
GRANT CREATE OPERATOR TO "JENKINS_STAGING";
GRANT CREATE VIEW TO "JENKINS_STAGING";
GRANT CREATE SESSION TO "JENKINS_STAGING";
GRANT CREATE TABLE TO "JENKINS_STAGING";
GRANT CREATE SEQUENCE TO "JENKINS_STAGING";
GRANT UNLIMITED TABLESPACE TO "JENKINS_STAGING";
GRANT CREATE PROCEDURE TO "JENKINS_STAGING";


-- RSGB
CREATE USER "JENKINS_RSGB" IDENTIFIED BY "jenkins_rsgb" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "JENKINS_RSGB" QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "CONNECT" TO "JENKINS_RSGB";
GRANT "RESOURCE" TO "JENKINS_RSGB";
ALTER USER "JENKINS_RSGB" DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO "JENKINS_RSGB";
GRANT ALTER SESSION TO "JENKINS_RSGB";
GRANT CREATE MATERIALIZED VIEW TO "JENKINS_RSGB";
GRANT CREATE OPERATOR TO "JENKINS_RSGB";
GRANT CREATE VIEW TO "JENKINS_RSGB";
GRANT CREATE SESSION TO "JENKINS_RSGB";
GRANT CREATE TABLE TO "JENKINS_RSGB";
GRANT CREATE SEQUENCE TO "JENKINS_RSGB";
GRANT UNLIMITED TABLESPACE TO "JENKINS_RSGB";
GRANT CREATE PROCEDURE TO "JENKINS_RSGB";


-- RSGB BGT
CREATE USER "JENKINS_RSGBBGT" IDENTIFIED BY "jenkins_rsgbbgt" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "JENKINS_RSGBBGT" QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "CONNECT" TO "JENKINS_RSGBBGT";
GRANT "RESOURCE" TO "JENKINS_RSGBBGT";
ALTER USER "JENKINS_RSGBBGT" DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO "JENKINS_RSGBBGT";
GRANT ALTER SESSION TO "JENKINS_RSGBBGT";
GRANT CREATE MATERIALIZED VIEW TO "JENKINS_RSGBBGT";
GRANT CREATE OPERATOR TO "JENKINS_RSGBBGT";
GRANT CREATE VIEW TO "JENKINS_RSGBBGT";
GRANT CREATE SESSION TO "JENKINS_RSGBBGT";
GRANT CREATE TABLE TO "JENKINS_RSGBBGT";
GRANT CREATE SEQUENCE TO "JENKINS_RSGBBGT";
GRANT UNLIMITED TABLESPACE TO "JENKINS_RSGBBGT";
GRANT CREATE PROCEDURE TO "JENKINS_RSGBBGT";

-- RSGB TOPNL
CREATE USER "TOP10NL" IDENTIFIED BY "top10nl" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";

grant CREATE TYPE to "TOP10NL";
grant UNLIMITED TABLESPACE to "TOP10NL";
grant CREATE VIEW to "TOP10NL";
grant CREATE SEQUENCE to "TOP10NL";
grant CREATE TRIGGER to "TOP10NL";
grant CREATE SESSION to "TOP10NL";
grant CREATE PROCEDURE to "TOP10NL";
grant CREATE TABLE to "TOP10NL";
grant "CONNECT" to "TOP10NL";
grant CREATE MATERIALIZED VIEW to "TOP10NL";
grant "RESOURCE" to "TOP10NL";

CREATE USER "TOP50NL" IDENTIFIED BY "top50nl" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";

grant CREATE TYPE to "TOP50NL";
grant UNLIMITED TABLESPACE to "TOP50NL";
grant CREATE VIEW to "TOP50NL";
grant CREATE SEQUENCE to "TOP50NL";
grant CREATE TRIGGER to "TOP50NL";
grant CREATE SESSION to "TOP50NL";
grant CREATE PROCEDURE to "TOP50NL";
grant CREATE TABLE to "TOP50NL";
grant "CONNECT" to "TOP50NL";
grant CREATE MATERIALIZED VIEW to "TOP50NL";
grant "RESOURCE" to "TOP50NL";

CREATE USER "TOP100NL" IDENTIFIED BY "top100nl" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";

grant CREATE TYPE to "TOP100NL";
grant UNLIMITED TABLESPACE to "TOP100NL";
grant CREATE VIEW to "TOP100NL";
grant CREATE SEQUENCE to "TOP100NL";
grant CREATE TRIGGER to "TOP100NL";
grant CREATE SESSION to "TOP100NL";
grant CREATE PROCEDURE to "TOP100NL";
grant CREATE TABLE to "TOP100NL";
grant "CONNECT" to "TOP100NL";
grant CREATE MATERIALIZED VIEW to "TOP100NL";
grant "RESOURCE" to "TOP100NL";

CREATE USER "TOP250NL" IDENTIFIED BY "top250nl" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";

grant CREATE TYPE to "TOP250NL";
grant UNLIMITED TABLESPACE to "TOP250NL";
grant CREATE VIEW to "TOP250NL";
grant CREATE SEQUENCE to "TOP250NL";
grant CREATE TRIGGER to "TOP250NL";
grant CREATE SESSION to "TOP250NL";
grant CREATE PROCEDURE to "TOP250NL";
grant CREATE TABLE to "TOP250NL";
grant "CONNECT" to "TOP250NL";
grant CREATE MATERIALIZED VIEW to "TOP250NL";
grant "RESOURCE" to "TOP250NL";


CREATE USER "JENKINS_TOPNL" IDENTIFIED BY "jenkins_topnl" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "JENKINS_TOPNL" QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "CONNECT" TO "JENKINS_TOPNL";
GRANT "RESOURCE" TO "JENKINS_TOPNL";
ALTER USER "JENKINS_TOPNL" DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO "JENKINS_TOPNL";
GRANT ALTER SESSION TO "JENKINS_TOPNL";
GRANT CREATE MATERIALIZED VIEW TO "JENKINS_TOPNL";
GRANT CREATE OPERATOR TO "JENKINS_TOPNL";
GRANT CREATE VIEW TO "JENKINS_TOPNL";
GRANT CREATE SESSION TO "JENKINS_TOPNL";
GRANT CREATE TABLE TO "JENKINS_TOPNL";
GRANT CREATE SEQUENCE TO "JENKINS_TOPNL";
GRANT UNLIMITED TABLESPACE TO "JENKINS_TOPNL";
GRANT CREATE PROCEDURE TO "JENKINS_TOPNL";


CREATE USER "JENKINS_BAG" IDENTIFIED BY "jenkins_bag" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "JENKINS_BAG" QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "CONNECT" TO "JENKINS_BAG";
GRANT "RESOURCE" TO "JENKINS_BAG";
ALTER USER "JENKINS_BAG" DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO "JENKINS_BAG";
GRANT ALTER SESSION TO "JENKINS_BAG";
GRANT CREATE MATERIALIZED VIEW TO "JENKINS_BAG";
GRANT CREATE OPERATOR TO "JENKINS_BAG";
GRANT CREATE VIEW TO "JENKINS_BAG";
GRANT CREATE SESSION TO "JENKINS_BAG";
GRANT CREATE TABLE TO "JENKINS_BAG";
GRANT CREATE SEQUENCE TO "JENKINS_BAG";
GRANT UNLIMITED TABLESPACE TO "JENKINS_BAG";
GRANT CREATE PROCEDURE TO "JENKINS_BAG";