-- oracle
CREATE TABLE BAK
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    BGT_TYPE            VARCHAR2(255),
    PLUS_TYPE           VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    LOD0GEOM MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'BAK',
    'LOD0GEOM',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT ('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'BAK',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT ('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX BAK_LOD0GEOM_IDX ON BAK
  (
    LOD0GEOM
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE INDEX BAK_GEOM2D_IDX ON BAK
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE TABLE BEGROEID_TERREINDEEL
  (
    IDENTIF              VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH        DATE,
    DATUM_EINDE_GELDH    DATE,
    RELVE_HOOGTELIGGING  NUMBER,
    BGT_STATUS           VARCHAR2(255),
    PLUS_STATUS          VARCHAR2(255),
    OPTALUD              VARCHAR2(5),
    BGT_FYSIEKVOORKOMEN  VARCHAR2(255),
    PLUS_FYSIEKVOORKOMEN VARCHAR2(255),
    LOD0MULTISURFACE MDSYS.SDO_GEOMETRY,
    GEOM2D MDSYS.SDO_GEOMETRY,
    KRUINLIJN MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'BEGROEID_TERREINDEEL',
    'LOD0MULTISURFACE',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'BEGROEID_TERREINDEEL',
    'KRUINLIJN',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'BEGROEID_TERREINDEEL',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX IDX_325A46FB5A5A477EBA16EFDF6F ON BEGROEID_TERREINDEEL
  (
    LOD0MULTISURFACE
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="MULTIPOLYGON"');
CREATE INDEX IDX_3E0C469F2DB04BFE8D70351C67 ON BEGROEID_TERREINDEEL
  (
    KRUINLIJN
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="LINE"');
CREATE INDEX IDX_9308A06EC5AF436B9454EF7F21 ON BEGROEID_TERREINDEEL
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POLYGON"');
CREATE TABLE BORD
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    BGT_TYPE            VARCHAR2(255),
    PLUS_TYPE           VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    LOD0GEOM MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'BORD',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'BORD',
    'LOD0GEOM',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX BORD_LOD0GEOM_IDX ON BORD
  (
    LOD0GEOM
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE INDEX BORD_GEOM2D_IDX ON BORD
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE TABLE FUNCTIONEELGEBIED
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    BGT_TYPE            VARCHAR2(255),
    PLUS_TYPE           VARCHAR2(255),
    NAAM                VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'FUNCTIONEELGEBIED',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX FUNCTIONEELGEBIED_GEOM2D_IDX ON FUNCTIONEELGEBIED
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POLYGON"');
CREATE TABLE GEBOUW_INSTALLATIE
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    BGT_TYPE            VARCHAR2(255),
    PLUS_TYPE           VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    LOD0GEOMETRY MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'GEBOUW_INSTALLATIE',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'GEBOUW_INSTALLATIE',
    'LOD0GEOMETRY',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX GEBOUW_INSTALLATIE_GEOM2D_IDX ON GEBOUW_INSTALLATIE
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POLYGON"');
CREATE INDEX IDX_29AA8288A2C742588B6BE169AF ON GEBOUW_INSTALLATIE
  (
    LOD0GEOMETRY
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POLYGON"');
CREATE TABLE INSTALLATIE
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    BGT_TYPE            VARCHAR2(255),
    PLUS_TYPE           VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    LOD0GEOM MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'INSTALLATIE',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'INSTALLATIE',
    'LOD0GEOM',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX INSTALLATIE_GEOM2D_IDX ON INSTALLATIE
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE INDEX INSTALLATIE_LOD0GEOM_IDX ON INSTALLATIE
  (
    LOD0GEOM
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE TABLE KAST
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    BGT_TYPE            VARCHAR2(255),
    PLUS_TYPE           VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    LOD0GEOM MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'KAST',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'KAST',
    'LOD0GEOM',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX KAST_LOD0GEOM_IDX ON KAST
  (
    LOD0GEOM
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE INDEX KAST_GEOM2D_IDX ON KAST
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE TABLE MAST
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    BGT_TYPE            VARCHAR2(255),
    PLUS_TYPE           VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    LOD0GEOM MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'MAST',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'MAST',
    'LOD0GEOM',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX MAST_LOD0GEOM_IDX ON MAST
  (
    LOD0GEOM
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE INDEX MAST_GEOM2D_IDX ON MAST
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE TABLE PAAL
  (
    IDENTIF              VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH        DATE,
    DATUM_EINDE_GELDH    DATE,
    RELVE_HOOGTELIGGING  NUMBER,
    BGT_STATUS           VARCHAR2(255),
    PLUS_STATUS          VARCHAR2(255),
    BGT_TYPE             VARCHAR2(255),
    PLUS_TYPE            VARCHAR2(255),
    HECTOMETERAANDUIDING VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    LOD0GEOM MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'PAAL',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'PAAL',
    'LOD0GEOM',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX PAAL_LOD0GEOM_IDX ON PAAL
  (
    LOD0GEOM
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE INDEX PAAL_GEOM2D_IDX ON PAAL
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE TABLE PUT
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    BGT_TYPE            VARCHAR2(255),
    PLUS_TYPE           VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    LOD0GEOM MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'PUT',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'PUT',
    'LOD0GEOM',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX PUT_LOD0GEOM_IDX ON PUT
  (
    LOD0GEOM
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE INDEX PUT_GEOM2D_IDX ON PUT
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE TABLE SENSOR
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    BGT_TYPE            VARCHAR2(255),
    PLUS_TYPE           VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    LOD0GEOM MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'SENSOR',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'SENSOR',
    'LOD0GEOM',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX SENSOR_LOD0GEOM_IDX ON SENSOR
  (
    LOD0GEOM
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2');
CREATE INDEX SENSOR_GEOM2D_IDX ON SENSOR
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2');
CREATE TABLE OPENBARERUIMTELABEL
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    IDENTIF_BAGOPR      VARCHAR2(255),
    OPRNM_TEKST         VARCHAR2(255),
    OPRNM_POS_1_PUNT MDSYS.SDO_GEOMETRY,
    OPRNM_POS_1_HOEK FLOAT(126),
    OPRNM_POS_2_PUNT MDSYS.SDO_GEOMETRY,
    OPRNM_POS_2_HOEK FLOAT(126),
    OPRNM_POS_3_PUNT MDSYS.SDO_GEOMETRY,
    OPRNM_POS_3_HOEK FLOAT(126),
    OPRTYPE VARCHAR2(255),
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'OPENBARERUIMTELABEL',
    'OPRNM_POS_1_PUNT',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'OPENBARERUIMTELABEL',
    'OPRNM_POS_2_PUNT',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'OPENBARERUIMTELABEL',
    'OPRNM_POS_3_PUNT',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX IDX_DFD9776B31984A38B0255CEC2A ON OPENBARERUIMTELABEL
  (
    OPRNM_POS_1_PUNT
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE INDEX IDX_B2AB80B1B8CF4C95AEBAA06ABE ON OPENBARERUIMTELABEL
  (
    OPRNM_POS_3_PUNT
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE INDEX IDX_6E8EA2966330480D85FD2F7E04 ON OPENBARERUIMTELABEL
  (
    OPRNM_POS_2_PUNT
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE TABLE OVERIGE_SCHEIDING
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    PLUS_TYPE           VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'OVERIGE_SCHEIDING',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX OVERIGE_SCHEIDING_GEOM2D_IDX ON OVERIGE_SCHEIDING
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2');
CREATE TABLE SCHEIDING
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    BGT_TYPE            VARCHAR2(255),
    PLUS_TYPE           VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'SCHEIDING',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX SCHEIDING_GEOM2D_IDX ON SCHEIDING
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2');
CREATE TABLE OVERIG_BOUWWERK
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    BGT_TYPE            VARCHAR2(255),
    PLUS_TYPE           VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'OVERIG_BOUWWERK',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX OVERIG_BOUWWERK_GEOM2D_IDX ON OVERIG_BOUWWERK
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2');
CREATE TABLE ONGECLASSIFICEERDOBJECT
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'ONGECLASSIFICEERDOBJECT',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX IDX_43DAFBD0D21A4C39BC2D9F980B ON ONGECLASSIFICEERDOBJECT
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POLYGON"') ;
CREATE TABLE WATERDEEL
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    BGT_TYPE            VARCHAR2(255),
    PLUS_TYPE           VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'WATERDEEL',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX WATERDEEL_GEOM2D_IDX ON WATERDEEL
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POLYGON"');
CREATE TABLE KUNSTWERKDEEL
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    BGT_TYPE            VARCHAR2(255),
    PLUS_TYPE           VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'KUNSTWERKDEEL',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX KUNSTWERKDEEL_GEOM2D_IDX ON KUNSTWERKDEEL
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2');
CREATE TABLE ONBEGROEID_TERREINDEEL
  (
    IDENTIF              VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH        DATE,
    DATUM_EINDE_GELDH    DATE,
    RELVE_HOOGTELIGGING  NUMBER,
    BGT_STATUS           VARCHAR2(255),
    PLUS_STATUS          VARCHAR2(255),
    BGT_FYSIEKVOORKOMEN  VARCHAR2(255),
    OPTALUD              VARCHAR2(5),
    PLUS_FYSIEKVOORKOMEN VARCHAR2(255),
    KRUINLIJN MDSYS.SDO_GEOMETRY,
    GEOM2D MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'ONBEGROEID_TERREINDEEL',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'ONBEGROEID_TERREINDEEL',
    'KRUINLIJN',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX IDX_728F8FBA18FC4250BF26A9CDC5 ON ONBEGROEID_TERREINDEEL
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POLYGON"');
CREATE INDEX IDX_4EAF754627D245BAA106D8E598 ON ONBEGROEID_TERREINDEEL
  (
    KRUINLIJN
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="LINE"');
CREATE TABLE OVERBRUGGINGSDEEL
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    OTYPE               VARCHAR2(255),
    HOORTBIJTYPE        VARCHAR2(255),
    ISBEWEEGBAAR        VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    LOD0GEOM MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'OVERBRUGGINGSDEEL',
    'LOD0GEOM',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'OVERBRUGGINGSDEEL',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX OVERBRUGGINGSDEEL_LOD0GEOM_IDX ON OVERBRUGGINGSDEEL
  (
    LOD0GEOM
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POLYGON"');
CREATE INDEX OVERBRUGGINGSDEEL_GEOM2D_IDX ON OVERBRUGGINGSDEEL
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POLYGON"');
CREATE TABLE STRAATMEUBILAIR
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    BGT_TYPE            VARCHAR2(255),
    PLUS_TYPE           VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    LOD0GEOM MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'STRAATMEUBILAIR',
    'LOD0GEOM',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'STRAATMEUBILAIR',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX STRAATMEUBILAIR_LOD0GEOM_IDX ON STRAATMEUBILAIR
  (
    LOD0GEOM
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE INDEX STRAATMEUBILAIR_GEOM2D_IDX ON STRAATMEUBILAIR
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE TABLE ONDERSTEUNEND_WATERDEEL
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    BGT_TYPE            VARCHAR2(255),
    PLUS_TYPE           VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'ONDERSTEUNEND_WATERDEEL',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX IDX_5E4F26FD2262478386319AF6A1 ON ONDERSTEUNEND_WATERDEEL
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POLYGON"') ;
CREATE TABLE ONDERSTEUNEND_WEGDEEL
  (
    IDENTIF              VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH        DATE,
    DATUM_EINDE_GELDH    DATE,
    RELVE_HOOGTELIGGING  NUMBER,
    BGT_STATUS           VARCHAR2(255),
    PLUS_STATUS          VARCHAR2(255),
    OPTALUD              VARCHAR2(5),
    BGTFUNCTIE           VARCHAR2(255),
    BGT_FYSIEKVOORKOMEN  VARCHAR2(255),
    PLUS_FUNCTIE         VARCHAR2(255),
    PLUS_FYSIEKVOORKOMEN VARCHAR2(255),
    KRUINLIJN MDSYS.SDO_GEOMETRY,
    LOD0GEOM MDSYS.SDO_GEOMETRY,
    GEOM2D MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'ONDERSTEUNEND_WEGDEEL',
    'KRUINLIJN',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'ONDERSTEUNEND_WEGDEEL',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'ONDERSTEUNEND_WEGDEEL',
    'LOD0GEOM',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX IDX_BAE98081172045FC887FCB0730 ON ONDERSTEUNEND_WEGDEEL
  (
    KRUINLIJN
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="LINE"');
CREATE INDEX IDX_4C732511D3EB4DF6A5D480ABD9 ON ONDERSTEUNEND_WEGDEEL
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POLYGON"');
CREATE INDEX IDX_06421A5912B8418CA36FC49BAE ON ONDERSTEUNEND_WEGDEEL
  (
    LOD0GEOM
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POLYGON"');
CREATE TABLE SPOOR
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    BGT_FUNCTIE         VARCHAR2(255),
    PLUS_FUNCTIE        VARCHAR2(255),
    LOD0GEOM MDSYS.SDO_GEOMETRY,
    GEOM2D MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'SPOOR',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'SPOOR',
    'LOD0GEOM',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX SPOOR_GEOM2D_IDX ON SPOOR
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="MULTICURVE"');
CREATE INDEX SPOOR_LOD0GEOM_IDX ON SPOOR
  (
    LOD0GEOM
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="MULTICURVE"');
CREATE TABLE WEGERINRICHTINGSELEMENT
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    BGT_TYPE            VARCHAR2(255),
    PLUS_TYPE           VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    LOD0GEOM MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'WEGERINRICHTINGSELEMENT',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'WEGERINRICHTINGSELEMENT',
    'LOD0GEOM',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX IDX_4860F2649F3F4A63B75E093042 ON WEGERINRICHTINGSELEMENT
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="MULTICURVE"');
CREATE INDEX IDX_5A88F28F7AE34BC1B9ADE84578 ON WEGERINRICHTINGSELEMENT
  (
    LOD0GEOM
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="MULTICURVE"');
CREATE TABLE VEGETATIEOBJECT
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    BGT_TYPE            VARCHAR2(255),
    PLUS_TYPE           VARCHAR2(255),
    LOD0GEOM MDSYS.SDO_GEOMETRY,
    GEOM2D MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'VEGETATIEOBJECT',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'VEGETATIEOBJECT',
    'LOD0GEOM',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX VEGETATIEOBJECT_GEOM2D_IDX ON VEGETATIEOBJECT
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2');
CREATE INDEX VEGETATIEOBJECT_LOD0GEOM_IDX ON VEGETATIEOBJECT
  (
    LOD0GEOM
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2');
CREATE TABLE TUNNELDEEL
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    LOD0GEOM MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'TUNNELDEEL',
    'LOD0GEOM',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'TUNNELDEEL',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX TUNNELDEEL_LOD0GEOM_IDX ON TUNNELDEEL
  (
    LOD0GEOM
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POLYGON"');
CREATE INDEX TUNNELDEEL_GEOM2D_IDX ON TUNNELDEEL
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POLYGON"');
CREATE TABLE WATERINRICHTINGSELEMENT
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    BGT_TYPE            VARCHAR2(255),
    PLUS_TYPE           VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    LOD0GEOM MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'WATERINRICHTINGSELEMENT',
    'LOD0GEOM',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'WATERINRICHTINGSELEMENT',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX IDX_90804D239BD94E1B8538EBE3AC ON WATERINRICHTINGSELEMENT
  (
    LOD0GEOM
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2');
CREATE INDEX IDX_E1640EBEF4BF453C8788EB90EE ON WATERINRICHTINGSELEMENT
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2');
CREATE TABLE WEGDEEL
  (
    IDENTIF              VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH        DATE,
    DATUM_EINDE_GELDH    DATE,
    RELVE_HOOGTELIGGING  NUMBER,
    BGT_STATUS           VARCHAR2(255),
    PLUS_STATUS          VARCHAR2(255),
    BGT_FUNCTIE          VARCHAR2(255),
    PLUS_FUNCTIE         VARCHAR2(255),
    OPTALUD              VARCHAR2(5),
    BGT_FYSIEKVOORKOMEN  VARCHAR2(255),
    PLUS_FYSIEKVOORKOMEN VARCHAR2(255),
    KRUINLIJN MDSYS.SDO_GEOMETRY,
    LOD0GEOM MDSYS.SDO_GEOMETRY,
    GEOM2D MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'WEGDEEL',
    'KRUINLIJN',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'WEGDEEL',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'WEGDEEL',
    'LOD0GEOM',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX WEGDEEL_KRUINLIJN_IDX ON WEGDEEL
  (
    KRUINLIJN
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="LINE"');
CREATE INDEX WEGDEEL_GEOM2D_IDX ON WEGDEEL
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POLYGON"');
CREATE INDEX WEGDEEL_LOD0GEOM_IDX ON WEGDEEL
  (
    LOD0GEOM
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POLYGON"');
CREATE TABLE BGT_PAND
  (
    IDENTIF             VARCHAR2(255) NOT NULL,
    DAT_BEG_GELDH       DATE,
    DATUM_EINDE_GELDH   DATE,
    RELVE_HOOGTELIGGING NUMBER,
    BGT_STATUS          VARCHAR2(255),
    PLUS_STATUS         VARCHAR2(255),
    IDENTIF_BAGPND      VARCHAR2(255),
    NRAR_1_TEKST        VARCHAR2(255),
    NRAR_1_POS_1_PNT MDSYS.SDO_GEOMETRY,
    NRAR_1_POS_1_HOEK FLOAT(126),
    NRAR_1_POS_2_PNT MDSYS.SDO_GEOMETRY,
    NRAR_1_POS_2_HOEK FLOAT(126),
    NRAR_1_POS_3_PNT MDSYS.SDO_GEOMETRY,
    NRAR_1_POS_3_HOEK FLOAT(126),
    NRAR_1_ID_BAGVBO_MIN_HUISNR VARCHAR2(255),
    NRAR_1_ID_BAGVBO_MAX_HUISNR VARCHAR2(255),
    NRAR_2_TEKST                VARCHAR2(255),
    NRAR_2_POS_1_PNT MDSYS.SDO_GEOMETRY,
    NRAR_2_POS_1_HOEK FLOAT(126),
    NRAR_2_POS_2_PNT MDSYS.SDO_GEOMETRY,
    NRAR_2_POS_2_HOEK FLOAT(126),
    NRAR_2_POS_3_PNT MDSYS.SDO_GEOMETRY,
    NRAR_2_POS_3_HOEK FLOAT(126),
    NRAR_2_ID_BAGVBO_MIN_HUISNR VARCHAR2(255),
    NRAR_2_ID_BAGVBO_MAX_HUISNR VARCHAR2(255),
    NRAR_3_TEKST                VARCHAR2(255),
    NRAR_3_POS_1_PNT MDSYS.SDO_GEOMETRY,
    NRAR_3_POS_1_HOEK FLOAT(126),
    NRAR_3_POS_2_PNT MDSYS.SDO_GEOMETRY,
    NRAR_3_POS_2_HOEK FLOAT(126),
    NRAR_3_POS_3_PNT MDSYS.SDO_GEOMETRY,
    NRAR_3_POS_3_HOEK FLOAT(126),
    NRAR_3_ID_BAGVBO_MIN_HUISNR VARCHAR2(255),
    NRAR_3_ID_BAGVBO_MAX_HUISNR VARCHAR2(255),
    GEOM2D MDSYS.SDO_GEOMETRY,
    PRIMARY KEY (IDENTIF)
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'BGT_PAND',
    'GEOM2D',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'BGT_PAND',
    'NRAR_1_POS_1_PNT',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'BGT_PAND',
    'NRAR_1_POS_2_PNT',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'BGT_PAND',
    'NRAR_1_POS_3_PNT',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'BGT_PAND',
    'NRAR_2_POS_1_PNT',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'BGT_PAND',
    'NRAR_2_POS_2_PNT',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'BGT_PAND',
    'NRAR_2_POS_3_PNT',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'BGT_PAND',
    'NRAR_3_POS_1_PNT',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'BGT_PAND',
    'NRAR_3_POS_2_PNT',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'BGT_PAND',
    'NRAR_3_POS_3_PNT',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 12000, 280000, .1), MDSYS.SDO_DIM_ELEMENT('Y', 304000, 620000, .1)),
    28992
  );
CREATE INDEX BGT_PAND_NRAR_1_POS_1_PNT_IDX ON BGT_PAND
  (
    NRAR_1_POS_1_PNT
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE INDEX BGT_PAND_NRAR_1_POS_2_PNT_IDX ON BGT_PAND
  (
    NRAR_1_POS_2_PNT
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE INDEX BGT_PAND_NRAR_1_POS_3_PNT_IDX ON BGT_PAND
  (
    NRAR_1_POS_3_PNT
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE INDEX BGT_PAND_NRAR_2_POS_1_PNT_IDX ON BGT_PAND
  (
    NRAR_2_POS_1_PNT
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE INDEX BGT_PAND_NRAR_2_POS_3_PNT_IDX ON BGT_PAND
  (
    NRAR_2_POS_3_PNT
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE INDEX BGT_PAND_NRAR_2_POS_2_PNT_IDX ON BGT_PAND
  (
    NRAR_2_POS_2_PNT
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE INDEX BGT_PAND_NRAR_3_POS_2_PNT_IDX ON BGT_PAND
  (
    NRAR_3_POS_2_PNT
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE INDEX BGT_PAND_NRAR_3_POS_3_PNT_IDX ON BGT_PAND
  (
    NRAR_3_POS_3_PNT
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE INDEX BGT_PAND_NRAR_3_POS_1_PNT_IDX ON BGT_PAND
  (
    NRAR_3_POS_1_PNT
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="POINT"');
CREATE INDEX BGT_PAND_GEOM2D_IDX ON BGT_PAND
  (
    GEOM2D
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('SDO_INDX_DIMS=2 LAYER_GTYPE="MULTIPOLYGON"');
