--
-- upgrade Oracle RSGB datamodel van 1.5.2 naar 1.5.3
--

ALTER TABLE ANDER_BTNLNDS_NIET_NAT_PRS MODIFY SC_IDENTIF VARCHAR2(255);
ALTER TABLE ANDER_NAT_PRS MODIFY SC_IDENTIF VARCHAR2(255);
ALTER TABLE APP_RE MODIFY FK_2NNP_SC_IDENTIF VARCHAR2(255);
ALTER TABLE INGESCHR_NIET_NAT_PRS MODIFY SC_IDENTIF VARCHAR2(255);
ALTER TABLE INGESCHR_NAT_PRS MODIFY SC_IDENTIF VARCHAR2(255);
ALTER TABLE INGEZETENE MODIFY SC_IDENTIF VARCHAR2(255);
ALTER TABLE KAD_ONRRND_ZK MODIFY FK_10PES_SC_IDENTIF VARCHAR2(255);
ALTER TABLE KAD_ONRRND_ZK_AANTEK MODIFY FK_5PES_SC_IDENTIF VARCHAR2(255);
ALTER TABLE MAATSCHAPP_ACTIVITEIT MODIFY FK_4PES_SC_IDENTIF VARCHAR2(255);
ALTER TABLE NAT_PRS MODIFY SC_IDENTIF VARCHAR2(255);
ALTER TABLE NIET_INGEZETENE MODIFY SC_IDENTIF VARCHAR2(255);
ALTER TABLE NIET_NAT_PRS MODIFY SC_IDENTIF VARCHAR2(255);
ALTER TABLE PRS MODIFY  SC_IDENTIF VARCHAR2(255);
ALTER TABLE SUBJECT MODIFY IDENTIF VARCHAR2(255);
ALTER TABLE VESTG MODIFY  SC_IDENTIF VARCHAR2(255);
ALTER TABLE VESTG MODIFY FK_18VES_SC_IDENTIF VARCHAR2(255);
ALTER TABLE ZAK_RECHT MODIFY FK_8PES_SC_IDENTIF VARCHAR2(255);
ALTER TABLE ZAK_RECHT_AANTEK MODIFY FK_6PES_SC_IDENTIF VARCHAR2(255);
ALTER TABLE VESTG_NAAM MODIFY FK_VES_SC_IDENTIF VARCHAR2(255);
ALTER TABLE HUISHOUDENREL MODIFY FK_SC_LH_INP_SC_IDENTIF VARCHAR2(255);
ALTER TABLE HUW_GER_PARTN MODIFY FK_SC_LH_INP_SC_IDENTIF VARCHAR2(255);
ALTER TABLE HUW_GER_PARTN MODIFY FK_SC_RH_INP_SC_IDENTIF VARCHAR2(255);
ALTER TABLE OUDER_KIND_REL MODIFY FK_SC_LH_INP_SC_IDENTIF VARCHAR2(255);
ALTER TABLE OUDER_KIND_REL MODIFY FK_SC_RH_INP_SC_IDENTIF VARCHAR2(255);
ALTER TABLE RSDOC_INGESCHR_NAT_PRS MODIFY FK_NN_RH_INP_SC_IDENTIF VARCHAR2(255);
ALTER TABLE VESTG_BENOEMD_OBJ MODIFY FK_NN_LH_VES_SC_IDENTIF VARCHAR2(255);

-- onderstaande dienen als laatste stappen van een upgrade uitgevoerd
INSERT INTO brmo_metadata (naam,waarde) SELECT 'upgrade_1.5.2_naar_1.5.3','vorige versie was '||waarde FROM brmo_metadata WHERE naam='brmoversie';
-- versienummer update
UPDATE brmo_metadata SET waarde='1.5.3' WHERE naam='brmoversie';
