//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 10:59:51 AM CEST 
//


package nl.b3p.topnl.top100nl;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HoofdverkeersgebruikT100Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="HoofdverkeersgebruikT100Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="snelverkeer"/&gt;
 *     &lt;enumeration value="gemengd verkeer"/&gt;
 *     &lt;enumeration value="busverkeer"/&gt;
 *     &lt;enumeration value="fietsers, bromfietsers"/&gt;
 *     &lt;enumeration value="voetgangers"/&gt;
 *     &lt;enumeration value="vliegverkeer"/&gt;
 *     &lt;enumeration value="overig"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "HoofdverkeersgebruikT100Type", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/top100nl/1.1.0")
@XmlEnum
public enum HoofdverkeersgebruikT100Type {

    @XmlEnumValue("snelverkeer")
    SNELVERKEER("snelverkeer"),
    @XmlEnumValue("gemengd verkeer")
    GEMENGD_VERKEER("gemengd verkeer"),
    @XmlEnumValue("busverkeer")
    BUSVERKEER("busverkeer"),
    @XmlEnumValue("fietsers, bromfietsers")
    FIETSERS_BROMFIETSERS("fietsers, bromfietsers"),
    @XmlEnumValue("voetgangers")
    VOETGANGERS("voetgangers"),
    @XmlEnumValue("vliegverkeer")
    VLIEGVERKEER("vliegverkeer"),
    @XmlEnumValue("overig")
    OVERIG("overig");
    private final String value;

    HoofdverkeersgebruikT100Type(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HoofdverkeersgebruikT100Type fromValue(String v) {
        for (HoofdverkeersgebruikT100Type c: HoofdverkeersgebruikT100Type.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
