//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 10:59:51 AM CEST 
//


package nl.b3p.topnl.top100nl;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for HoogteType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HoogteType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://register.geostandaarden.nl/gmlapplicatieschema/top100nl/1.1.0}_Top100nlObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="geometrie" type="{http://register.geostandaarden.nl/gmlapplicatieschema/top100nl/1.1.0}LijnOfPuntPropertyType"/&gt;
 *         &lt;element name="hoogte" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="typeHoogte" type="{http://register.geostandaarden.nl/gmlapplicatieschema/top100nl/1.1.0}TypeHoogteT100Type"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HoogteType", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/top100nl/1.1.0", propOrder = {
    "geometrie",
    "hoogte",
    "typeHoogte"
})
public class HoogteType
    extends Top100NlObjectType
{

    @XmlAnyElement
    protected Element geometrie;
    protected double hoogte;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TypeHoogteT100Type typeHoogte;

    /**
     * Gets the value of the geometrie property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     
     */
    public Element getGeometrie() {
        return geometrie;
    }

    /**
     * Sets the value of the geometrie property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     
     */
    public void setGeometrie(Element value) {
        this.geometrie = value;
    }

    /**
     * Gets the value of the hoogte property.
     * 
     */
    public double getHoogte() {
        return hoogte;
    }

    /**
     * Sets the value of the hoogte property.
     * 
     */
    public void setHoogte(double value) {
        this.hoogte = value;
    }

    /**
     * Gets the value of the typeHoogte property.
     * 
     * @return
     *     possible object is
     *     {@link TypeHoogteT100Type }
     *     
     */
    public TypeHoogteT100Type getTypeHoogte() {
        return typeHoogte;
    }

    /**
     * Sets the value of the typeHoogte property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeHoogteT100Type }
     *     
     */
    public void setTypeHoogte(TypeHoogteT100Type value) {
        this.typeHoogte = value;
    }

}
