//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 10:59:51 AM CEST 
//


package nl.b3p.topnl.top100nl;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for TerreinType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TerreinType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://register.geostandaarden.nl/gmlapplicatieschema/top100nl/1.1.0}_Top100nlObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="geometrie" type="{http://www.opengis.net/gml/3.2}SurfacePropertyType"/&gt;
 *         &lt;element name="typeLandgebruik" type="{http://register.geostandaarden.nl/gmlapplicatieschema/top100nl/1.1.0}TypeLandgebruikT100Type"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TerreinType", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/top100nl/1.1.0", propOrder = {
    "geometrie",
    "typeLandgebruik"
})
public class TerreinType
    extends Top100NlObjectType
{

    @XmlAnyElement
    protected Element geometrie;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TypeLandgebruikT100Type typeLandgebruik;

    /**
     * Gets the value of the geometrie property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     
     */
    public Element getGeometrie() {
        return geometrie;
    }

    /**
     * Sets the value of the geometrie property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     
     */
    public void setGeometrie(Element value) {
        this.geometrie = value;
    }

    /**
     * Gets the value of the typeLandgebruik property.
     * 
     * @return
     *     possible object is
     *     {@link TypeLandgebruikT100Type }
     *     
     */
    public TypeLandgebruikT100Type getTypeLandgebruik() {
        return typeLandgebruik;
    }

    /**
     * Sets the value of the typeLandgebruik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeLandgebruikT100Type }
     *     
     */
    public void setTypeLandgebruik(TypeLandgebruikT100Type value) {
        this.typeLandgebruik = value;
    }

}
