//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 10:59:51 AM CEST 
//


package nl.b3p.topnl.top100nl;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeLandgebruikT100Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TypeLandgebruikT100Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="aanlegsteiger"/&gt;
 *     &lt;enumeration value="akkerland"/&gt;
 *     &lt;enumeration value="basaltblokken, steenglooiing"/&gt;
 *     &lt;enumeration value="bebouwd gebied"/&gt;
 *     &lt;enumeration value="boomgaard"/&gt;
 *     &lt;enumeration value="boomkwekerij"/&gt;
 *     &lt;enumeration value="bos: gemengd bos"/&gt;
 *     &lt;enumeration value="bos: griend"/&gt;
 *     &lt;enumeration value="bos: loofbos"/&gt;
 *     &lt;enumeration value="bos: naaldbos"/&gt;
 *     &lt;enumeration value="dodenakker"/&gt;
 *     &lt;enumeration value="fruitkwekerij"/&gt;
 *     &lt;enumeration value="grasland"/&gt;
 *     &lt;enumeration value="heide"/&gt;
 *     &lt;enumeration value="kassengebied"/&gt;
 *     &lt;enumeration value="laadperron"/&gt;
 *     &lt;enumeration value="populieren"/&gt;
 *     &lt;enumeration value="spoorbaanlichaam"/&gt;
 *     &lt;enumeration value="zand"/&gt;
 *     &lt;enumeration value="overig"/&gt;
 *     &lt;enumeration value="ongedefinieerd"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TypeLandgebruikT100Type", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/top100nl/1.1.0")
@XmlEnum
public enum TypeLandgebruikT100Type {

    @XmlEnumValue("aanlegsteiger")
    AANLEGSTEIGER("aanlegsteiger"),
    @XmlEnumValue("akkerland")
    AKKERLAND("akkerland"),
    @XmlEnumValue("basaltblokken, steenglooiing")
    BASALTBLOKKEN_STEENGLOOIING("basaltblokken, steenglooiing"),
    @XmlEnumValue("bebouwd gebied")
    BEBOUWD_GEBIED("bebouwd gebied"),
    @XmlEnumValue("boomgaard")
    BOOMGAARD("boomgaard"),
    @XmlEnumValue("boomkwekerij")
    BOOMKWEKERIJ("boomkwekerij"),
    @XmlEnumValue("bos: gemengd bos")
    BOS_GEMENGD_BOS("bos: gemengd bos"),
    @XmlEnumValue("bos: griend")
    BOS_GRIEND("bos: griend"),
    @XmlEnumValue("bos: loofbos")
    BOS_LOOFBOS("bos: loofbos"),
    @XmlEnumValue("bos: naaldbos")
    BOS_NAALDBOS("bos: naaldbos"),
    @XmlEnumValue("dodenakker")
    DODENAKKER("dodenakker"),
    @XmlEnumValue("fruitkwekerij")
    FRUITKWEKERIJ("fruitkwekerij"),
    @XmlEnumValue("grasland")
    GRASLAND("grasland"),
    @XmlEnumValue("heide")
    HEIDE("heide"),
    @XmlEnumValue("kassengebied")
    KASSENGEBIED("kassengebied"),
    @XmlEnumValue("laadperron")
    LAADPERRON("laadperron"),
    @XmlEnumValue("populieren")
    POPULIEREN("populieren"),
    @XmlEnumValue("spoorbaanlichaam")
    SPOORBAANLICHAAM("spoorbaanlichaam"),
    @XmlEnumValue("zand")
    ZAND("zand"),
    @XmlEnumValue("overig")
    OVERIG("overig"),

    /**
     * ruimte tussen 2 weglijnen van direct naast elkaar gelegen wegen
     * 
     */
    @XmlEnumValue("ongedefinieerd")
    ONGEDEFINIEERD("ongedefinieerd");
    private final String value;

    TypeLandgebruikT100Type(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeLandgebruikT100Type fromValue(String v) {
        for (TypeLandgebruikT100Type c: TypeLandgebruikT100Type.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
