//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 10:59:51 AM CEST 
//


package nl.b3p.topnl.top100nl;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeWaterT100Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TypeWaterT100Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="waterloop"/&gt;
 *     &lt;enumeration value="meer, plas, ven, vijver"/&gt;
 *     &lt;enumeration value="greppel, droge sloot"/&gt;
 *     &lt;enumeration value="zee"/&gt;
 *     &lt;enumeration value="droogvallend"/&gt;
 *     &lt;enumeration value="bron, wel"/&gt;
 *     &lt;enumeration value="overig"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TypeWaterT100Type", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/top100nl/1.1.0")
@XmlEnum
public enum TypeWaterT100Type {

    @XmlEnumValue("waterloop")
    WATERLOOP("waterloop"),
    @XmlEnumValue("meer, plas, ven, vijver")
    MEER_PLAS_VEN_VIJVER("meer, plas, ven, vijver"),
    @XmlEnumValue("greppel, droge sloot")
    GREPPEL_DROGE_SLOOT("greppel, droge sloot"),
    @XmlEnumValue("zee")
    ZEE("zee"),
    @XmlEnumValue("droogvallend")
    DROOGVALLEND("droogvallend"),
    @XmlEnumValue("bron, wel")
    BRON_WEL("bron, wel"),
    @XmlEnumValue("overig")
    OVERIG("overig");
    private final String value;

    TypeWaterT100Type(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeWaterT100Type fromValue(String v) {
        for (TypeWaterT100Type c: TypeWaterT100Type.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
