//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 10:59:51 AM CEST 
//


package nl.b3p.topnl.top100nl;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VlakOfLijnPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VlakOfLijnPropertyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://register.geostandaarden.nl/gmlapplicatieschema/top100nl/1.1.0}VlakOfLijn"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VlakOfLijnPropertyType", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/top100nl/1.1.0", propOrder = {
    "vlakOfLijn"
})
public class VlakOfLijnPropertyType {

    @XmlElement(name = "VlakOfLijn", required = true)
    protected VlakOfLijnType vlakOfLijn;

    /**
     * Gets the value of the vlakOfLijn property.
     * 
     * @return
     *     possible object is
     *     {@link VlakOfLijnType }
     *     
     */
    public VlakOfLijnType getVlakOfLijn() {
        return vlakOfLijn;
    }

    /**
     * Sets the value of the vlakOfLijn property.
     * 
     * @param value
     *     allowed object is
     *     {@link VlakOfLijnType }
     *     
     */
    public void setVlakOfLijn(VlakOfLijnType value) {
        this.vlakOfLijn = value;
    }

}
