--
-- upgrade Oracle TopNL datamodellen van 3.0.2 naar 4.0.0
-- NB uit te voeren onder sys of een andere gebruiker met voldoende rechten in alle schemas
--
-- verbreed de boolean kolommen zodat er true/false in past
ALTER TABLE TOP10NL.SPOORBAANDEEL MODIFY ELEKTRIFICATIE VARCHAR2(5);
ALTER TABLE TOP10NL.WATERDEEL MODIFY GETIJDEINVLOED VARCHAR2(5);
ALTER TABLE TOP10NL.WATERDEEL MODIFY ISBAGNAAM VARCHAR2(5);
ALTER TABLE TOP10NL.WATERDEEL MODIFY HOOFDAFWATERING VARCHAR2(5);
ALTER TABLE TOP100NL.WEGDEEL MODIFY GESCHEIDENRIJBAAN VARCHAR2(5);
ALTER TABLE TOP100NL.WEGDEEL MODIFY ISBAGNAAM VARCHAR2(5);

ALTER TABLE TOP50NL.SPOORBAANDEEL MODIFY ELEKTRIFICATIE VARCHAR2(5);
ALTER TABLE TOP50NL.WATERDEEL MODIFY GETIJDEINVLOED VARCHAR2(5);
ALTER TABLE TOP50NL.WATERDEEL MODIFY ISBAGNAAM VARCHAR2(5);
ALTER TABLE TOP50NL.WATERDEEL MODIFY HOOFDAFWATERING VARCHAR2(5);
ALTER TABLE TOP50NL.WEGDEEL MODIFY GESCHEIDENRIJBAAN VARCHAR2(5);
ALTER TABLE TOP50NL.WEGDEEL MODIFY ISBAGNAAM VARCHAR2(5);

ALTER TABLE TOP100NL.SPOORBAANDEEL MODIFY ELEKTRIFICATIE VARCHAR2(5);
ALTER TABLE TOP100NL.WATERDEEL MODIFY GETIJDEINVLOED VARCHAR2(5);
ALTER TABLE TOP100NL.WATERDEEL MODIFY ISBAGNAAM VARCHAR2(5);
ALTER TABLE TOP100NL.WATERDEEL MODIFY HOOFDAFWATERING VARCHAR2(5);
ALTER TABLE TOP100NL.WEGDEEL MODIFY GESCHEIDENRIJBAAN VARCHAR2(5);
ALTER TABLE TOP100NL.WEGDEEL MODIFY ISBAGNAAM VARCHAR2(5);

ALTER TABLE TOP250NL.SPOORBAANDEEL MODIFY ELEKTRIFICATIE VARCHAR2(5);
ALTER TABLE TOP250NL.WATERDEEL MODIFY GETIJDEINVLOED VARCHAR2(5);
ALTER TABLE TOP250NL.WATERDEEL MODIFY ISBAGNAAM VARCHAR2(5);
ALTER TABLE TOP250NL.WATERDEEL MODIFY HOOFDAFWATERING VARCHAR2(5);
ALTER TABLE TOP250NL.WEGDEEL MODIFY GESCHEIDENRIJBAAN VARCHAR2(5);
ALTER TABLE TOP250NL.WEGDEEL MODIFY ISBAGNAAM VARCHAR2(5);
