<?xml version="1.0" encoding="UTF-8"?>
<CityModel xmlns:gml="http://www.opengis.net/gml"
				xmlns:imgeo="http://www.geostandaarden.nl/imgeo/2.1"
				xmlns:lu="http://www.opengis.net/citygml/landuse/2.0"
				xmlns:tra="http://www.opengis.net/citygml/transportation/2.0"
				xmlns:tun="http://www.opengis.net/citygml/tunnel/2.0"
				xmlns:veg="http://www.opengis.net/citygml/vegetation/2.0"
				xmlns:xlink="http://www.w3.org/1999/xlink"
				xmlns:wat="http://www.opengis.net/citygml/waterbody/2.0"
				xmlns:bri="http://www.opengis.net/citygml/bridge/2.0"
				xmlns:bui="http://www.opengis.net/citygml/building/2.0"
				xmlns:cif="http://www.opengis.net/citygml/cityfurniture/2.0"
				xmlns="http://www.opengis.net/citygml/2.0"
				xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
				xsi:schemaLocation="http://www.geostandaarden.nl/imgeo/2.1 http://schemas.geonovum.nl/imgeo/2.1/imgeo-2.1.1.xsd"></CityModel>