//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 10:59:54 AM CEST 
//


package nl.b3p.topnl.top10nl;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BRTHogeEnLageZijdePropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BRTHogeEnLageZijdePropertyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTHogeEnLageZijde"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BRTHogeEnLageZijdePropertyType", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0", propOrder = {
    "brtHogeEnLageZijde"
})
public class BRTHogeEnLageZijdePropertyType {

    @XmlElement(name = "BRTHogeEnLageZijde", required = true)
    protected BRTHogeEnLageZijdeType brtHogeEnLageZijde;

    /**
     * Gets the value of the brtHogeEnLageZijde property.
     * 
     * @return
     *     possible object is
     *     {@link BRTHogeEnLageZijdeType }
     *     
     */
    public BRTHogeEnLageZijdeType getBRTHogeEnLageZijde() {
        return brtHogeEnLageZijde;
    }

    /**
     * Sets the value of the brtHogeEnLageZijde property.
     * 
     * @param value
     *     allowed object is
     *     {@link BRTHogeEnLageZijdeType }
     *     
     */
    public void setBRTHogeEnLageZijde(BRTHogeEnLageZijdeType value) {
        this.brtHogeEnLageZijde = value;
    }

}
