//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.08 at 10:18:04 AM CET 
//


package nl.b3p.topnl.top250nl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BRTVlakOfMultivlakPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BRTVlakOfMultivlakPropertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTVlakOfMultivlak"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BRTVlakOfMultivlakPropertyType", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0", propOrder = {
    "brtVlakOfMultivlak"
})
public class BRTVlakOfMultivlakPropertyType {

    @XmlElement(name = "BRTVlakOfMultivlak", required = true)
    protected BRTVlakOfMultivlakType brtVlakOfMultivlak;

    /**
     * Gets the value of the brtVlakOfMultivlak property.
     * 
     * @return
     *     possible object is
     *     {@link BRTVlakOfMultivlakType }
     *     
     */
    public BRTVlakOfMultivlakType getBRTVlakOfMultivlak() {
        return brtVlakOfMultivlak;
    }

    /**
     * Sets the value of the brtVlakOfMultivlak property.
     * 
     * @param value
     *     allowed object is
     *     {@link BRTVlakOfMultivlakType }
     *     
     */
    public void setBRTVlakOfMultivlak(BRTVlakOfMultivlakType value) {
        this.brtVlakOfMultivlak = value;
    }

}
