//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 10:59:53 AM CEST 
//


package nl.b3p.topnl.top50nl;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LijnOfPuntType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LijnOfPuntType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="lijnGeometrie" type="{http://www.opengis.net/gml/3.2}CurvePropertyType"/&gt;
 *         &lt;element name="puntGeometrie" type="{http://www.opengis.net/gml/3.2}PointPropertyType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LijnOfPuntType", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/top50nl/1.1.1", propOrder = {
    "lijnGeometrie",
    "puntGeometrie"
})
public class LijnOfPuntType {

    protected CurvePropertyType lijnGeometrie;
    protected PointPropertyType puntGeometrie;

    /**
     * Gets the value of the lijnGeometrie property.
     * 
     * @return
     *     possible object is
     *     {@link CurvePropertyType }
     *     
     */
    public CurvePropertyType getLijnGeometrie() {
        return lijnGeometrie;
    }

    /**
     * Sets the value of the lijnGeometrie property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurvePropertyType }
     *     
     */
    public void setLijnGeometrie(CurvePropertyType value) {
        this.lijnGeometrie = value;
    }

    /**
     * Gets the value of the puntGeometrie property.
     * 
     * @return
     *     possible object is
     *     {@link PointPropertyType }
     *     
     */
    public PointPropertyType getPuntGeometrie() {
        return puntGeometrie;
    }

    /**
     * Sets the value of the puntGeometrie property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointPropertyType }
     *     
     */
    public void setPuntGeometrie(PointPropertyType value) {
        this.puntGeometrie = value;
    }

}
