//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 10:59:53 AM CEST 
//


package nl.b3p.topnl.top50nl;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LijnOfPuntPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LijnOfPuntPropertyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://register.geostandaarden.nl/gmlapplicatieschema/top50nl/1.1.1}LijnOfPunt"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LijnOfPuntPropertyType", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/top50nl/1.1.1", propOrder = {
    "lijnOfPunt"
})
public class LijnOfPuntPropertyType {

    @XmlElement(name = "LijnOfPunt", required = true)
    protected LijnOfPuntType lijnOfPunt;

    /**
     * Gets the value of the lijnOfPunt property.
     * 
     * @return
     *     possible object is
     *     {@link LijnOfPuntType }
     *     
     */
    public LijnOfPuntType getLijnOfPunt() {
        return lijnOfPunt;
    }

    /**
     * Sets the value of the lijnOfPunt property.
     * 
     * @param value
     *     allowed object is
     *     {@link LijnOfPuntType }
     *     
     */
    public void setLijnOfPunt(LijnOfPuntType value) {
        this.lijnOfPunt = value;
    }

}
