//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 10:59:53 AM CEST 
//


package nl.b3p.topnl.top50nl;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for RegistratiefGebiedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistratiefGebiedType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://register.geostandaarden.nl/gmlapplicatieschema/top50nl/1.1.1}_Top50nlObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="geometrie" type="{http://register.geostandaarden.nl/gmlapplicatieschema/top50nl/1.1.1}VlakOfMultivlakPropertyType"/&gt;
 *         &lt;element name="naamFries" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="naamNL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="nummer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="typeRegistratiefGebied" type="{http://register.geostandaarden.nl/gmlapplicatieschema/top50nl/1.1.1}TypeRegistratiefGebiedT50Type"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistratiefGebiedType", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/top50nl/1.1.1", propOrder = {
    "geometrie",
    "naamFries",
    "naamNL",
    "nummer",
    "typeRegistratiefGebied"
})
public class RegistratiefGebiedType
    extends Top50NlObjectType
{

    @XmlAnyElement
    protected Element geometrie;
    protected String naamFries;
    protected String naamNL;
    protected String nummer;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TypeRegistratiefGebiedT50Type typeRegistratiefGebied;

    /**
     * Gets the value of the geometrie property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     
     */
    public Element getGeometrie() {
        return geometrie;
    }

    /**
     * Sets the value of the geometrie property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     
     */
    public void setGeometrie(Element value) {
        this.geometrie = value;
    }

    /**
     * Gets the value of the naamFries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaamFries() {
        return naamFries;
    }

    /**
     * Sets the value of the naamFries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaamFries(String value) {
        this.naamFries = value;
    }

    /**
     * Gets the value of the naamNL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaamNL() {
        return naamNL;
    }

    /**
     * Sets the value of the naamNL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaamNL(String value) {
        this.naamNL = value;
    }

    /**
     * Gets the value of the nummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNummer() {
        return nummer;
    }

    /**
     * Sets the value of the nummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNummer(String value) {
        this.nummer = value;
    }

    /**
     * Gets the value of the typeRegistratiefGebied property.
     * 
     * @return
     *     possible object is
     *     {@link TypeRegistratiefGebiedT50Type }
     *     
     */
    public TypeRegistratiefGebiedT50Type getTypeRegistratiefGebied() {
        return typeRegistratiefGebied;
    }

    /**
     * Sets the value of the typeRegistratiefGebied property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeRegistratiefGebiedT50Type }
     *     
     */
    public void setTypeRegistratiefGebied(TypeRegistratiefGebiedT50Type value) {
        this.typeRegistratiefGebied = value;
    }

}
