//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 10:59:53 AM CEST 
//


package nl.b3p.topnl.top50nl;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeVerhardingT50Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TypeVerhardingT50Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="verhard"/&gt;
 *     &lt;enumeration value="half verhard"/&gt;
 *     &lt;enumeration value="onverhard"/&gt;
 *     &lt;enumeration value="onbekend"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TypeVerhardingT50Type", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/top50nl/1.1.1")
@XmlEnum
public enum TypeVerhardingT50Type {

    @XmlEnumValue("verhard")
    VERHARD("verhard"),
    @XmlEnumValue("half verhard")
    HALF_VERHARD("half verhard"),
    @XmlEnumValue("onverhard")
    ONVERHARD("onverhard"),
    @XmlEnumValue("onbekend")
    ONBEKEND("onbekend");
    private final String value;

    TypeVerhardingT50Type(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeVerhardingT50Type fromValue(String v) {
        for (TypeVerhardingT50Type c: TypeVerhardingT50Type.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
