//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 10:59:53 AM CEST 
//


package nl.b3p.topnl.top50nl;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeRegistratiefGebiedT50Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TypeRegistratiefGebiedT50Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="land"/&gt;
 *     &lt;enumeration value="provincie"/&gt;
 *     &lt;enumeration value="gemeente"/&gt;
 *     &lt;enumeration value="enclave"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TypeRegistratiefGebiedT50Type", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/top50nl/1.1.1")
@XmlEnum
public enum TypeRegistratiefGebiedT50Type {

    @XmlEnumValue("land")
    LAND("land"),
    @XmlEnumValue("provincie")
    PROVINCIE("provincie"),
    @XmlEnumValue("gemeente")
    GEMEENTE("gemeente"),
    @XmlEnumValue("enclave")
    ENCLAVE("enclave");
    private final String value;

    TypeRegistratiefGebiedT50Type(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeRegistratiefGebiedT50Type fromValue(String v) {
        for (TypeRegistratiefGebiedT50Type c: TypeRegistratiefGebiedT50Type.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
