//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 10:59:53 AM CEST 
//


package nl.b3p.topnl.top50nl;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeBronT50Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TypeBronT50Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="externe data"/&gt;
 *     &lt;enumeration value="TOP10NL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TypeBronT50Type", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/top50nl/1.1.1")
@XmlEnum
public enum TypeBronT50Type {


    /**
     * Data afkomstig uit andere bronnen dan TOP10NL
     * 
     */
    @XmlEnumValue("externe data")
    EXTERNE_DATA("externe data"),

    /**
     * Ontstaan door automatische generalisatie van TOP10NL data
     * 
     */
    @XmlEnumValue("TOP10NL")
    TOP_10_NL("TOP10NL");
    private final String value;

    TypeBronT50Type(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeBronT50Type fromValue(String v) {
        for (TypeBronT50Type c: TypeBronT50Type.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
