//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 10:59:53 AM CEST 
//


package nl.b3p.topnl.top50nl;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeInfrastructuurWegT50Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TypeInfrastructuurWegT50Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="verbinding"/&gt;
 *     &lt;enumeration value="overig verkeersgebied"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TypeInfrastructuurWegT50Type", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/top50nl/1.1.1")
@XmlEnum
public enum TypeInfrastructuurWegT50Type {

    @XmlEnumValue("verbinding")
    VERBINDING("verbinding"),
    @XmlEnumValue("overig verkeersgebied")
    OVERIG_VERKEERSGEBIED("overig verkeersgebied");
    private final String value;

    TypeInfrastructuurWegT50Type(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeInfrastructuurWegT50Type fromValue(String v) {
        for (TypeInfrastructuurWegT50Type c: TypeInfrastructuurWegT50Type.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
