//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 10:59:53 AM CEST 
//


package nl.b3p.topnl.top50nl;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for WaterdeelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WaterdeelType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://register.geostandaarden.nl/gmlapplicatieschema/top50nl/1.1.1}_Top50nlObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="typeWater" type="{http://register.geostandaarden.nl/gmlapplicatieschema/top50nl/1.1.1}TypeWaterT50Type"/&gt;
 *         &lt;element name="breedteklasse" type="{http://register.geostandaarden.nl/gmlapplicatieschema/top50nl/1.1.1}BreedteklasseWaterT50Type" minOccurs="0"/&gt;
 *         &lt;element name="fysiekVoorkomen" type="{http://register.geostandaarden.nl/gmlapplicatieschema/top50nl/1.1.1}FysiekVoorkomenWaterT50Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="hoogteniveau" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="geometrie" type="{http://register.geostandaarden.nl/gmlapplicatieschema/top50nl/1.1.1}VlakOfLijnPropertyType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WaterdeelType", namespace = "http://register.geostandaarden.nl/gmlapplicatieschema/top50nl/1.1.1", propOrder = {
    "typeWater",
    "breedteklasse",
    "fysiekVoorkomen",
    "hoogteniveau",
    "geometrie"
})
public class WaterdeelType
    extends Top50NlObjectType
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TypeWaterT50Type typeWater;
    protected String breedteklasse;
    @XmlSchemaType(name = "string")
    protected List<FysiekVoorkomenWaterT50Type> fysiekVoorkomen;
    @XmlElement(required = true)
    protected BigInteger hoogteniveau;
    @XmlAnyElement
    protected Element geometrie;

    /**
     * Gets the value of the typeWater property.
     * 
     * @return
     *     possible object is
     *     {@link TypeWaterT50Type }
     *     
     */
    public TypeWaterT50Type getTypeWater() {
        return typeWater;
    }

    /**
     * Sets the value of the typeWater property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeWaterT50Type }
     *     
     */
    public void setTypeWater(TypeWaterT50Type value) {
        this.typeWater = value;
    }

    /**
     * Gets the value of the breedteklasse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBreedteklasse() {
        return breedteklasse;
    }

    /**
     * Sets the value of the breedteklasse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBreedteklasse(String value) {
        this.breedteklasse = value;
    }

    /**
     * Gets the value of the fysiekVoorkomen property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the fysiekVoorkomen property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFysiekVoorkomen().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FysiekVoorkomenWaterT50Type }
     * 
     * 
     */
    public List<FysiekVoorkomenWaterT50Type> getFysiekVoorkomen() {
        if (fysiekVoorkomen == null) {
            fysiekVoorkomen = new ArrayList<FysiekVoorkomenWaterT50Type>();
        }
        return this.fysiekVoorkomen;
    }

    /**
     * Gets the value of the hoogteniveau property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHoogteniveau() {
        return hoogteniveau;
    }

    /**
     * Sets the value of the hoogteniveau property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHoogteniveau(BigInteger value) {
        this.hoogteniveau = value;
    }

    /**
     * Gets the value of the geometrie property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     
     */
    public Element getGeometrie() {
        return geometrie;
    }

    /**
     * Sets the value of the geometrie property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     
     */
    public void setGeometrie(Element value) {
        this.geometrie = value;
    }

}
