name: "Cleanup and Maintainance"

on:
  workflow_dispatch:
  schedule:
    - cron: "16 23 * * 1"

jobs:
  dockercleanup:
    runs-on: ubuntu-latest
    name: "Pruning Untagged Images"
    # using https://github.com/marketplace/actions/ghcr-pruning
    steps:
      - name: "brmo-bgt-loader older than 1 week"
        uses: vlaurin/action-ghcr-prune@v0.3.0
        with:
          token: ${{ secrets.GHCR_CLEANUP_PAT }}
          organization: B3Partners
          container: brmo-bgt-loader
          dry-run: false
          older-than: 7
          keep-last: 1
          untagged: true
      - name: "brmo-service older than 1 week"
        uses: vlaurin/action-ghcr-prune@v0.3.0
        with:
          token: ${{ secrets.GHCR_CLEANUP_PAT }}
          organization: B3Partners
          container: brmo-service
          dry-run: false
          older-than: 7
          keep-last: 1
          untagged: true
      - name: "brmo-bag2-loader older than 1 week"
        continue-on-error: true
        uses: vlaurin/action-ghcr-prune@v0.3.0
        with:
          token: ${{ secrets.GHCR_CLEANUP_PAT }}
          organization: B3Partners
          container: brmo-bag2-loader
          dry-run: false
          older-than: 7
          keep-last: 1
          untagged: true
      - name: "brmo-bgt-loader older than 4 weeks"
        uses: vlaurin/action-ghcr-prune@v0.3.0
        with:
          token: ${{ secrets.GHCR_CLEANUP_PAT }}
          organization: B3Partners
          container: brmo-bgt-loader
          dry-run: false
          older-than: 28
          keep-last: 0
          untagged: true
      - name: "brmo-service older than 4 weeks"
        uses: vlaurin/action-ghcr-prune@v0.3.0
        with:
          token: ${{ secrets.GHCR_CLEANUP_PAT }}
          organization: B3Partners
          container: brmo-service
          dry-run: false
          older-than: 28
          keep-last: 0
          untagged: true
      - name: "brmo-bag2-loader older than 4 weeks"
        continue-on-error: true
        uses: vlaurin/action-ghcr-prune@v0.3.0
        with:
          token: ${{ secrets.GHCR_CLEANUP_PAT }}
          organization: B3Partners
          container: brmo-bag2-loader
          dry-run: false
          older-than: 28
          keep-last: 0
          untagged: true
