name: 'OWASP dependency check'

env:
  MAVEN_VERSION: '3.9.15'

on:
  pull_request:
    paths:
      - 'pom.xml'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/owasp-dependency-check.yml'
  schedule:
    - cron: "19 3 * * 1-5"
      timezone: 'Europe/Amsterdam'
  workflow_dispatch:

jobs:
  check:
    name: 'OWASP dependency check'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      security-events: write
    steps:
      - uses: actions/checkout@v7

      - name: 'Set up JDK'
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: 'maven'

      - name: 'Set up Maven'
        uses: stCarolas/setup-maven@v5.1
        with:
          maven-version: ${{ env.MAVEN_VERSION }}

      - name: 'Run Check'
        continue-on-error: true
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: mvn -U package -DnvdApiKey=${{ secrets.NVD_API_KEY }} -Dmaven.test.skip=true -Ddocker.skip=true -Dtest.onlyITs= -DskipQA=true org.owasp:dependency-check-maven:aggregate -fae -B -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -DfailBuildOnCVSS=5

      - name: 'Check sarif file'
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: 'target/dependency-check-report.sarif'

      - name: 'Upload result to GitHub Code Scanning'
        uses: github/codeql-action/upload-sarif@v4
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          sarif_file: target/dependency-check-report.sarif
