name: 'Release Drafter'

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    name: 'Update release Draft'
    permissions:
      contents: write
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
