name: 'REUSE Compliance Check'

on:
  - pull_request

jobs:
  reusecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # Only check a few subdirectories for now
      - name: 'REUSE Compliance Check (BGT loader)'
        uses: fsfe/reuse-action@v6
        with:
          args: --root bgt-loader lint

      - name: 'REUSE Compliance Check (BAG2 loader)'
        uses: fsfe/reuse-action@v6
        with:
          args: --root bag2-loader lint

      - name: 'REUSE Compliance Check (NHR loader)'
        uses: fsfe/reuse-action@v6
        with:
          args: --root nhr-loader lint