INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('1', 'Beklemrecht');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('2', 'Eigendom (recht van)');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('3', 'Erfpacht (recht van)');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('4', 'Gebruik en bewoning (recht van)');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('5', 'Grondrente (recht van)');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('6', 'Huurrecht (zakelijk)');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('7', 'Opstal (recht van)');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('8', 'Optierecht (zakelijk)');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('9', 'Oud-vaderlandsrecht');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('10', 'Zakelijk recht (als bedoeld in artikel 5, lid 3, onder b)');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('11', 'Stadsmeierrecht');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('12', 'Vruchtgebruik (recht van)');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('13', 'Erfpacht en Opstal (recht van)');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('14', 'Opstalrecht Nutsvoorzieningen');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('15', 'Eigendom Telecommunicatienetwerk');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('16', 'Erfpachtrecht Telecommunicatienetwerk');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('17', 'Vruchtgebruik Telecommunicatienetwerk');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('18', 'Overige zakelijke rechten');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('19', 'Voorrecht');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('20', 'Zakelijk recht na twee of meer zakelijke belastingen');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('21', 'Zakelijke belasting derde of volgende');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('22', 'BP-recht');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('23', 'Opstalrecht Nutsvoorzieningen op gedeelte van perceel');
INSERT INTO aard_recht_verkort (aand, omschr) VALUES ('24', 'Zakelijk recht op gedeelte van perceel (als bedoeld in artikel 5, lid 3, onder b)');
